lang_dict = {
    ('*', '3D View: Stored Views'): '3D 视图：保存视图',
    ('*', 'Stored Views'): '保存视图',
    ('*', 'Save and restore User defined views, pov, layers and display configs'): '保存与恢复用户定义的视图，POV，图层与显示配置',
    ('*', 'View3D > Sidebar > View > Stored Views'): '3D 视图 > 边栏 > 视图 > 保存视图',
    ('*', 'Initialize'): '初始化',
    ('*', 'Enable I/O Operators'): '启用导入导出操作',
    ('*', '3D view update'): '3D 视图更新率',
    ('Operator', 'Import Stored Views preset'): '导入视图预设',
    ('Operator', 'Export Stored Views preset'): '导出视图预设',
    ('Operator', 'Camera To view'): '相机到视图',
    ('Operator', 'New Camera To View'): '新相机到视图',
    ('Operator', 'Save Current'): '保存当前',
    ('Operator', 'Import from Scene'): '从场景导入',
    ('*', 'Camera Selector'): '相机选择',
    ('Operator', 'Preview Camera'): '预览相机',
    ('Operator', 'Add Camera Marker'): '添加相机标记',
    ('*', 'Set chosen camera as the scene\'s active camera'): '设置选择的相机为场景活动相机',
    ('*', 'Preview chosen camera and make scene\'s active camera'): '预览选择的相机并设置为场景活动相机',

}