lang_dict = {
    ('*', 'Align Tools'): '对齐工具',
    ('*', 'Object: Align Tools'): '对象：对齐工具',
    ('*', 'Align Selected Objects to Active Object'): '将所选对象与活动对象对齐',
    ('*', 'View3D > Sidebar > Item Tab'): '3D 视图 > 边栏 > 条目 选项卡',

    ('*', 'Active object is: '): '活动对象是：',
    ('*', 'Align Loc + Rot:'): '对齐位置与旋转：',
    ('*', 'Align Location:'): '对齐位置：',
    ('*', 'Align Rotation:'): '对齐旋转：',
    ('*', 'Align Scale:'): '对齐旋转：',
    ('*', 'Advanced Align Operations'): '调整对齐操作',
    ('Operator', 'Advanced'): '调整对齐操作',
    ('*', 'Match Scale:'): '匹配缩放：',
    ('*', 'Fit Dimensions:'): '拟合尺寸：',
    ('*', 'Active too'): '调整活动对象',
    ('*', 'Consistent Selection'): '一致的选择',
    ('*', 'Self'): '自身',
    ('Operator', 'Align Operator'): '活动操作',
}