lang_dict = {
    ('*', 'Building Tools'): '建筑工具',
    ('*', 'Mesh: Building Tools'): '网格：建筑工具',
    ('*', 'Building Creation Tools'): '建筑创建工具',
    ('*', 'View3D > Toolshelf > Building Tools'): '3D 视图 > 边栏 > 建筑工具',

    ('Operator', 'Create Floorplan'): '创建地面',  
    ('*', 'Cap Triangles'): '三角形封顶',
    ('*', 'Fan Length 1'): '扇长1',
    ('*', 'Fan Length 2'): '扇长2',
    ('*', 'Fan Length 3'): '扇长3',
    ('*', 'Fan Length 4'): '扇长4',
    ('*', 'H-Shaped'): 'H-字型',
    ('*', 'Tail Width 1'): '角宽1',
    ('*', 'Tail Length 1'): '角长1',
    ('*', 'Tail Width 2'): '角宽2',
    ('*', 'Tail Length 2'): '角长2',
    ('*', 'Tail Width 3'): '角宽3',
    ('*', 'Tail Length 3'): '角长3',
    ('*', 'Tail Width 4'): '角宽4',
    ('*', 'Tail Length 4'): '角长4',
    ('*', 'Random Extension Amount'): '随机扩展数量',
    ('*', 'Extension Amount'): '扩展数量',

    ('Operator', 'Add Floors'): '添加楼层',
    ('*', 'Floor Count'): '层数',
    ('*', 'Floor Height'): '层高',
    ('*', 'Add Slab'): '添加隔板',
    ('*', 'Slab Thickness'): '隔板厚度',
    ('*', 'Slab Outset'): '隔板外插',
    ('*', 'Add Columns'): '添加柱',

    ('Operator', 'Add Roof'): '添加屋顶',
    ('*', 'Add Border'): '添加边',
    ('*', 'Gable'): '山墙',
    ('*', 'OPEN'): '开放',
    ('*', 'BOX'): '包裹',
    ('*', 'Hip'): '关节',

    ('Operator', 'Add Balcony'): '添加阳台',
    ('*', 'Depth Offset'): '深度偏移',
    ('*', 'Slab Height'): '隔板高',
    ('*', 'Add Railing'): '添加栏杆',
    ('*', 'Railing Offset'): '栏杆偏移',
    ('*', 'Posts'): '立柱',
    ('*', 'Add Bottom Rail'): '添加底部横栏',
    ('*', 'Rail Offset'): '横栏偏移',
    ('*', 'Corner Posts'): '立柱角',
    ('*', 'Rails'): '横栏',
    ('*', 'Rail Density'): '横栏密度',
    ('*', 'Rail Size'): '横栏尺寸',
    ('*', 'Wall Width'): '墙宽',

    ('Operator', 'Add Stairs'): '添加楼梯',
    ('*', 'Step Count'): '步数',
    ('*', 'Step Height'): '步高',
    ('*', 'Step Width'): '步宽',
    ('*', 'Filled'): '填充',
    ('*', 'Blocked'): '块',
    ('*', 'Has Landing'): '有平台',
    ('*', 'Landing Width'): '平台宽度',

    ('Operator', 'Add Window'): '添加窗子',
    ('*', 'Frame Depth'): '框架深度',
    ('*', 'Frame Thickness'): '框架厚度',
    ('*', 'Window Depth'): '窗子深度',
    ('*', 'Add Arch'): '添加拱顶',
    ('*', 'Arc Resolution'): '弧分辨率',
    ('*', 'Arc Depth'): '弧深度',
    ('*', 'Arc Height'): '弧高度',

    ('Operator', 'Add Door'): '添加门',
    ('*', 'Door Depth'): '门深度',
    ('*', 'Double Door'): '双门',
    ('*', 'Panels'): '面',
    ('*', 'Horizontal Panels'): '横向面数',
    ('*', 'Vertical Panels'): '垂直面数',
    ('*', 'Panel Border'): '面边框',
    ('*', 'Panel Margin'): '面空间',
    ('*', 'Panel Depth'): '面深度',
    ('*', 'Glass Panes'): '玻璃窗格',
    ('*', 'Glass_Panes'): '玻璃窗格',
    ('*', 'Horizontal glass panes'): '横向窗格数',
    ('*', 'Vertical glass panes'): '垂直窗格数',
    ('*', 'Glass Pane Margin'): '玻璃格空间',
    ('*', 'Glass Pane Depth'): '玻璃格深度',
    ('*', 'Louver'): '百叶窗',
    ('*', 'Louver Margin'): '百叶窗空间',
    ('*', 'Louver Count'): '百叶窗叶数',
    ('*', 'Louver Depth'): '百叶窗深度',
    ('*', 'Louver Border'): '百叶窗边框',

    ('Operator', 'Add Multigroup'): '添加一组门窗',
    ('*', 'Window Height'): '窗高度',
    ('*', 'Components'): '组件',
    ('*', 'Door/Window Depth'): '门窗深度',
    
    ('*', 'Material Tools'): '材质工具',
    ('*', 'Unwrap'): '展开',
    ('*', 'Cube_Projection'): '立方体投影',
    ('Operator', 'Assign New Material'): '分配新材质',
}