# -*- coding: utf-8 -*-

lang_dict = {
   ('*', 'Building Tools') : '建築工具',
   ('*', 'Mesh: Building Tools') : '網格：建築工具',
   ('*', 'Building Creation Tools') : '建築創建工具',
   ('*', 'View3D > Toolshelf > Building Tools') : '3D 視圖 > 邊欄 > 建築工具',
   ('Operator', 'Create Floorplan') : '創建地面',
   ('*', 'Cap Triangles') : '三角形封頂',
   ('*', 'Fan Length 1') : '扇長1',
   ('*', 'Fan Length 2') : '扇長2',
   ('*', 'Fan Length 3') : '扇長3',
   ('*', 'Fan Length 4') : '扇長4',
   ('*', 'H-Shaped') : 'H-字型',
   ('*', 'Tail Width 1') : '角寬1',
   ('*', 'Tail Length 1') : '角長1',
   ('*', 'Tail Width 2') : '角寬2',
   ('*', 'Tail Length 2') : '角長2',
   ('*', 'Tail Width 3') : '角寬3',
   ('*', 'Tail Length 3') : '角長3',
   ('*', 'Tail Width 4') : '角寬4',
   ('*', 'Tail Length 4') : '角長4',
   ('*', 'Random Extension Amount') : '隨機擴展數量',
   ('*', 'Extension Amount') : '擴展數量',
   ('Operator', 'Add Floors') : '添加樓層',
   ('*', 'Floor Count') : '層數',
   ('*', 'Floor Height') : '層高',
   ('*', 'Add Slab') : '添加隔板',
   ('*', 'Slab Thickness') : '隔板厚度',
   ('*', 'Slab Outset') : '隔板外插',
   ('*', 'Add Columns') : '添加柱',
   ('Operator', 'Add Roof') : '添加屋頂',
   ('*', 'Add Border') : '添加邊',
   ('*', 'Gable') : '山牆',
   ('*', 'OPEN') : '開放',
   ('*', 'BOX') : '包裹',
   ('*', 'Hip') : '關節',
   ('Operator', 'Add Balcony') : '添加陽臺',
   ('*', 'Depth Offset') : '深度偏移',
   ('*', 'Slab Height') : '隔板高',
   ('*', 'Add Railing') : '添加欄杆',
   ('*', 'Railing Offset') : '欄杆偏移',
   ('*', 'Posts') : '立柱',
   ('*', 'Add Bottom Rail') : '添加底部橫欄',
   ('*', 'Rail Offset') : '橫欄偏移',
   ('*', 'Corner Posts') : '立柱角',
   ('*', 'Rails') : '橫欄',
   ('*', 'Rail Density') : '橫欄密度',
   ('*', 'Rail Size') : '橫欄尺寸',
   ('*', 'Wall Width') : '牆寬',
   ('Operator', 'Add Stairs') : '添加樓梯',
   ('*', 'Step Count') : '步數',
   ('*', 'Step Height') : '步高',
   ('*', 'Step Width') : '步寬',
   ('*', 'Filled') : '填充',
   ('*', 'Blocked') : '塊',
   ('*', 'Has Landing') : '有平臺',
   ('*', 'Landing Width') : '平臺寬度',
   ('Operator', 'Add Window') : '添加窗子',
   ('*', 'Frame Depth') : '框架深度',
   ('*', 'Frame Thickness') : '框架厚度',
   ('*', 'Window Depth') : '窗子深度',
   ('*', 'Add Arch') : '添加拱頂',
   ('*', 'Arc Resolution') : '弧分辨率',
   ('*', 'Arc Depth') : '弧深度',
   ('*', 'Arc Height') : '弧高度',
   ('Operator', 'Add Door') : '添加門',
   ('*', 'Door Depth') : '門深度',
   ('*', 'Double Door') : '雙門',
   ('*', 'Panels') : '面',
   ('*', 'Horizontal Panels') : '橫向面數',
   ('*', 'Vertical Panels') : '垂直面數',
   ('*', 'Panel Border') : '面邊框',
   ('*', 'Panel Margin') : '面空間',
   ('*', 'Panel Depth') : '面深度',
   ('*', 'Glass Panes') : '玻璃窗格',
   ('*', 'Glass_Panes') : '玻璃窗格',
   ('*', 'Horizontal glass panes') : '橫向窗格數',
   ('*', 'Vertical glass panes') : '垂直窗格數',
   ('*', 'Glass Pane Margin') : '玻璃格空間',
   ('*', 'Glass Pane Depth') : '玻璃格深度',
   ('*', 'Louver') : '百葉窗',
   ('*', 'Louver Margin') : '百葉窗空間',
   ('*', 'Louver Count') : '百葉窗葉數',
   ('*', 'Louver Depth') : '百葉窗深度',
   ('*', 'Louver Border') : '百葉窗邊框',
   ('Operator', 'Add Multigroup') : '添加一組門窗',
   ('*', 'Window Height') : '窗高度',
   ('*', 'Components') : '組件',
   ('*', 'Door/Window Depth') : '門窗深度',
   ('*', 'Material Tools') : '材質工具',
   ('*', 'Unwrap') : '展開',
   ('*', 'Cube_Projection') : '立方體投影',
   ('Operator', 'Assign New Material') : '分配新材質',
}