lang_dict = {
    ('*', 'BlenderKit Online Asset Library'): 'BlenderKit 在线资产库',
    ('*', '3D View: BlenderKit Online Asset Library'): '3D 视图：BlenderKit 在线资产库',
    ('*', 'Online BlenderKit library (materials, models, brushes and more). Connects to the internet.'): '在线 BlenderKit 在线库（材质，模型，画笔和更多）。',
    ('*', 'View3D > Properties > BlenderKit'): '3D 视图 > 属性 > BlenderKit',
    ('*', 'Show assetbar when starting blender'): '在 Blender 启动时显示资产栏',
    ('Operator', 'Sign up'): '注册',
    ('*', 'Your API Key'): '您的 API Key',
    ('*', 'Global Files Directory'): '全局文件夹',
    ('*', 'Project Assets Subdirectory'): '项目资产子文件夹',
    ('*', 'Use Directories'): '使用文件夹',
    ('*', 'Global and subdir'): '全局和子文件夹',
    ('*', 'Use GPU for Thumbnails Rendering'): '使用 GPU 渲染缩略图',
    ('*', 'Assetbar thumbnail Size'): '资产栏缩略图尺寸',
    ('*', 'Max Assetbar Rows'): '最大资产栏列数',
    ('*', 'Show tips when starting blender'): '在 Blender 启动时显示提示',
    ('*', 'Show BlenderKit search in 3D view header'): '在 3D 视图头部显示 BlenderKit 搜索',
    ('*', 'Use timers'): '使用计时器',
    ('*', 'Login through browser'): '通过浏览器登录',
    ('*', 'in progress.'): '操作中。',
    ('Operator', 'Cancel'): '取消',
    ('*', 'BlenderKit Profile'): 'BlenderKit 配置',
    ('*', 'Me:'): '我：',
    ('*', 'My plan:'): '我的计划：',
    ('*', 'Free plan'): '免费计划',
    ('Operator', 'Change plan'): '更改计划',
    ('Operator', 'See my uploads'): '查看上传的文件',
    ('*', 'BlenderKit Login'): 'BlenderKit 登录',
    ('Operator', 'Login as someone else'): '更改登录帐号',
    ('*', 'Find and Upload Assets'): '查找与上传资产',
    ('*', 'Upload'): '上传',
    ('*', 'Models'): '模型',
    ('Operator', 'BlenderKit Asset Bar UI'): 'BlenderKit 资产栏界面',
    ('*', 'Click to Hide Asset Bar'): '点击隐藏资产栏',
    ('*', 'Click to Show Asset Bar'): '点击显示资产栏',
    ('*', 'My Assets'): '我的资产',
    ('*', 'BlenderKit searching....'): 'BlenderKit 正在搜索……',
    ('*', 'Search filters'): '搜索过滤',
    ('*', 'texture types'): '材质类型',
    ('*', 'Procedural'): '程序化纹理',
    ('*', 'Texture based'): '基于纹理',
    ('*', 'File size ( min - max MB)'): '文件大小（MB)',
    ('*', 'min'): '最小',
    ('*', 'max'): '最大',
    ('*', 'Categories'): '分类',
    ('*', 'Run Search'): '执行搜索',
    ('*', 'Keep Running'): '保持执行',
    ('*', 'Free Only'): '仅免费',
    ('*', 'tooltip'): '工具提示',
    ('*', 'Import settings'): '导入设置',
    ('*', 'Auto-Map'): '自动映射',
    ('*', 'Selected Model'): '选择的模型',
    ('*', 'To upload this asset to'): '要上传此资产到',
    ('*', 'BlenderKit, go to the Find and'): 'Blender, 转到查找与',
    ('*', 'Upload Assets panel.'): '上传资产面板',
    ('Operator', 'Hide asset preview - ;'): '隐藏资产预览',
    ('*', 'Show/Hide asset preview'): '显示或隐藏资产预览',
    ('Operator', 'Read upload instructions'): '阅读上传说明',
    ('Operator', 'Upload material'): '上传材质',
    ('*', 'animal'): '动物',
    ('*', 'asphalt'): '沥青',
    ('*', 'bricks'): '砖',
    ('*', 'ceramic'): '陶瓷',
    ('*', 'concrete'): '混凝土',
    ('*', 'dirt'): '污垢',
    ('*', 'fabric'): '织物',
    ('*', 'floor'): '地板',
    ('*', 'food'): '食品',
    ('*', 'food'): '食品',
    ('*', 'fx'): '特效',
    ('*', 'glass'): '玻璃',
    ('*', 'grass'): '草',
    ('*', 'ground'): '地面',
    ('*', 'ice'): '冰',
    ('*', 'leather'): '皮革',
    ('*', 'liquid'): '液体',
    ('*', 'metal'): '金属',
    ('*', 'organic'): '有机物',
    ('*', 'ornaments'): '饰品',
    ('*', 'paper'): '纸',
    ('*', 'paving'): '路面',
    ('*', 'plaster'): '石膏',
    ('*', 'plastic'): '塑料',
    ('*', 'rock'): '岩石',
    ('*', 'roofing'): '屋顶',
    ('*', 'rubber'): '橡胶',
    ('*', 'rust'): '铁锈',
    ('*', 'sand'): '沙',
    ('*', 'stone'): '石头',
    ('*', 'tech'): '科技',
    ('*', 'tiles'): '砖瓦',
    ('*', 'wood'): '树木',
    ('*', 'Private'): '私有',
    ('*', 'Public'): '公开',
    ('*', 'license'): '许可',
    ('*', 'Tags'): '标签',
    ('*', 'Free for Everyone'): '对所有人免费',
    ('*', 'Pure PBR Compatible'): '兼容纯 PBR',
    ('*', 'Needs UV'): '需要 UV',
    ('*', 'Texture Size in Meters'): '纹理大小（以米为单位）',
    ('*', 'Thumbnail'): '缩略图',
    ('*', 'Please add thumbnail(jpg, at least'): '请增加缩略图(jpg, 至少',
    ('Operator', 'Render thumbnail with Cycles'): '使用 Cycles 渲染缩略图',
    ('Operator', 'Upload model'): '上传模型',
    ('*', 'Subcategory'): '子类别',
    ('Operator', 'Generate thumbnail'): '生成缩略图',
    ('*', 'Production Level'): '生成级别',
    ('*', 'condition'): '条件',
    ('*', 'PBR Compatible'): 'PBR 兼容',
    ('*', 'design props:'): '设计属性：',
    ('*', 'Manufacturer'): '制造商',
    ('*', 'Designer'): '设计师',
    ('*', 'Design Collection'): '设计集合',
    ('*', 'Variant'): '变体',
    ('*', 'Use Design Year'): '使用设计年份',
    ('*', 'Design Year'): '设计年份',
    ('*', 'Work Hours'): '工作小时',
    ('*', 'Adult Content'): '成人内容',
    ('*', 'Realistic'): '真实',
    ('*', 'Painterly'): '绘画',
    ('*', 'Lowpoly'): '低面',
    ('*', 'Anime'): '动漫',
    ('*', '2D Vector'): '2D 矢量',
    ('*', '3D Graphics'): '3D 图形',
    ('*', 'Finished'): '完成',
    ('*', 'Template'): '模版',
    ('*', 'Unspecified'): '未定义',
    ('*', 'Used'): '已使用',
    ('*', 'Desolate'): '无效的',
    ('Operator', 'Upload brush'): '上传笔刷',
    ('*', 'Free only'): '仅免费',
    ('*', 'Import method:'): '导入方式：',
    ('*', 'Perpendicular snap'): '垂直快照',
    ('*', 'designed in ( min - max )'): '设计年代',
    ('*', 'Poly count in ( min - max )'): '几何数量',
    ('*', 'texture resolution ( min - max )'): '纹理分辨率',
}