# -*- coding: utf-8 -*-

lang_dict = {
   ('*', 'BlenderKit Online Asset Library') : 'BlenderKit 在線資產庫',
   ('*', '3D View: BlenderKit Online Asset Library') : '3D 視圖：BlenderKit 在線資產庫',
   ('*', 'Online BlenderKit library (materials, models, brushes and more). Connects to the internet.') : '在線 BlenderKit 在線庫（材質，模型，畫筆和更多）。',
   ('*', 'View3D > Properties > BlenderKit') : '3D 視圖 > 屬性 > BlenderKit',
   ('*', 'Show assetbar when starting blender') : '在 Blender 啟動時顯示資產欄',
   ('Operator', 'Sign up') : '註冊',
   ('*', 'Your API Key') : '您的 API Key',
   ('*', 'Global Files Directory') : '全局文件夾',
   ('*', 'Project Assets Subdirectory') : '項目資產子文件夾',
   ('*', 'Use Directories') : '使用文件夾',
   ('*', 'Global and subdir') : '全局和子文件夾',
   ('*', 'Use GPU for Thumbnails Rendering') : '使用 GPU 渲染縮略圖',
   ('*', 'Assetbar thumbnail Size') : '資產欄縮略圖尺寸',
   ('*', 'Max Assetbar Rows') : '最大資產欄列數',
   ('*', 'Show tips when starting blender') : '在 Blender 啟動時顯示提示',
   ('*', 'Show BlenderKit search in 3D view header') : '在 3D 視圖頭部顯示 BlenderKit 搜索',
   ('*', 'Use timers') : '使用計時器',
   ('*', 'Login through browser') : '通過瀏覽器登錄',
   ('*', 'in progress.') : '操作中。',
   ('Operator', 'Cancel') : '取消',
   ('*', 'BlenderKit Profile') : 'BlenderKit 配置',
   ('*', 'Me:') : '我：',
   ('*', 'My plan:') : '我的計劃：',
   ('*', 'Free plan') : '免費計劃',
   ('Operator', 'Change plan') : '更改計劃',
   ('Operator', 'See my uploads') : '查看上傳的文件',
   ('*', 'BlenderKit Login') : 'BlenderKit 登錄',
   ('Operator', 'Login as someone else') : '更改登錄帳號',
   ('*', 'Find and Upload Assets') : '查找與上傳資產',
   ('*', 'Upload') : '上傳',
   ('*', 'Models') : '模型',
   ('Operator', 'BlenderKit Asset Bar UI') : 'BlenderKit 資產欄界面',
   ('*', 'Click to Hide Asset Bar') : '點擊隱藏資產欄',
   ('*', 'Click to Show Asset Bar') : '點擊顯示資產欄',
   ('*', 'My Assets') : '我的資產',
   ('*', 'BlenderKit searching....') : 'BlenderKit 正在搜索……',
   ('*', 'Search filters') : '搜索過濾',
   ('*', 'texture types') : '材質類型',
   ('*', 'Procedural') : '程序化紋理',
   ('*', 'Texture based') : '基於紋理',
   ('*', 'File size ( min - max MB)') : '文件大小（MB)',
   ('*', 'min') : '最小',
   ('*', 'max') : '最大',
   ('*', 'Categories') : '分類',
   ('*', 'Run Search') : '執行搜索',
   ('*', 'Keep Running') : '保持執行',
   ('*', 'Free Only') : '僅免費',
   ('*', 'tooltip') : '工具提示',
   ('*', 'Import settings') : '導入設置',
   ('*', 'Auto-Map') : '自動映射',
   ('*', 'Selected Model') : '選擇的模型',
   ('*', 'To upload this asset to') : '要上傳此資產到',
   ('*', 'BlenderKit, go to the Find and') : 'Blender, 轉到查找與',
   ('*', 'Upload Assets panel.') : '上傳資產面板',
   ('Operator', 'Hide asset preview - ;') : '隱藏資產預覽',
   ('*', 'Show/Hide asset preview') : '顯示或隱藏資產預覽',
   ('Operator', 'Read upload instructions') : '閱讀上傳說明',
   ('Operator', 'Upload material') : '上傳材質',
   ('*', 'animal') : '動物',
   ('*', 'asphalt') : '瀝青',
   ('*', 'bricks') : '磚',
   ('*', 'ceramic') : '陶瓷',
   ('*', 'concrete') : '混凝土',
   ('*', 'dirt') : '汙垢',
   ('*', 'fabric') : '織物',
   ('*', 'floor') : '地板',
   ('*', 'food') : '食品',
   ('*', 'fx') : '特效',
   ('*', 'glass') : '玻璃',
   ('*', 'grass') : '草',
   ('*', 'ground') : '地面',
   ('*', 'ice') : '冰',
   ('*', 'leather') : '皮革',
   ('*', 'liquid') : '液體',
   ('*', 'metal') : '金屬',
   ('*', 'organic') : '有機物',
   ('*', 'ornaments') : '飾品',
   ('*', 'paper') : '紙',
   ('*', 'paving') : '路面',
   ('*', 'plaster') : '石膏',
   ('*', 'plastic') : '塑料',
   ('*', 'rock') : '岩石',
   ('*', 'roofing') : '屋頂',
   ('*', 'rubber') : '橡膠',
   ('*', 'rust') : '鐵鏽',
   ('*', 'sand') : '沙',
   ('*', 'stone') : '石頭',
   ('*', 'tech') : '科技',
   ('*', 'tiles') : '磚瓦',
   ('*', 'wood') : '樹木',
   ('*', 'Private') : '私有',
   ('*', 'Public') : '公開',
   ('*', 'license') : '許可',
   ('*', 'Tags') : '標籤',
   ('*', 'Free for Everyone') : '對所有人免費',
   ('*', 'Pure PBR Compatible') : '兼容純 PBR',
   ('*', 'Needs UV') : '需要 UV',
   ('*', 'Texture Size in Meters') : '紋理大小（以米為單位）',
   ('*', 'Thumbnail') : '縮略圖',
   ('*', 'Please add thumbnail(jpg, at least') : '請增加縮略圖(jpg, 至少',
   ('Operator', 'Render thumbnail with Cycles') : '使用 Cycles 渲染縮略圖',
   ('Operator', 'Upload model') : '上傳模型',
   ('*', 'Subcategory') : '子類別',
   ('Operator', 'Generate thumbnail') : '生成縮略圖',
   ('*', 'Production Level') : '生成級別',
   ('*', 'condition') : '條件',
   ('*', 'PBR Compatible') : 'PBR 兼容',
   ('*', 'design props:') : '設計屬性：',
   ('*', 'Manufacturer') : '製造商',
   ('*', 'Designer') : '設計師',
   ('*', 'Design Collection') : '設計集合',
   ('*', 'Variant') : '變體',
   ('*', 'Use Design Year') : '使用設計年份',
   ('*', 'Design Year') : '設計年份',
   ('*', 'Work Hours') : '工作小時',
   ('*', 'Adult Content') : '成人內容',
   ('*', 'Realistic') : '真實',
   ('*', 'Painterly') : '繪畫',
   ('*', 'Lowpoly') : '低面',
   ('*', 'Anime') : '動漫',
   ('*', '2D Vector') : '2D 矢量',
   ('*', '3D Graphics') : '3D 圖形',
   ('*', 'Finished') : '完成',
   ('*', 'Template') : '模版',
   ('*', 'Unspecified') : '未定義',
   ('*', 'Used') : '已使用',
   ('*', 'Desolate') : '無效的',
   ('Operator', 'Upload brush') : '上傳筆刷',
   ('*', 'Free only') : '僅免費',
   ('*', 'Import method:') : '導入方式：',
   ('*', 'Perpendicular snap') : '垂直快照',
   ('*', 'designed in ( min - max )') : '設計年代',
   ('*', 'Poly count in ( min - max )') : '幾何數量',
   ('*', 'texture resolution ( min - max )') : '紋理分辨率',
}