lang_dict = {
    ('*', 'Cutters'):'切刀',
    ('*', 'None'): '无',
    ('*', 'Interaction'): '交互',
    ('*', 'Array'): '阵列',
    ('*', 'Axis'): '轴',
    ('*', 'Behavior'): '行为',
    ('*', 'Solidify'): '实体化',
    ('*', 'Bevel'): '倒角',
    ('*', 'Mirror'): '镜像',
    ('*', 'Collection'): '集合',
    ('*', 'Color'): '颜色',
    ('*', 'Display'): '显示',
    ('*', 'Shape'): '形状',
    ('*', 'Keymap'): '键位映射',
    ('*', 'Settings'): '偏好设置',
    ('*', 'Ngon'): '多边形',
    ('*', 'Circle'): '圆形',
    ('*', 'Box'): '圆形',
    ('*', 'Cut'): '剪切',
    ('*', 'Slice'): '切缝',
    ('*', 'Snap'): '吸附',
    ('*', 'Inset'): '内插',
    ('*', 'Join'): '接合',
    ('*', 'Make'): '构建',
    ('*', 'Knife'): '切刀',
    ('*', 'Extract'): '挤出',
    ('*', 'Negative'): '负',
    ('*', 'Snap Point'): '吸附到点',
    ('*', 'Snap point'): '吸附到点',
    ('*', 'Snap Edges'): '吸附到线',
    ('*', 'Snap Faces'): '吸附到面',
    ('*', 'Snap Grid'): '吸附到网格',
    ('*', 'Highlight'): '高亮',
    ('*', 'Offset'): '偏移',
    ('*', 'Dot'): '点',
    ('*', 'Wire'): '线',
    ('*', 'Grid'): '网格',
    ('*', 'Live'): '实时',
    ('*', 'Auto Hide'): '自动隐藏',
    ('*', 'Active only'): '仅激活',
    ('*', 'Quick Execute'): '快速执行',
    ('*', 'Auto Ortho'): '自动正交模式',
    ('*', 'Grid Mode Color'): '网格模式颜色',
    ('*', 'Grid Wire'): '网格线',
    ('*', 'Show Shape'): '显示形状',
    ('*', 'Show Shape Wire'): '显示形状线',
    ('*', 'Wire Width'): '线宽',
    ('*', 'Show Bounds'): '显示界限',
    ('*', 'Allow Selection'): '可选中',
    ('*', 'Auto Smooth'): '自动平滑',
    ('*', 'Sort Modifiers'): '排序修改器',
    ('*', 'Keep Modifiers'): '保持修改器',
    ('*', 'Ngon Snap Angle'): 'Ngon 吸附角',
    ('*', 'Bevel Dot'): '倒角点',
    ('*', 'Dot Highlight'): '点高亮',
    ('*', 'Simple Topbar'): '简单顶部栏',
    ('*', 'Topbar'): '顶部栏',
    ('*', 'Destructive Menu'): '破坏性菜单',
    ('*', 'Mode Label'): '模式标签',
    ('*', 'Shape Label'): '形状标签',
    ('*', 'Operation Label'): '操作标签',
    ('*', 'Surface Label'): '表（曲）面标签',
    ('*', 'Fix Label Size'): '修正标签尺寸',
    ('*', 'Topbar Padding'): '顶部栏填充',
    ('*', 'Pad Menus'): '便笺菜单',
    ('*', 'Middle Padding'): '中间填充',
    ('*', 'Fade Timing'): '渐隐时间',
    ('*', 'Settings to display'): '显示的设置',
    ('*', 'Use default behavior'): '使用默认行为',
    ('*', 'Modal Shortcut: X'): '模式快捷键：X',
    ('*', 'Modal Shortcut: Y'): '模式快捷键：Y',
    ('*', 'Modal Shortcut: Z'): '模式快捷键：Z',
    ('*', 'Start Operation'): '开始动作',
    ('*', 'Non-Destructive'): '非破坏性',
    ('*', 'Circle Vertices'): '圆点数',
    ('*', 'Inset Thickness'): '内插厚度',
    ('*', 'Array Count'): '阵列数',
    ('*', 'Solidify Thickness'): '实体化厚度',
    ('*', 'Bevel Width'): '倒角宽度',
    ('*', 'Lazorcut Limit'): '切割限制',
    ('*', 'Bevel Segments'): '倒角段数',
    ('*', 'Quad Bevel'): '四倍倒角',
    ('*', 'Straight Corner Flow'): '直角流',
    ('*', 'Destructive'): '破坏性',
    ('*', 'Apply Boolean'): '应用布尔',
    ('*', 'Apply Slices'): '应用切片',
    ('*', 'Shift to Active'): '切换到激活',
    ('*', 'Simple Trace'): '简单跟踪',
    ('*', 'Use DPI Factoring'): '使用 DPI 因子',
    ('*', 'Join Flip Z'): '接合翻转 Z',
    ('*', 'Parent Shape'): '父级形状',
    ('*', 'Accucut Lazorcut'): '精确切割',
    ('*', 'Reduce Opacity in Edit'): '编辑时减少不透明度',
    ('*', 'Wires Only'): '仅显示线框',
    ('*', 'Thick Wire'): '细线',
    ('*', 'Wire Size Multiplier'): '线宽倍数',
    ('*', 'Snap Dot Size'): '吸附点尺寸',
    ('*', 'Snap Dot Detection Factor'): '吸附点检测因子',
    ('*', 'Dot Size'): '点尺寸',
    ('*', 'Dot Detection Factor'): '点检测因子',
    ('*', 'Activate BoxCutter'): '激活 BoxCutter',
    ('*', 'Enable Surface Toggle'): '启用平（曲）面切换',
    ('*', 'Enable Topbar'): '启用顶部栏',
    ('*', 'Disable Ctrl & Shift LMB (Edit Mode)'): '编辑模式禁用 Ctrl & Shift LMB',
    ('*', 'Preserve Alt'): '保留 Alt',
    ('*', 'RMB Cancel Ngon'): '右键取消多边形',
    ('*', 'Alt Center'): 'Alt 为中心',
    ('*', 'Shift Uniform'): 'Alt 正规化',
    ('*', 'Scroll Adjust Circle'): '滚动调整圆',
    ('*', '\n Default State (no modifier)'): '\n 默认状态（无修改器）',
    ('*', '\n Starts drawing with Array active'): '\n 在阵列激活时开始绘图',
    ('*', '\n Starts drawing with Solidify active'): '\n 在实体化激活时开始绘图',
    ('*', '\n Starts drawing with Bevel active'): '\n 在倒角激活时开始绘图',
    ('*', '\n Starts drawing with Mirror active'): '\n 在镜像激活时开始绘图',
    ('*', '\n Assign collection for shape objects'): '\n 分配形状对象的集合',
    ('*', '\n Assign shape object'): '\n 分配形状对象',
    ('*', 'Show grid gizmo'): '显示网络 gizmo',
    ('*', 'Show cursor gizmo'): '显示3D光标 gizmo',
    ('*', 'Show transform gizmo'): '显示变换 gizmo',
    ('*', 'Axis to be used'): '使用的轴',
    ('*', '\n Quickly execute cuts on release'): '\n 释放时快速执行剪切',
    ('*', '\n Automatically enter orthographic for view project cuts'): '自动进入正交模式以查看项目切割',
    ('*', '\n Parent cutters to the target'): '\n 父切割器到目标',
    ('*', 'Auto Hide Shapes'): '自动隐藏形状',
    ('*', '\n Hide previously made unselected cutters on cut'): '\n 隐藏先前制作的未选择的切割',
    ('*', 'Hold LMB + Drag to draw a shape'): '按住鼠标左键并拖动绘制形状',
    ('*', 'Begin with a modifier'): '选择初始修改器',
    ('*', '\n Start with the previously used settings of operation'): '\n 从先前使用的操作设置开始',
    ('*', 'D - Pie Menu'): 'D - 馅饼菜单',
    ('*', 'Ctrl + D - Behavior Helper'): 'Ctrl + D - 行为辅助',
    ('*', 'Hold Ctrl - Display Snapping Points'): '按住 Ctrl - 显示吸附点',
    ('*', 'LMB / Spacebar- Confirm'): 'LMB / 空格 - 确定',
    ('*', 'Shift + Confirm - Keep Shape'): 'Shift + 确定 - 保持形状',
    ('*', 'RMB / Esc - Cancel'): '右键 / Esc - 取消',
    ('*', 'LMB - Lock'): '左键 - 锁定',
    ('*', 'RMB - Cancel'): '右键 - 取消',
    ('*', 'LMB Release - Extrude'): '左键释放 - 扩展',
    ('*', 'RMB - Lock Shape'): '右键 - 锁定形状',
    ('*', 'LMB - Lock'): '左键 - 锁定',
    ('*', 'LMB - Place Point'): '左键 - 放置点',
    ('*', 'RMB / Backspace - Remove Point'): '右键 / 退格 - 删除点',
    ('*', 'C / Alt + Scroll - Cycle Cutters'): 'C / Alt + Scroll - 循环切片',
    ('*', 'CTRL - Angle Snapping'): 'CTRL - 角度吸附',
    ('*', 'C - Toggle Cyclic'): 'C - 开关循环',
    ('*', 'Tilde / R - Rotate 90 Fitted'): 'Tilde / R - 旋转90度',
    ('*', 'TAB - Lock Shape'): 'TAB - 锁定形状',
    ('*', 'L - Live Toggle'): 'L - 实时更新切换',
    ('*', 'E - Extrude'): 'E - 扩展',
    ('*', 'O - Offse'): 'O - 偏移',
    ('*', 'H - Toggle Wires Only'): 'H - 切换仅线框',
    ('*', 'X - Slice'): 'X - 切缝',
    ('*', 'X - Cut'): 'X - 剪切',
    ('*', 'Z - Inset'): 'Z - 内插',
    ('*', 'J - Join'): 'J - 接合',
    ('*', 'K - Knife'): 'K - 切刀',
    ('*', 'A - Make'): 'A - 构建',
    ('*', 'Y - Extract'): 'Y - 扩展',
    ('*', 'V - Array'): 'V - 阵列',
    ('*', 'V - Circle Array'): 'V - 圆形阵列',
    ('*', 'Scroll / - / + - Adjust Count'): '滚动 / - / + - 调整数量',
    ('*', 'T - Solidify'): 'T - 实体化',
    ('*', 'T - Clear Solidify'): 'T - 清除实体化',
    ('*', 'B - Bevel'): 'T - 倒角',
    ('*', 'B - Clear Bevel'): 'T - 清除倒角',
    ('*', 'Scroll / - / + - Adjust Segments'): '滚动 / - / + - 调整分段数',
    ('*', 'Q - Contour Bevel'): 'Q - 轮廓斜角',
    ('*', '. - Change origin (period)'): '. - 更改原点（临时）',
    ('*', '1, 2, 3 - Offset (-1, 0, 1)'): '1, 2, 3 - 偏移 (-1, 0, 1)',
    ('*', '1, 2, 3 - Mirror (X, Y, Z)'): '1, 2, 3 - 镜像 (X, Y, Z)',
    ('*', '\n Sort modifier order'): '\n 排序修改器顺序',
    ('*', 'Sort Bevel'): '排序倒角',
    ('*', '\n Choose what modifiers are applied on the shape'): '\n 选择哪些修改器应用在形状上'
}