# -*- coding: utf-8 -*-

lang_dict = {
   ('*', 'Cutters') : '切刀',
   ('*', 'None') : '無',
   ('*', 'Interaction') : '交互',
   ('*', 'Array') : '陣列',
   ('*', 'Axis') : '軸',
   ('*', 'Behavior') : '行為',
   ('*', 'Solidify') : '實體化',
   ('*', 'Bevel') : '倒角',
   ('*', 'Mirror') : '鏡像',
   ('*', 'Collection') : '集合',
   ('*', 'Color') : '顏色',
   ('*', 'Display') : '顯示',
   ('*', 'Shape') : '形狀',
   ('*', 'Keymap') : '鍵位映射',
   ('*', 'Settings') : '偏好設置',
   ('*', 'Ngon') : '多邊形',
   ('*', 'Circle') : '圓形',
   ('*', 'Box') : '圓形',
   ('*', 'Cut') : '剪切',
   ('*', 'Slice') : '切縫',
   ('*', 'Snap') : '吸附',
   ('Operator', 'Snap') : '吸附',
   ('*', 'Inset') : '內插',
   ('*', 'Join') : '接合',
   ('*', 'Make') : '構建',
   ('*', 'Knife') : '切刀',
   ('*', 'Extract') : '擠出',
   ('*', 'Negative') : '負',
   ('*', 'Snap Point') : '吸附到點',
   ('*', 'Snap point') : '吸附到點',
   ('*', 'Snap Edges') : '吸附到線',
   ('*', 'Snap Faces') : '吸附到面',
   ('*', 'Snap Grid') : '吸附到網格',
   ('*', 'Highlight') : '高亮',
   ('*', 'Offset') : '偏移',
   ('*', 'Dot') : '點',
   ('*', 'Wire') : '線',
   ('*', 'Grid') : '網格',
   ('*', 'Live') : '實時',
   ('*', 'Auto Hide') : '自動隱藏',
   ('*', 'Active only') : '僅激活',
   ('*', 'Quick Execute') : '快速執行',
   ('*', 'Auto Ortho') : '自動正交模式',
   ('*', 'Grid Mode Color') : '網格模式顏色',
   ('*', 'Grid Wire') : '網格線',
   ('*', 'Show Shape') : '顯示形狀',
   ('*', 'Show Shape Wire') : '顯示形狀線',
   ('*', 'Wire Width') : '線寬',
   ('*', 'Show Bounds') : '顯示界限',
   ('*', 'Allow Selection') : '可選中',
   ('*', 'Auto Smooth') : '自動平滑',
   ('*', 'Sort Modifiers') : '排序修改器',
   ('*', 'Keep Modifiers') : '保持修改器',
   ('*', 'Ngon Snap Angle') : 'Ngon 吸附角',
   ('*', 'Bevel Dot') : '倒角點',
   ('*', 'Dot Highlight') : '點高亮',
   ('*', 'Simple Topbar') : '簡單頂部欄',
   ('*', 'Topbar') : '頂部欄',
   ('*', 'Destructive Menu') : '破壞性菜單',
   ('*', 'Mode Label') : '模式標籤',
   ('*', 'Shape Label') : '形狀標籤',
   ('*', 'Operation Label') : '操作標籤',
   ('*', 'Surface Label') : '表（曲）面標籤',
   ('*', 'Fix Label Size') : '修正標籤尺寸',
   ('*', 'Topbar Padding') : '頂部欄填充',
   ('*', 'Pad Menus') : '便箋菜單',
   ('*', 'Middle Padding') : '中間填充',
   ('*', 'Fade Timing') : '漸隱時間',
   ('*', 'Settings to display') : '顯示的設置',
   ('*', 'Use default behavior') : '使用默認行為',
   ('*', 'Modal Shortcut: X') : '模式快捷鍵：X',
   ('*', 'Modal Shortcut: Y') : '模式快捷鍵：Y',
   ('*', 'Modal Shortcut: Z') : '模式快捷鍵：Z',
   ('*', 'Start Operation') : '開始動作',
   ('*', 'Non-Destructive') : '非破壞性',
   ('*', 'Circle Vertices') : '圓點數',
   ('*', 'Inset Thickness') : '內插厚度',
   ('*', 'Array Count') : '陣列數',
   ('*', 'Solidify Thickness') : '實體化厚度',
   ('*', 'Bevel Width') : '倒角寬度',
   ('*', 'Lazorcut Limit') : '切割限制',
   ('*', 'Bevel Segments') : '倒角段數',
   ('*', 'Quad Bevel') : '四倍倒角',
   ('*', 'Straight Corner Flow') : '直角流',
   ('*', 'Destructive') : '破壞性',
   ('*', 'Apply Boolean') : '應用布爾',
   ('*', 'Apply Slices') : '應用切片',
   ('*', 'Shift to Active') : '切換到激活',
   ('*', 'Simple Trace') : '簡單跟蹤',
   ('*', 'Use DPI Factoring') : '使用 DPI 因子',
   ('*', 'Join Flip Z') : '接合翻轉 Z',
   ('*', 'Parent Shape') : '父級形狀',
   ('*', 'Accucut Lazorcut') : '精確切割',
   ('*', 'Reduce Opacity in Edit') : '編輯時減少不透明度',
   ('*', 'Wires Only') : '僅顯示線框',
   ('*', 'Thick Wire') : '細線',
   ('*', 'Wire Size Multiplier') : '線寬倍數',
   ('*', 'Snap Dot Size') : '吸附點尺寸',
   ('*', 'Snap Dot Detection Factor') : '吸附點檢測因子',
   ('*', 'Dot Size') : '點尺寸',
   ('*', 'Dot Detection Factor') : '點檢測因子',
   ('*', 'Activate BoxCutter') : '激活 BoxCutter',
   ('Operator', 'Activate BoxCutter') : '激活 BoxCutter',
   ('Operator', 'Apply Boolean ') : '應用布爾',
   ('*', 'Applies Boolean Modifiers') : '應用布爾修改器',
   ('*', 'Enable Surface Toggle') : '啟用平（曲）面切換',
   ('*', 'Enable Topbar') : '啟用頂部欄',
   ('*', 'Disable Ctrl & Shift LMB (Edit Mode)') : '編輯模式禁用 Ctrl & Shift LMB',
   ('*', 'Preserve Alt') : '保留 Alt',
   ('*', 'RMB Cancel Ngon') : '右鍵取消多邊形',
   ('*', 'Alt Center') : 'Alt 為中心',
   ('*', 'Shift Uniform') : 'Alt 正規化',
   ('*', 'Scroll Adjust Circle') : '滾動調整圓',
   ('*', '\n Default State (no modifier)') : '\n 默認狀態（無修改器）',
   ('*', '\n Starts drawing with Array active') : '\n 在陣列激活時開始繪圖',
   ('*', '\n Starts drawing with Solidify active') : '\n 在實體化激活時開始繪圖',
   ('*', '\n Starts drawing with Bevel active') : '\n 在倒角激活時開始繪圖',
   ('*', '\n Starts drawing with Mirror active') : '\n 在鏡像激活時開始繪圖',
   ('*', '\n Assign collection for shape objects') : '\n 分配形狀對象的集合',
   ('*', '\n Assign shape object') : '\n 分配形狀對象',
   ('*', 'Show grid gizmo') : '顯示網絡 gizmo',
   ('*', 'Show cursor gizmo') : '顯示3D光標 gizmo',
   ('*', 'Show transform gizmo') : '顯示變換 gizmo',
   ('*', 'Axis to be used') : '使用的軸',
   ('*', '\n Quickly execute cuts on release') : '\n 釋放時快速執行剪切',
   ('*', '\n Automatically enter orthographic for view project cuts') : '自動進入正交模式以查看項目切割',
   ('*', '\n Parent cutters to the target') : '\n 父切割器到目標',
   ('*', 'Auto Hide Shapes') : '自動隱藏形狀',
   ('*', '\n Hide previously made unselected cutters on cut') : '\n 隱藏先前製作的未選擇的切割',
   ('*', 'Hold LMB + Drag to draw a shape') : '按住鼠標左鍵並拖動繪製形狀',
   ('*', 'Begin with a modifier') : '選擇初始修改器',
   ('*', '\n Start with the previously used settings of operation') : '\n 從先前使用的操作設置開始',
   ('*', 'D - Pie Menu') : 'D - 餡餅菜單',
   ('*', 'Ctrl + D - Behavior Helper') : 'Ctrl + D - 行為輔助',
   ('*', 'Hold Ctrl - Display Snapping Points') : '按住 Ctrl - 顯示吸附點',
   ('*', 'LMB / Spacebar- Confirm') : 'LMB / 空格 - 確定',
   ('*', 'Shift + Confirm - Keep Shape') : 'Shift + 確定 - 保持形狀',
   ('*', 'RMB / Esc - Cancel') : '右鍵 / Esc - 取消',
   ('*', 'LMB - Lock') : '左鍵 - 鎖定',
   ('*', 'RMB - Cancel') : '右鍵 - 取消',
   ('*', 'LMB Release - Extrude') : '左鍵釋放 - 擴展',
   ('*', 'RMB - Lock Shape') : '右鍵 - 鎖定形狀',
   ('*', 'LMB - Place Point') : '左鍵 - 放置點',
   ('*', 'RMB / Backspace - Remove Point') : '右鍵 / 退格 - 刪除點',
   ('*', 'C / Alt + Scroll - Cycle Cutters') : 'C / Alt + Scroll - 循環切片',
   ('*', 'CTRL - Angle Snapping') : 'CTRL - 角度吸附',
   ('*', 'C - Toggle Cyclic') : 'C - 開關循環',
   ('*', 'Tilde / R - Rotate 90 Fitted') : 'Tilde / R - 旋轉90度',
   ('*', 'TAB - Lock Shape') : 'TAB - 鎖定形狀',
   ('*', 'L - Live Toggle') : 'L - 實時更新切換',
   ('*', 'E - Extrude') : 'E - 擴展',
   ('*', 'O - Offse') : 'O - 偏移',
   ('*', 'H - Toggle Wires Only') : 'H - 切換僅線框',
   ('*', 'X - Slice') : 'X - 切縫',
   ('*', 'X - Cut') : 'X - 剪切',
   ('*', 'Z - Inset') : 'Z - 內插',
   ('*', 'J - Join') : 'J - 接合',
   ('*', 'K - Knife') : 'K - 切刀',
   ('*', 'A - Make') : 'A - 構建',
   ('*', 'Y - Extract') : 'Y - 擴展',
   ('*', 'V - Array') : 'V - 陣列',
   ('*', 'V - Circle Array') : 'V - 圓形陣列',
   ('*', 'Scroll / - / + - Adjust Count') : '滾動 / - / + - 調整數量',
   ('*', 'T - Solidify') : 'T - 實體化',
   ('*', 'T - Clear Solidify') : 'T - 清除實體化',
   ('*', 'B - Bevel') : 'T - 倒角',
   ('*', 'B - Clear Bevel') : 'T - 清除倒角',
   ('*', 'Scroll / - / + - Adjust Segments') : '滾動 / - / + - 調整分段數',
   ('*', 'Q - Contour Bevel') : 'Q - 輪廓斜角',
   ('*', '. - Change origin (period)') : '. - 更改原點（臨時）',
   ('*', '1, 2, 3 - Offset (-1, 0, 1)') : '1, 2, 3 - 偏移 (-1, 0, 1)',
   ('*', '1, 2, 3 - Mirror (X, Y, Z)') : '1, 2, 3 - 鏡像 (X, Y, Z)',
   ('*', '\n Sort modifier order') : '\n 排序修改器順序',
   ('*', 'Sort Bevel') : '排序倒角',
   ('*', '\n Choose what modifiers are applied on the shape') : '\n 選擇哪些修改器應用在形狀上',
}