lang_dict = {
    ('*', 'Sapling Tree Gen'): '树苗生成器',
    ('*', 'Add Curve: Sapling Tree Gen'): '添加曲线：树苗生成器',
    ('*', 'View3D > Add > Curve'): '3D 视图 > 添加 > 曲线',
    ('*', ("Adds a parametric tree. The method is presented by "
    "Jason Weber & Joseph Penn in their paper 'Creation and Rendering of "
    "Realistic Trees'")): '添加参数化树。该方法由 Jason Weber 和 Joseph Penn 在他们的论文 "现实树的创造和渲染" 中提出',
    
    ('Operator', 'Sapling Tree Gen'): '树苗生成器',
    ('Operator', 'Sapling: Add Tree'): '树苗：添加树',
    ('*', 'Geometry:'): '几何：',
    ('*', 'Curve Resolution'): '曲线分辨率',
    ('*', 'Conical'): '锥形',
    ('*', 'Inverse Conical'): '反向锥形',
    ('*', 'Spherical'): '球形',
    ('*', 'Hemispherical'): '半球',
    ('*', 'Cylindrical'): '圆柱',
    ('*', 'Tapered Cylindrical'): '锥圆柱',
    ('*', 'Inverse Tapered Cylindrical'): '反向锥圆柱',
    ('*', 'Flame'): '火焰',
    ('*', 'Tend Flame'): '滕德火焰',
    ('*', 'Custom Shape'): '自定义形状',
    ('*', 'Secondary Branches Shape'): '次分支形状',
    ('*', 'Branch Distribution'): '分支分布',
    ('*', 'Branch Rings'): '分支环',
    ('*', 'Tree Scale:'): '树缩放：',
    ('*', 'Scale Variation'): '比例变量',
    ('Operator', 'Export Preset'): '导出预设',
    ('*', 'Load Preset'): '加载预设',
    ('*', 'Limit Import'): '有限导入',

    ('*', 'Branch Radius'): '分支半径',
    ('*', 'Branch Radius:'): '分支半径：',
    ('*', 'Radius Scale Variation'): '分支缩放变量',
    ('*', 'Branch Radius Ratio'): '分支半径比率',
    ('*', 'Minimum Radius'): '最小半径',
    ('*', 'Root Flare'): '根径',
    ('*', 'Auto Taper'): '自动锥度',
    ('*', 'Tweak Radius'): '调整半径',

    ('*', 'Branch Splitting'): '分支拆分',
    ('*', 'Branch Splitting:'): '分支拆分：',
    ('*', 'Base Splits'): '基本拆分',
    ('*', 'Trunk Height'): '树干高度',
    ('*', 'Secondary Base Size'): '次基尺寸',
    ('*', 'Split Height'): '分割高度',
    ('*', 'splitBias'): '拆分偏置',
    ('*', 'Split relative to length'): '相对于长度的拆分',
    ('*', 'Branches'): '分支',
    ('*', 'Segment Splits'): '分段',
    ('*', 'Split Angle Variation'): '切分角变量',
    ('*', 'Rotate Angle'): '旋转角',
    ('*', 'Rotate Angle Variation'): '旋转角变量',
    ('*', 'Outward Attraction'): '向外引力',
    ('*', 'Branching Mode:'): '分支模式：',

    ('*', 'Branch Growth'): '分支成长',
    ('*', 'Branch Growth:'): '分支成长：',
    ('*', 'Taper Crown'): '锥形封顶',
    ('*', 'Length Variation'): '长度变量',
    ('*', 'Down Angle'): '向下角度',
    ('*', 'Down Angle Variation'): '向下角度变量',
    ('*', 'Curvature'): '曲率',
    ('*', 'Curvature Variation'): '曲率变量',
    ('*', 'Back Curvature'): '后曲率',
    ('*', 'Vertical Attraction'): '垂直引力',
    ('*', 'Use old down angle variation'): '使用旧的向下角度变化',
    ('*', 'Use parent angle'): '使用父角度',

    ('*', 'Pruning'): '修剪',
    ('*', 'Prune:'): '修剪：',
    ('*', 'Prune'): '修剪',
    ('*', 'Prune Ratio'): '修剪半径',
    ('*', 'Prune Width'): '修剪宽度',
    ('*', 'Prune Base Height'): '修剪基高度',
    ('*', 'Prune Width Peak'): '修剪宽度峰值',
    ('*', 'Prune Power High'): '修剪高强度',
    ('*', 'Prune Power Low'): '修剪低强度',

    ('*', 'Leaves'): '叶',
    ('*', 'Leaves:'): '叶：',
    ('*', 'Show Leaves'): '显示叶',
    ('*', 'Leaf Shape'): '叶形',
    ('*', 'Rectangular'): '矩形',
    ('*', 'DupliFaces'): '复制面',
    ('*', 'DupliVerts'): '复制点',
    ('*', 'Leaf Object'): '叶对象',
    ('*', 'No objects'): '无对象',
    ('*', 'Leaf Distribution'): '叶分布',
    ('*', 'Leaf Down Angle'): '叶下角',
    ('*', 'Leaf Down Angle Variation'): '叶下角变量',
    ('*', 'Leaf Rotate Angle'): '叶旋转角',
    ('*', 'Leaf Rotate Angle Variation'): '叶旋转角变量',
    ('*', 'Leaf Scale'): '叶缩放',
    ('*', 'Leaf Scale X'): '叶 X 缩放',
    ('*', 'Leaf Scale Taper'): '叶缩放锥',
    ('*', 'Leaf Scale Variation'): '叶缩放变量',
    ('*', 'Horizontal leaves'): '横向叶面',
    ('*', 'Leaf Angle'): '叶角',

    ('*', 'Use Armature'): '使用骨架',
    ('*', 'Make Mesh'): '生成网格',
    ('*', 'Make Mesh'): '生成网格',
    ('*', 'Armature Simplification:'): '骨架简化：',
    ('*', 'Armature Levels'): '骨架级别',
    ('*', 'Bone Length'): '骨骼长度',

    ('*', 'Finalize All Other Settings First!'): '首先完成所有其他设置！',
    ('*', 'Armature Animation'): '骨骼动画',
    ('*', 'Leaf Animation'): '叶动画',
    ('*', 'Fast Preview'): '快速预览',
    ('*', 'Animation Speed'): '动画速度',
    ('*', 'Loop Frames'): '循环帧',
    ('*', 'Wind Settings:'): '风设置：',
    ('*', 'Overall Wind Strength'): '整体风力强度',
    ('*', 'Wind Gust Strength'): '阵风强度',
    ('*', 'Wind Gust Fequency'): '阵风频率',
    ('*', 'Leaf Wind Settings:'): '叶风设置：',
}