# -*- coding: utf-8 -*-

lang_dict = {
   ('*', 'Sapling Tree Gen') : '樹苗生成器',
   ('*', 'Add Curve: Sapling Tree Gen') : '添加曲線：樹苗生成器',
   ('*', 'View3D > Add > Curve') : '3D 視圖 > 添加 > 曲線',
   ('*', "Adds a parametric tree. The method is presented by Jason Weber & Joseph Penn in their paper 'Creation and Rendering of Realistic Trees'") : '添加參數化樹。該方法由 Jason Weber 和 Joseph Penn 在他們的論文 "現實樹的創造和渲染" 中提出',
   ('Operator', 'Sapling Tree Gen') : '樹苗生成器',
   ('Operator', 'Sapling: Add Tree') : '樹苗：添加樹',
   ('*', 'Geometry:') : '幾何：',
   ('*', 'Curve Resolution') : '曲線分辨率',
   ('*', 'Conical') : '錐形',
   ('*', 'Inverse Conical') : '反向錐形',
   ('*', 'Spherical') : '球形',
   ('*', 'Hemispherical') : '半球',
   ('*', 'Cylindrical') : '圓柱',
   ('*', 'Tapered Cylindrical') : '錐圓柱',
   ('*', 'Inverse Tapered Cylindrical') : '反向錐圓柱',
   ('*', 'Flame') : '火焰',
   ('*', 'Tend Flame') : '滕德火焰',
   ('*', 'Custom Shape') : '自定義形狀',
   ('*', 'Secondary Branches Shape') : '次分支形狀',
   ('*', 'Branch Distribution') : '分支分佈',
   ('*', 'Branch Rings') : '分支環',
   ('*', 'Tree Scale:') : '樹縮放：',
   ('*', 'Scale Variation') : '比例變量',
   ('Operator', 'Export Preset') : '導出預設',
   ('*', 'Load Preset') : '加載預設',
   ('*', 'Limit Import') : '有限導入',
   ('*', 'Branch Radius') : '分支半徑',
   ('*', 'Branch Radius:') : '分支半徑：',
   ('*', 'Radius Scale Variation') : '分支縮放變量',
   ('*', 'Branch Radius Ratio') : '分支半徑比率',
   ('*', 'Minimum Radius') : '最小半徑',
   ('*', 'Root Flare') : '根徑',
   ('*', 'Auto Taper') : '自動錐度',
   ('*', 'Tweak Radius') : '調整半徑',
   ('*', 'Branch Splitting') : '分支拆分',
   ('*', 'Branch Splitting:') : '分支拆分：',
   ('*', 'Base Splits') : '基本拆分',
   ('*', 'Trunk Height') : '樹幹高度',
   ('*', 'Secondary Base Size') : '次基尺寸',
   ('*', 'Split Height') : '分割高度',
   ('*', 'splitBias') : '拆分偏置',
   ('*', 'Split relative to length') : '相對於長度的拆分',
   ('*', 'Branches') : '分支',
   ('*', 'Segment Splits') : '分段',
   ('*', 'Split Angle Variation') : '切分角變量',
   ('*', 'Rotate Angle') : '旋轉角',
   ('*', 'Rotate Angle Variation') : '旋轉角變量',
   ('*', 'Outward Attraction') : '向外引力',
   ('*', 'Branching Mode:') : '分支模式：',
   ('*', 'Branch Growth') : '分支成長',
   ('*', 'Branch Growth:') : '分支成長：',
   ('*', 'Taper Crown') : '錐形封頂',
   ('*', 'Length Variation') : '長度變量',
   ('*', 'Down Angle') : '向下角度',
   ('*', 'Down Angle Variation') : '向下角度變量',
   ('*', 'Curvature') : '曲率',
   ('*', 'Curvature Variation') : '曲率變量',
   ('*', 'Back Curvature') : '後曲率',
   ('*', 'Vertical Attraction') : '垂直引力',
   ('*', 'Use old down angle variation') : '使用舊的向下角度變化',
   ('*', 'Use parent angle') : '使用父角度',
   ('*', 'Pruning') : '修剪',
   ('*', 'Prune:') : '修剪：',
   ('*', 'Prune') : '修剪',
   ('*', 'Prune Ratio') : '修剪半徑',
   ('*', 'Prune Width') : '修剪寬度',
   ('*', 'Prune Base Height') : '修剪基高度',
   ('*', 'Prune Width Peak') : '修剪寬度峰值',
   ('*', 'Prune Power High') : '修剪高強度',
   ('*', 'Prune Power Low') : '修剪低強度',
   ('*', 'Leaves') : '葉',
   ('*', 'Leaves:') : '葉：',
   ('*', 'Show Leaves') : '顯示葉',
   ('*', 'Leaf Shape') : '葉形',
   ('*', 'Rectangular') : '矩形',
   ('*', 'DupliFaces') : '複製面',
   ('*', 'DupliVerts') : '複製點',
   ('*', 'Leaf Object') : '葉對象',
   ('*', 'No objects') : '無對象',
   ('*', 'Leaf Distribution') : '葉分佈',
   ('*', 'Leaf Down Angle') : '葉下角',
   ('*', 'Leaf Down Angle Variation') : '葉下角變量',
   ('*', 'Leaf Rotate Angle') : '葉旋轉角',
   ('*', 'Leaf Rotate Angle Variation') : '葉旋轉角變量',
   ('*', 'Leaf Scale') : '葉縮放',
   ('*', 'Leaf Scale X') : '葉 X 縮放',
   ('*', 'Leaf Scale Taper') : '葉縮放錐',
   ('*', 'Leaf Scale Variation') : '葉縮放變量',
   ('*', 'Horizontal leaves') : '橫向葉面',
   ('*', 'Leaf Angle') : '葉角',
   ('*', 'Use Armature') : '使用骨架',
   ('*', 'Make Mesh') : '生成網格',
   ('*', 'Armature Simplification:') : '骨架簡化：',
   ('*', 'Armature Levels') : '骨架級別',
   ('*', 'Bone Length') : '骨骼長度',
   ('*', 'Finalize All Other Settings First!') : '首先完成所有其他設置！',
   ('*', 'Armature Animation') : '骨骼動畫',
   ('*', 'Leaf Animation') : '葉動畫',
   ('*', 'Fast Preview') : '快速預覽',
   ('*', 'Animation Speed') : '動畫速度',
   ('*', 'Loop Frames') : '循環幀',
   ('*', 'Wind Settings:') : '風設置：',
   ('*', 'Overall Wind Strength') : '整體風力強度',
   ('*', 'Wind Gust Strength') : '陣風強度',
   ('*', 'Wind Gust Fequency') : '陣風頻率',
   ('*', 'Leaf Wind Settings:') : '葉風設置：',
}