lang_dict = {
    ('*', '3D Navigation') : '3D 导航',
    ('*', '3D View: 3D Navigation') : '3D 视图： 3D 导航',
    ('*', 'Navigate the Camera & 3D View from the Toolshelf') : '从工具架导航相机和 3D 视图',
    ('*', 'View3D > Sidebar > View Tab'): '3D 视图 > 边栏 > 视图 选项卡',
    ('*', 'Tab Category:'): '选项卡类别：',
    ('*', '3D Nav'): '3D 导航',
    ('Operator', 'View Global / Local'): '全局 / 局部',
    ('Operator', 'View Persp / Ortho'): '透视 / 正交',
    ('*', 'Align view from:'): '转到视角：',
    ('*', 'Lock View to Object:'): '锁定到对象：',
    ('Operator', 'View to Selected'): '查看选中对象',
    ('*', 'Cursor:'): '游标：',
    ('Operator', 'World Origin'): '世界原点',
    ('Operator', 'View'): '查看',
    ('*', 'Pan Orbit Zoom Roll'): '相机轨道',
    ('*', 'Screen View Perspective'): '屏幕视图透视',
    ('*', 'Pan:'): '平移：',
    ('Operator', 'Up'): '上',
    ('Operator', 'Down'): '下',
    ('*', 'Orbit:'): '环绕：',
    ('*', 'Zoom:'): '缩放：',
    ('Operator', 'In'): '进',
    ('Operator', 'Out'): '出',
    ('*', 'Roll:'): '翻滚：',
}