lang_dict = {
    ('*', 'Edit Mesh Tools'): '编辑网格工具',
    ('*', 'Mesh: Edit Mesh Tools'): '网格：编辑网格工具',
    ('*', 'Mesh modelling toolkit. Several tools to aid modelling'): '网格建模工具包。提供几种建模辅助工具',
    ('*', 'View3D > Sidebar > Edit Tab / Edit Mode Context Menu'): '3D 视图 > 边栏 > 编辑选项卡 / 编辑模式上下文菜单',
    ('*', 'Mesh Tools'): '网格工具',
    ('*', 'Vert tools'): '点工具',
    ('*', 'Vert Tools'): '点工具',
    ('*', 'Edge Tools'): '线工具',
    ('*', 'Face Tools'): '面工具',
    ('*', 'Utility Tools'): '实用工具',
    ('Operator', 'Vertex Select Mode'): '点选择',
    ('Operator', 'Vert & Edge Select'): '点和边选择',
    ('Operator', 'Vert & Face Select'): '点和面选择',
    ('Operator', 'Edge Select Mode'): '边选择',
    ('Operator', 'Edge & Vert Select'): '边和点选择',
    ('Operator', 'Edge & Face Select'): '边和面选择',
    ('Operator', 'Face Select Mode'): '面选择',
    ('Operator', 'Face & Vert Select'): '面和点选择',
    ('Operator', 'Face & Edge Select'): '面和边选择',
    ('Operator', 'All Select Modes'): '全部选择模式',
    ('Operator', 'Vertex Chamfer'): '顶点倒角',
    ('Operator', 'Chamfer Vertex'): '顶点倒角',
    ('Operator', 'Random Vertices'): '随机顶点',
    ('*', 'Min XYZ'): '最小 XYZ',
    ('*', 'Max XYZ'): '最大 XYZ',
    ('*', 'Miter Outer'): '外斜角',
    ('*', 'Intersection Type'): '交点类型',
    ('*', 'Profile Type'): '配置类型',
    ('*', 'Superellipse'): '超级椭圆',
    ('Operator', 'Offset Edges'): '偏移边',
    ('Operator', 'Fillet Edges'): '圆角边',
    ('Operator', 'Edge Roundify'): '边圆化',
    ('Operator', 'Edge Roundifier'): '边圆化',
    ('*', 'Plane:'): '平面：',
    ('*', 'Reference:'): '参考：',
    ('*', 'Scale base:'): '缩放基于：',
    ('*', 'Scale factor:'): '缩放因子：',
    ('*', 'Entry mode:'): '进入模式：',
    ('*', 'Angle:'): '角度：',
    ('*', 'Segments:'): '分段：',
    ('Operator', 'Both sides'): '双面',
    ('*', 'Both sides'): '双面',
    ('*', 'Remove:'): '移除：',
    ('Operator', 'Scaled edges'): '缩放边',
    ('*', 'Scaled edges'): '缩放边',
    ('*', 'Connect:'): '连接：',
    ('*', 'Arcs'): '弧',
    ('*', 'Flip Arcs'): '翻转弧',
    ('*', 'Arc - Edge'): '弧 - 边',
    ('*', 'Flip Arc - Edge'): '翻转弧 - 边',
    ('*', 'Scaled - Base Edge'): '缩放 - 基边',
    ('*', 'Orhto offset:'): '奥赫托偏移：',
    ('*', 'Parallel offset:'): '平行偏移：',
    ('*', 'Edge rotate:'): '边旋转：',
    ('*', 'Axis rotate center:'): '轴旋转原点：',
    ('*', 'Axis rotate:'): '轴旋转：',
    ('*', 'Elliptic factor:'): '椭圆因子：',
    ('Operator', 'Set Edge Length'): '设置边长度',
    ('*', 'Set edge length'): '设置边长度',
    ('*', 'Existing Length'): '现有长度',
    ('*', 'Target Length'): '目标长度',
    ('*', 'Resize Behavior:'): '调整大小行为：',
    ('*', 'Proportional'): '比例',
    ('*', 'Counterclockwise'): '逆时针',
    ('*', 'Decrement'): '递减',
    ('*', 'Shortest'): '最短',
    ('Operator', 'Edges Floor Plan'): '边平面图',
    ('*', 'Choose Method:'): '选择方式：',
    ('*', 'Edge Net'): '边网',
    ('*', 'Single Face'): '独立面',
    ('*', 'Recursive Prepare'): '递归准备',
    ('*', 'Remove Ngons'): '删除 Ngons',
    ('*', 'Wall width:'): '墙宽：',
    ('*', 'Inner height:'): '内高：',
    ('*', 'Connect Ends'): '连接终点',
    ('*', 'Keep Faces'): '保持面',
    ('*', 'Keep faces'): '保持面',
    ('*', 'Wall Offset:'): '墙偏移：',
    ('*', 'Rim Only'): '仅边缘',
    ('*', 'Initial Extrude'): '初始拉伸',
    ('Operator', 'Face Inset Fillet'): '面内插圆角',
    ('*', 'Corner Type:'): '倒角类型:',
    ('*', 'Inset amount'): '内插量',
    ('*', 'Number of sides'): '内插量',
    ('Operator', 'Cut Faces'): '切割面',
    ('Operator', 'Multi Extrude'): '多拉伸',
    ('*', 'Transformations:'): '变换：',
    ('*', 'Variation settings:'): '变量设置：',
    ('*', 'Offset Var'): '偏移变量：',
    ('*', 'Rotation Var'): '旋转变量：',
    ('*', 'Scale Noise'): '缩放噪音',
    ('*', 'Probability'): '概率',
    ('*', 'Polygon coordinates'): '多边形坐标',
    ('*', 'Proportional offset'): '比例偏移',
    ('*', 'Per step rotation noise'): '每步旋转噪音',
    ('*', 'Per step scale noise'): '每步缩放噪音',
    ('Operator', 'Split Solidify'): '分割实体',
    ('*', 'Normal:'): '法向：',
    ('*', 'Thickness:'): '厚度：',
    ('*', 'Delete original faces'): '删除原有面',
    ('*', 'Random distance:'): '随机距离：',
    ('Operator', 'Face Shape'): '面形状',
    ('*', 'Using Active Object'): '使用活动对象',
    ('*', 'Custom Normals Only'): '仅自定义法线',
    ('*', 'Relax iterations'): '松弛迭代',
}