# -*- coding: utf-8 -*-

lang_dict = {
   ('*', 'Edit Mesh Tools') : '編輯網格工具',
   ('*', 'Mesh: Edit Mesh Tools') : '網格：編輯網格工具',
   ('*', 'Mesh modelling toolkit. Several tools to aid modelling') : '網格建模工具包。提供幾種建模輔助工具',
   ('*', 'View3D > Sidebar > Edit Tab / Edit Mode Context Menu') : '3D 視圖 > 邊欄 > 編輯選項卡 / 編輯模式上下文菜單',
   ('*', 'Mesh Tools') : '網格工具',
   ('*', 'Vert tools') : '點工具',
   ('*', 'Vert Tools') : '點工具',
   ('*', 'Edge Tools') : '線工具',
   ('*', 'Face Tools') : '面工具',
   ('*', 'Utility Tools') : '實用工具',
   ('Operator', 'Vertex Select Mode') : '點選擇',
   ('Operator', 'Vert & Edge Select') : '點和邊選擇',
   ('Operator', 'Vert & Face Select') : '點和麵選擇',
   ('Operator', 'Edge Select Mode') : '邊選擇',
   ('Operator', 'Edge & Vert Select') : '邊和點選擇',
   ('Operator', 'Edge & Face Select') : '邊和麵選擇',
   ('Operator', 'Face Select Mode') : '面選擇',
   ('Operator', 'Face & Vert Select') : '面和點選擇',
   ('Operator', 'Face & Edge Select') : '面和邊選擇',
   ('Operator', 'All Select Modes') : '全部選擇模式',
   ('Operator', 'Vertex Chamfer') : '頂點倒角',
   ('Operator', 'Chamfer Vertex') : '頂點倒角',
   ('Operator', 'Random Vertices') : '隨機頂點',
   ('*', 'Min XYZ') : '最小 XYZ',
   ('*', 'Max XYZ') : '最大 XYZ',
   ('*', 'Miter Outer') : '外斜角',
   ('*', 'Intersection Type') : '交點類型',
   ('*', 'Profile Type') : '配置類型',
   ('*', 'Superellipse') : '超級橢圓',
   ('Operator', 'Offset Edges') : '偏移邊',
   ('Operator', 'Fillet Edges') : '圓角邊',
   ('Operator', 'Edge Roundify') : '邊圓化',
   ('Operator', 'Edge Roundifier') : '邊圓化',
   ('*', 'Plane:') : '平面：',
   ('*', 'Reference:') : '參考：',
   ('*', 'Scale base:') : '縮放基於：',
   ('*', 'Scale factor:') : '縮放因子：',
   ('*', 'Entry mode:') : '進入模式：',
   ('*', 'Angle:') : '角度：',
   ('*', 'Segments:') : '分段：',
   ('Operator', 'Both sides') : '雙面',
   ('*', 'Both sides') : '雙面',
   ('*', 'Remove:') : '移除：',
   ('Operator', 'Scaled edges') : '縮放邊',
   ('*', 'Scaled edges') : '縮放邊',
   ('*', 'Connect:') : '連接：',
   ('*', 'Arcs') : '弧',
   ('*', 'Flip Arcs') : '翻轉弧',
   ('*', 'Arc - Edge') : '弧 - 邊',
   ('*', 'Flip Arc - Edge') : '翻轉弧 - 邊',
   ('*', 'Scaled - Base Edge') : '縮放 - 基邊',
   ('*', 'Orhto offset:') : '奧赫託偏移：',
   ('*', 'Parallel offset:') : '平行偏移：',
   ('*', 'Edge rotate:') : '邊旋轉：',
   ('*', 'Axis rotate center:') : '軸旋轉原點：',
   ('*', 'Axis rotate:') : '軸旋轉：',
   ('*', 'Elliptic factor:') : '橢圓因子：',
   ('Operator', 'Set Edge Length') : '設置邊長度',
   ('*', 'Set edge length') : '設置邊長度',
   ('*', 'Existing Length') : '現有長度',
   ('*', 'Target Length') : '目標長度',
   ('*', 'Resize Behavior:') : '調整大小行為：',
   ('*', 'Proportional') : '比例',
   ('*', 'Counterclockwise') : '逆時針',
   ('*', 'Decrement') : '遞減',
   ('*', 'Shortest') : '最短',
   ('Operator', 'Edges Floor Plan') : '邊平面圖',
   ('*', 'Choose Method:') : '選擇方式：',
   ('*', 'Edge Net') : '邊網',
   ('*', 'Single Face') : '獨立面',
   ('*', 'Recursive Prepare') : '遞歸準備',
   ('*', 'Remove Ngons') : '刪除 Ngons',
   ('*', 'Wall width:') : '牆寬：',
   ('*', 'Inner height:') : '內高：',
   ('*', 'Connect Ends') : '連接終點',
   ('*', 'Keep Faces') : '保持面',
   ('*', 'Keep faces') : '保持面',
   ('*', 'Wall Offset:') : '牆偏移：',
   ('*', 'Rim Only') : '僅邊緣',
   ('*', 'Initial Extrude') : '初始拉伸',
   ('Operator', 'Face Inset Fillet') : '面內插圓角',
   ('*', 'Corner Type:') : '倒角類型:',
   ('*', 'Inset amount') : '內插量',
   ('*', 'Number of sides') : '內插量',
   ('Operator', 'Cut Faces') : '切割面',
   ('Operator', 'Multi Extrude') : '多拉伸',
   ('*', 'Transformations:') : '變換：',
   ('*', 'Variation settings:') : '變量設置：',
   ('*', 'Offset Var') : '偏移變量：',
   ('*', 'Rotation Var') : '旋轉變量：',
   ('*', 'Scale Noise') : '縮放噪音',
   ('*', 'Probability') : '概率',
   ('*', 'Polygon coordinates') : '多邊形座標',
   ('*', 'Proportional offset') : '比例偏移',
   ('*', 'Per step rotation noise') : '每步旋轉噪音',
   ('*', 'Per step scale noise') : '每步縮放噪音',
   ('Operator', 'Split Solidify') : '分割實體',
   ('*', 'Normal:') : '法向：',
   ('*', 'Thickness:') : '厚度：',
   ('*', 'Delete original faces') : '刪除原有面',
   ('*', 'Random distance:') : '隨機距離：',
   ('Operator', 'Face Shape') : '面形狀',
   ('*', 'Using Active Object') : '使用活動對象',
   ('*', 'Custom Normals Only') : '僅自定義法線',
   ('*', 'Relax iterations') : '鬆弛迭代',
}