lang_dict = {
    ('*', 'Curve Tools'): '曲线工具',
    ('*', 'Add Curve: Curve Tools'): '添加曲线：曲线工具',
    ('*', 'Adds some functionality for bezier/nurbs curve/surface modeling'): '为贝塞尔/NURBS 曲线/曲面建模添加一些功能',
    ('*', 'View3D > Tool Shelf > Edit Tab'): '3D 视图 > 边栏 > 编辑选项卡',
    
    ('*', 'Curve Info'): '曲线信息',
    ('Operator', 'Segment'): '分段',
    
    ('*', 'Curve Edit'): '曲线编辑',
    ('Operator', 'Fillet/Chamfer'): '圆角/倒角',
    ('Operator', 'Outline'): '轮廓',
    ('Operator', 'Recursive Offset'): '递归偏移',
    ('Operator', 'Separate Offset/Selected'): '分离偏移/选定',
    ('Operator', 'Extend Handles'): '扩展手柄',
    ('Operator', 'Boolean Splines'): '布尔样条线',
    ('Operator', 'Multi Subdivide'): '多次细分',
    ('Operator', 'Split at Vertex'): '在顶点拆分',
    ('Operator', 'Discretize Curve'): '分离曲线',
    ('Operator', 'Array Splines'): '阵列样条线',
    ('Operator', '2D Curve Boolean'): '2D 曲线布尔',
    ('Operator', 'Intersect Curves'): '相交曲线',
    ('Operator', 'Birail'): '比拉尔',
    ('Operator', 'Convert Bezier to Surface'): '转换贝塞尔到曲面',
    ('Operator', 'Convert Faces to Bezier'): '转换面到贝塞尔',
    ('*', 'Loft'): '放样',
    ('*', 'Auto Loft'): '自动放样',
    ('Operator', 'Update Auto Loft'): '更新自动放样',
    ('*', 'Sanitize'): '清理',
    ('Operator', 'Set Origin to Spline Start'): '设置原点到曲线起点',
    ('Operator', 'Reset Scale'): '重置缩放',
    ('*', 'Cleanup:'): '清理：',
    ('Operator', '0-Segment Splines'): '零分段样条线',
    ('Operator', 'Short Splines'): '短样条线',
    ('*', 'Threshold remove'): '阈值删除',
    ('*', 'Join Splines:'): '连接样条线：',
    ('Operator', 'Join Neighbouring Splines'): '连接相邻样条线',
    ('*', 'Only at Ends'): '仅在结束点',
    ('*', 'Join Position'): '连接点',
    ('*', 'At midpoint'): '在中点',
    ('*', 'Insert segment'): '插入段',
    ('*', 'Utilities'): '实用工具',
    ('*', 'Curve Resolution:'): '曲线分辨率：',
    ('Operator', 'Show [ESC]'): '显示 [ESC]',
    ('Operator', 'Set Resolution'): '设置分辨率',
    ('*', 'Spline Order:'): '样条顺序：',
    ('*', 'Font Thickness'): '字体厚度',
    ('Operator', 'Set First Points'): '设置起始点',
    ('*', 'Path Finder'): '路径查找器',
    ('Operator', 'Path Finder [ESC]'): '路径查找器 [ESC]',
    ('*', 'PathFinder Radius'): '路径查找器半径',
    ('*', 'ESC or TAB - Exit PathFinder'): 'ESC 或 TAB - 退出路径查找器',
    ('*', 'X or DEL - Delete'): 'X 或 DEL - 删除',
    ('*', 'Alt + Mouse Click - Select Spline'): 'Alt + 点击 - 选择样条线',
    ('*', 'Alt + Shift + Mouse click - Add Spline to Selection'): 'Alt + Shift + 点击 - 添加样条线到选集',
    ('*', 'A - Deselect All'): 'A - 取消选择全部',
}