# -*- coding: utf-8 -*-

lang_dict = {
   ('*', 'Curve Tools') : '曲線工具',
   ('*', 'Add Curve: Curve Tools') : '添加曲線：曲線工具',
   ('*', 'Adds some functionality for bezier/nurbs curve/surface modeling') : '為貝塞爾/NURBS 曲線/曲面建模添加一些功能',
   ('*', 'View3D > Tool Shelf > Edit Tab') : '3D 視圖 > 邊欄 > 編輯選項卡',
   ('*', 'Curve Info') : '曲線信息',
   ('Operator', 'Segment') : '分段',
   ('*', 'Curve Edit') : '曲線編輯',
   ('Operator', 'Fillet/Chamfer') : '圓角/倒角',
   ('Operator', 'Outline') : '輪廓',
   ('Operator', 'Recursive Offset') : '遞歸偏移',
   ('Operator', 'Separate Offset/Selected') : '分離偏移/選定',
   ('Operator', 'Extend Handles') : '擴展手柄',
   ('Operator', 'Boolean Splines') : '布爾樣條線',
   ('Operator', 'Multi Subdivide') : '多次細分',
   ('Operator', 'Split at Vertex') : '在頂點拆分',
   ('Operator', 'Discretize Curve') : '分離曲線',
   ('Operator', 'Array Splines') : '陣列樣條線',
   ('Operator', '2D Curve Boolean') : '2D 曲線布爾',
   ('Operator', 'Intersect Curves') : '相交曲線',
   ('Operator', 'Birail') : '比拉爾',
   ('Operator', 'Convert Bezier to Surface') : '轉換貝塞爾到曲面',
   ('Operator', 'Convert Faces to Bezier') : '轉換面到貝塞爾',
   ('*', 'Loft') : '放樣',
   ('*', 'Auto Loft') : '自動放樣',
   ('Operator', 'Update Auto Loft') : '更新自動放樣',
   ('*', 'Sanitize') : '清理',
   ('Operator', 'Set Origin to Spline Start') : '設置原點到曲線起點',
   ('Operator', 'Reset Scale') : '重置縮放',
   ('*', 'Cleanup:') : '清理：',
   ('Operator', '0-Segment Splines') : '零分段樣條線',
   ('Operator', 'Short Splines') : '短樣條線',
   ('*', 'Threshold remove') : '閾值刪除',
   ('*', 'Join Splines:') : '連接樣條線：',
   ('Operator', 'Join Neighbouring Splines') : '連接相鄰樣條線',
   ('*', 'Only at Ends') : '僅在結束點',
   ('*', 'Join Position') : '連接點',
   ('*', 'At midpoint') : '在中點',
   ('*', 'Insert segment') : '插入段',
   ('*', 'Utilities') : '實用工具',
   ('*', 'Curve Resolution:') : '曲線分辨率：',
   ('Operator', 'Show [ESC]') : '顯示 [ESC]',
   ('Operator', 'Set Resolution') : '設置分辨率',
   ('*', 'Spline Order:') : '樣條順序：',
   ('*', 'Font Thickness') : '字體厚度',
   ('Operator', 'Set First Points') : '設置起始點',
   ('*', 'Path Finder') : '路徑查找器',
   ('Operator', 'Path Finder [ESC]') : '路徑查找器 [ESC]',
   ('*', 'PathFinder Radius') : '路徑查找器半徑',
   ('*', 'ESC or TAB - Exit PathFinder') : 'ESC 或 TAB - 退出路徑查找器',
   ('*', 'X or DEL - Delete') : 'X 或 DEL - 刪除',
   ('*', 'Alt + Mouse Click - Select Spline') : 'Alt + 點擊 - 選擇樣條線',
   ('*', 'Alt + Shift + Mouse click - Add Spline to Selection') : 'Alt + Shift + 點擊 - 添加樣條線到選集',
   ('*', 'A - Deselect All') : 'A - 取消選擇全部',
}