lang_dict = {
    ('*', 'LoopTools'): '循环工具',
    ('*', 'Mesh: LoopTools'): '网格：循环工具',

    ('Operator', 'Bridge'): '桥接',    
    ('Operator', 'Bridge / Loft'): '桥接/放榜',
    ('*', 'Remove faces'): '移除面',
    ('*', 'Best fit'): '最适合',
    ('*', 'Fit inside'): '适合内部',
    ('*', 'Restriction'): '限制',
    ('*', 'Extrude only'): '仅拉伸',
    ('*', 'Indent only'): '仅缩进',
    ('Operator', 'Gstretch'): 'G 伸展',
    ('*', 'Gstretch'): 'G 伸展',
    ('*', 'Use guides'): '使用指南',
    ('*', 'Spread evenly'): '均匀分布',
    ('*', 'Limit vertices'): '限制顶点',
    ('*', 'Exact vertices'): '精确顶点',
    ('*', 'No simplification'): '无简化',
    ('Operator', 'Delete Annotation Strokes'): '删除标注线',
    ('*', 'No simplification'): '无简化',
    ('*', 'Parallel (all)'): '平行（全部）',
    ('Operator', 'Space'): '空间',
}