lang_dict = {
    ('*', 'BoltFactory'): '螺栓工厂',
    ('*', 'Add Mesh: BoltFactory'): '添加网格：螺栓工厂',
    ('*', 'View3D > Add > Mesh'): '3D 视图 > 添加 > 网格',
    ('*', 'Add a bolt or nut'): '添加螺栓或螺母',
    ('Operator', 'Bolt'): '螺栓',
    ('Operator', 'Change Bolt'): '更改螺栓',
    ('*', 'Add Bolt'): '添加螺栓',
    ('Operator', 'Add Bolt'): '添加螺栓',
    ('*', 'Model'): '模型',
    ('*', 'BOLT'): '螺栓',
    ('*', 'NUT'): '螺母',
    ('*', 'Bit Type'): '钻子类型',
    ('*', 'NONE'): '无',
    ('*', 'ALLEN'): '六角',
    ('*', 'TORX'): '梅花',
    ('*', 'PHILLIPS'): '十字',
    ('*', 'Bit Depth'): '深度',
    ('*', 'Bit Dia'): '直径',
    ('*', 'Flat Dist'): '尺寸',
    ('*', 'Torx Size'): '梅花大小',
    ('*', 'HEX'): '六角',
    ('*', '12 POINT'): '12 点',
    ('*', 'CAP'): '帽',
    ('*', 'DOME'): '圆顶',
    ('*', 'PAN'): '平顶',
    ('*', 'PAN'): '平顶',
    ('*', 'COUNTER SINK'): '水槽',
    ('*', 'Head Height'): '高度',
    ('*', '12 Point Head Flange Dia'): '12 点头边直径',
    ('*', 'Head Dia'): '直径',
    ('*', 'Dome Head Dia'): '圆顶直径',
    ('*', 'Pan Head Dia'): '平顶直径',
    ('*', 'Shank'): '中段',
    ('*', 'Shank Length'): '中段长度',
    ('*', 'Shank Dia'): '中段直径',
    ('*', 'Thread'): '丝',
    ('*', 'Thread Length'): '丝长度',
    ('*', 'Major Dia'): '主直径',
    ('*', 'Minor Dia'): '次直径',
    ('*', 'Crest Percent'): '顶端百分比',
    ('*', 'Root Percent'): '底端百分比',
    ('*', 'Div count'): '股数',
    ('*', 'Nut Type'): '螺母类型',
    ('*', 'LOCK'): '底座',
    ('*', 'Hex Nut Height'): '高度',
    ('*', 'Hex Nut Flat Dist'): '直径',
    ('*', '12 Point Nut Height'): '高度',
    ('*', '12 Point Nut Flat Dist'): '直径',
    ('*', '12 Point Nut Flange Dia'): '边直径',
}