# -*- coding: utf-8 -*-

lang_dict = {
   ('*', 'BoltFactory') : '螺栓工廠',
   ('*', 'Add Mesh: BoltFactory') : '添加網格：螺栓工廠',
   ('*', 'View3D > Add > Mesh') : '3D 視圖 > 添加 > 網格',
   ('*', 'Add a bolt or nut') : '添加螺栓或螺母',
   ('Operator', 'Bolt') : '螺栓',
   ('Operator', 'Change Bolt') : '更改螺栓',
   ('*', 'Add Bolt') : '添加螺栓',
   ('Operator', 'Add Bolt') : '添加螺栓',
   ('*', 'Model') : '模型',
   ('*', 'BOLT') : '螺栓',
   ('*', 'NUT') : '螺母',
   ('*', 'Bit Type') : '鑽子類型',
   ('*', 'NONE') : '無',
   ('*', 'ALLEN') : '六角',
   ('*', 'TORX') : '梅花',
   ('*', 'PHILLIPS') : '十字',
   ('*', 'Bit Depth') : '深度',
   ('*', 'Bit Dia') : '直徑',
   ('*', 'Flat Dist') : '尺寸',
   ('*', 'Torx Size') : '梅花大小',
   ('*', 'HEX') : '六角',
   ('*', '12 POINT') : '12 點',
   ('*', 'CAP') : '帽',
   ('*', 'DOME') : '圓頂',
   ('*', 'PAN') : '平頂',
   ('*', 'COUNTER SINK') : '水槽',
   ('*', 'Head Height') : '高度',
   ('*', '12 Point Head Flange Dia') : '12 點頭邊直徑',
   ('*', 'Head Dia') : '直徑',
   ('*', 'Dome Head Dia') : '圓頂直徑',
   ('*', 'Pan Head Dia') : '平頂直徑',
   ('*', 'Shank') : '中段',
   ('*', 'Shank Length') : '中段長度',
   ('*', 'Shank Dia') : '中段直徑',
   ('*', 'Thread') : '絲',
   ('*', 'Thread Length') : '絲長度',
   ('*', 'Major Dia') : '主直徑',
   ('*', 'Minor Dia') : '次直徑',
   ('*', 'Crest Percent') : '頂端百分比',
   ('*', 'Root Percent') : '底端百分比',
   ('*', 'Div count') : '股數',
   ('*', 'Nut Type') : '螺母類型',
   ('*', 'LOCK') : '底座',
   ('*', 'Hex Nut Height') : '高度',
   ('*', 'Hex Nut Flat Dist') : '直徑',
   ('*', '12 Point Nut Height') : '高度',
   ('*', '12 Point Nut Flat Dist') : '直徑',
   ('*', '12 Point Nut Flange Dia') : '邊直徑',
}