lang_dict = {
    ('*', 'IvyGen'): '常春藤生成',
    ('*', 'Add Curve: IvyGen'): '添加曲线：常春藤生成',
    ('*', 'View3D > Sidebar > Ivy Generator (Create Tab)'): '3D 视图 > 边栏 > 常春藤生成器',
    ('*', 'View3D > Sidebar > Ivy Generator (Create Tab)'): '3D 视图 > 边栏 > 常春藤生成器 (创建选项卡)',
    ('*', "Adds generated ivy to a mesh object starting "
                   "at the 3D cursor"): '从 3D 光标开始生成常春藤到网格对象',
    ('*', 'Ivy Generator'): '常春藤生成器',
    ('Operator', 'Add New Ivy'): '添加新常春藤',
    ('Operator', 'Add New Default Ivy'): '添加新默认常春藤',
    ('*', 'Generation Settings:'): '生成设置：',
    ('*', 'Maximum Time'): '最大时间',
    ('*', 'Size Settings:'): '大小设置：',
    ('*', 'Max Ivy Length'): '最大藤长度',
    ('*', 'Ivy Size'): '藤尺寸',
    ('*', 'Max Float Length'): '最浮动长度',
    ('*', 'Max Adhesion Length'): '最大黏附长度',
    ('*', 'Weight Settings:'): '权重设置：',
    ('*', 'Primary Weight'): '主权重',
    ('*', 'Random Weight'): '随机权重',
    ('*', 'Gravity Weight'): '重力权重',
    ('*', 'Adhesion Weight'): '黏附权重',
    ('*', 'Branch Settings:'): '分支设置：',
    ('*', 'Branching Probability'): '分支概率',
    ('*', 'Ivy Branch Size'): '藤分支尺寸',
    ('*', 'Grow Leaves'): '生成叶子',
    ('*', 'Leaf Settings:'): '叶子设置：',
    ('*', 'Ivy Leaf Size'): '生成叶子尺寸',
    ('*', 'Leaf Probability'): '叶子概率',
    
    ('Operator', 'IvyGen'): '常春藤生成',
    ('*', 'Update Ivy'): '更新常春藤',
}