# -*- coding: utf-8 -*-

lang_dict = {
   ('*', 'IvyGen') : '常春藤生成',
   ('*', 'Add Curve: IvyGen') : '添加曲線：常春藤生成',
   ('*', 'View3D > Sidebar > Ivy Generator (Create Tab)') : '3D 視圖 > 邊欄 > 常春藤生成器 (創建選項卡)',
   ('*', 'Adds generated ivy to a mesh object starting at the 3D cursor') : '從 3D 光標開始生成常春藤到網格對象',
   ('*', 'Ivy Generator') : '常春藤生成器',
   ('Operator', 'Add New Ivy') : '添加新常春藤',
   ('Operator', 'Add New Default Ivy') : '添加新默認常春藤',
   ('*', 'Generation Settings:') : '生成設置：',
   ('*', 'Maximum Time') : '最大時間',
   ('*', 'Size Settings:') : '大小設置：',
   ('*', 'Max Ivy Length') : '最大藤長度',
   ('*', 'Ivy Size') : '藤尺寸',
   ('*', 'Max Float Length') : '最浮動長度',
   ('*', 'Max Adhesion Length') : '最大黏附長度',
   ('*', 'Weight Settings:') : '權重設置：',
   ('*', 'Primary Weight') : '主權重',
   ('*', 'Random Weight') : '隨機權重',
   ('*', 'Gravity Weight') : '重力權重',
   ('*', 'Adhesion Weight') : '黏附權重',
   ('*', 'Branch Settings:') : '分支設置：',
   ('*', 'Branching Probability') : '分支概率',
   ('*', 'Ivy Branch Size') : '藤分支尺寸',
   ('*', 'Grow Leaves') : '生成葉子',
   ('*', 'Leaf Settings:') : '葉子設置：',
   ('*', 'Ivy Leaf Size') : '生成葉子尺寸',
   ('*', 'Leaf Probability') : '葉子概率',
   ('Operator', 'IvyGen') : '常春藤生成',
   ('*', 'Update Ivy') : '更新常春藤',
}