# -*- coding: utf-8 -*-
 
lang_dict = {
    # bl_info
    ('*', 'Node: Animation Nodes') : '节点： 动画节点编辑器(Animation Nodes)',
    ('*', 'Animation Nodes') : '动画节点编辑器',
    ('*', 'Node based visual scripting system designed for motion graphics in Blender.') : '基于节点的可视化脚本系统，专为 Blender 中的运动图形而设计。',
    ('*', 'Animation Nodes Editor'): '动画节点编辑器',
    ('*', 'This version is still in development.'): '此版本任在开发中',

    # pref
    ('*', 'Node Colors:'): '节点颜色：',
    ('*', 'Main Network'): '主网络',
    ('*', 'Invalid Network'): '无效网络',
    ('*', 'Run Tests'): '运行测试',
    ('*', 'Subprogram Value'): '子程序亮度',
    ('*', 'Subprogram Saturation'): '子程序饱和度',
    ('*', 'Color for all networks that are not in a subprogram'): '非子程序中的所有网络的颜色',
    ('*', 'Color for networks that stop the execution because they have an error'): '因出现错误而停止执行的网络的颜色',
    ('*', 'Lightness of random subnetwork colors'): '随机子网颜色的亮度',
    ('*', 'Color intensity of random subnetwork colors'): '随机子网颜色的强度',
    ('*', 'Enable some print statements'): '启用一些打印语句',
    ('*', 'Run the test suite when Blender starts'): 'Blender 启动时运行测试套件',
    ('*', 'How to Uninstall?'): '如何卸载？',
    ('*', 'Animation Node Tree'): '动画节点树',

    # panels
    ('*', 'Auto Execution'): '自动执行',
    ('*', 'Tree Changed'): '树改变时',
    ('*', 'Frame Changed'): '帧改变时',
    ('*', 'Property Changed'): '属性改变时',
    ('*', 'Min Time Difference'): '最小时差',
    ('Operator', 'New Trigger'): '添加触发器',
    ('Operator', 'Remove Auto Execution Trigger'): '删除自动执行触发器',
    ('Operator', 'Enable'): '启用',
    ('Operator', 'Execute Node Tree'): '执行节点树',
    ('*', 'Details'): '明细',
    ('*', 'Measure execution times of the individual nodes'): '测量各个节点的执行时间',
    ('*', 'Edit Node Labels'): '编辑节点标签',
    ('*', 'Overview'): '概述',
    ('*', 'Execution Code:'): '执行代码：',
    ('*', 'Different execution codes can be useful in different contexts'): '不同的执行代码在不同的上下文中很有用',
    ('*', 'Monitor Execution'): '监视执行',
    ('*', 'Measure Execution Times'): '测量执行时间',
    ('Operator', 'Print'): '打印',
    ('*', 'Print the code of the currently active node'): '打印当前活动节点的代码',
    ('Operator', 'Write'): '编写',
    ('*', 'Write the code of the currently active node in a text block'): '在文本块中写入当前活动节点的代码',
    ('Operator', 'Select Area'): '选择区域',
    ('*', 'Profiling Function'): '分析功能',
    ('*', 'Function'): '功能',
    ('*', 'Execution'): '执行',
    ('*', 'Tree Analysis'): '树分析',
    ('*', 'Update Everything'): '更新全部',
    ('*', 'Script Generation'): '脚本生成',
    ('*', 'Sort Mode'): '排序模式',
    ('*', 'Amount of Calls'): '调用次数',
    ('*', 'Total Time'): '总时间',
    ('*', 'Cumulative Time'): '累计时间',
    ('*', 'Text Block'): '文本块',
    ('Operator', 'Profile'): '分析',
    ('*', 'Networks'): '网络',
    ('*', 'Needed Copies'): '所需副本',
    ('*', 'Use Network Color'): '使用网络颜色',
    ('*', 'Only subprograms have a custom network color'): '只有子程序具有自定义网络颜色',
    ('*', 'Advanced Node Settings'): '高级节点设置',
    ('*', 'Has no advanced settings'): '没有高级设置',
    ('*', 'Viewport Input'): '视口输入',
    ('*', 'No Viewport Input node.'): '没有视口输入节点',
    ('*', 'ID Keys'): 'ID 键',
    ('*', 'Initial Transforms'): '初始变换',
    ('Operator', 'From Current Transforms'): '从当前变换',
    ('Operator', 'Sort Objects'): '排序对象',
    ('*', 'Selection Order'): '选中的顺序',
    ('Operator', 'New ID Key'): '新增 ID 键',
    # menus & nodes
    ('*', 'Number'): '数值',
    ('*', '   There are no subprograms yet'): '   没有子程序',
    ('Operator', 'Remove Animation Node Tree'): '移除动画节点树',
    ('*', 'Remove the active animation node tree'): '移除活动的动画节点树',
    ('Operator', 'Integer'): '整数',
    ('Operator', 'Float'): '浮点数',
    ('Operator', 'Integer List'): '整数列表',
    ('Operator', 'Float List'): '浮点数列表',
    ('Operator', 'Integer Range'): '整数范围序列',
    ('Operator', 'Float Range'): '浮点数范围序列',
    ('Operator', 'Parse Number'): '解析数值',
    ('Operator', 'Constants'): '常量',
    ('Operator', 'Random'): '随机',
    ('Operator', 'Wiggle'): '摇摆',
    ('Operator', 'Mix'): '混合',
    ('Operator', 'Map Range'): '范围映射',
    ('Operator', 'Math'): '运算',
    ('Operator', 'List Math'): '列表运算',
    ('Operator', 'Sort Numbers'): '排序数值',
    ('Operator', 'Clamp'): '钳制',
    ('Operator', 'Round'): '四舍五入',
    ('Operator', 'Convert Angle'): '角度转换',
    ('Operator', 'Float to Integer'): '浮点到整数',
    ('Operator', 'Float to Text'): '浮点到文本',
    ('Operator', 'Combine'): '组合',
    ('Operator', 'From Value'): '从值',
    ('Operator', 'List'): '列表',
    ('Operator', 'Noise'): '噪声',
    ('Operator', 'Distance'): '距离',
    ('Operator', 'Distance to Line'): '到线的距离',
    ('Operator', 'Distance to Plane'): '到面的距离',
    ('Operator', 'Dot Product'): '点乘',
    ('Operator', 'Offset'): '偏移',
    ('Operator', 'Direction to Rotation'): '方向到旋转',
    ('Operator', 'Rotation to Direction'): '旋转到方向',
    ('Operator', 'Euler to/from Vector'): '欧拉到/从矢量',
    ('Operator', 'Convert Rotation Types'): '转换旋转类型',
    ('Operator', 'Separate Euler'): '分离欧拉',
    ('Operator', 'Combine Euler'): '组合欧拉',
    ('Operator', 'Euler Math'): '欧拉运算',
    ('Operator', 'Euler Mix'): '欧拉混合',
    ('Operator', 'Random Euler'): '随机欧拉',
    ('Operator', 'Euler Wiggle'): '摇摆欧拉',
    ('Operator', 'Separate Quaternion'): '分离四元数',
    ('Operator', 'Combine Quaternion'): '组合四元数',
    ('Operator', 'Quaternion Math'): '四元数运算',
    ('Operator', 'Quaternion Mix'): '四元数混合',
    ('Operator', 'Random Quaternion'): '随机四元数',
    ('Operator', 'Quaternion Wiggle'): '摇摆四元数',
    ('Operator', 'Combine Quaternion Rotations'): '组合四元旋转',
    ('Operator', 'Compose'): '组成',
    ('Operator', 'Decompose'): '分解',
    ('Operator', 'Distribute'): '分发',
    ('Operator', 'Replicate'): '复制',
    ('Operator', 'Axis Rotation'): '轴向旋转',
    ('Operator', 'Extract Matrix Basis'): '提取矩阵基础',
    ('Operator', 'Input'): '输入',
    ('Operator', 'Characters'): '字符',
    ('Operator', 'Convert To Text'): '转换到文本',
    ('Operator', 'Timecode Generator'): '时间码生成器',
    ('Operator', 'Change Text Case'): '转换大小写',
    ('Operator', 'Reverse'): '反向',
    ('Operator', 'LSystem'): 'L系统',
    ('Operator', 'Decompose Text'): '分解文本',
    ('Operator', 'Block Reader'): '块读取器',
    ('Operator', 'Block Writer'): '块写入器',
    ('Operator', 'Filter Text Block List'): '过滤文本块列表',
    ('Operator', 'File Reader'): '文件读取器',
    ('Operator', 'Sequence Output'): '序列输出',
    ('*', 'Element'): '元素',
    ('*', 'Start / Step'): '起始 / 步长',
    ('*', 'Start / Stop'): '起始 / 停止',
    ('*', 'Include End Point'): '包括停止',
    ('*', 'List'): '列表',
    ('*', 'Create'): '创建',
    ('*', 'More'): '更多',
    ('*', 'Subprograms'): '子程序',
    ('Operator', 'Search'): '搜索',
    ('*', 'Results'): '结果',
    ('Operator', 'Are you sure?'): '是否确定？',
    ('*', 'Remove unlinked inputs'): '删除未连接的输入',
    ('Operator', 'Remove Unlinked Inputs'): '删除未连接的输入',
    ('*', 'Sorted Numbers'): '已排序数值',
    ('Operator', 'Time Info'): '时间信息',
    ('Operator', 'Delay'): '延时',
    ('Operator', 'Repeat'): '重复',
    ('Operator', 'New Input'): '添加输入',
    ('*', 'Create a new input socket'): '添加一个新的输入端口',
    ('*', 'Node Seed'): '随机种子',
    ('*', 'Degree'): '度',
    ('*', 'Degree to Radian'): '度到弧度',
    ('*', 'Radian'): '弧度',
    ('*', 'Radian to Degree'): '弧度到度',
    ('*', 'Vectors'): '向量',
    ('*', 'Evolution'): '演变',
    ('*', 'Persistance'): '持续',
    ('*', 'Simplex'): '简单',
    ('*', 'Perlin'): '柏林',
    ('*', 'Cellular'): '蜂窝',
    ('*', 'Cell Value'): '格值',
    ('*', 'Clamp Factor'): '钳制因子',
    ('*', 'Clamp factor between 0 and 1'): '限制结果为 0 到 1 的范围内',
    ('*', 'Line Start'): '线起点',
    ('*', 'Parameter'): '参数',
    ('*', 'Signed Distance'): '距离',
    ('*', 'Rotation Difference'): '旋转差异',
    ('*', 'Vector List'): '向量列表',
    ('*', 'Matrix Rotation'): '矩阵旋转',
    ('*', 'Euler to Vector'): '欧拉到矢量',
    ('*', 'Vector to Euler'): '矢量到欧拉',
    ('*', 'Use Degree'): '使用度',
    ('*', 'Matrix to Euler'): '矩阵到欧拉',
    ('*', 'Euler to Matrix'): '欧拉到矩阵',
    ('*', 'Quaternion to Euler'): '四元数到欧拉',
    ('*', 'Euler to Quaternion'): '欧拉到四元数',
    ('*', 'Quaternion to Matrix'): '四元数到矩阵',
    ('*', 'Matrix to Quaternion'): '矩阵到四元数',
    ('*', 'Quaternion to Axis Angle'): '四元数到轴角度',
    ('*', 'Axis Angle to Quaternion'): '轴角度到四元数',
    ('*', 'Matrices'): '矩阵',
    ('*', 'X Divisions'): 'X 分段',
    ('*', 'Y Divisions'): 'Y 分段',
    ('*', 'Z Divisions'): 'Z 分段',
    ('*', 'X Distance'): 'X 距离',
    ('*', 'Y Distance'): 'Y 距离',
    ('*', 'Z Distance'): 'Z 距离',
    ('*', 'Start Radius'): '起始半径',
    ('*', 'End Radius'): '结束半径',
    ('*', 'Start Size'): '起始尺寸',
    ('*', 'End Size'): '结束尺寸',
    ('*', 'Start Angle'): '起始角度',
    ('*', 'End Angle'): '结束角度',
    ('*', 'Transformations'): '变换',
    ('*', 'Inverted Matrix'): '倒置矩阵',
    ('*', 'Loc/Rot/Scale'): '位置/旋转/缩放',
    ('*', 'Characters'): '字符',
    ('*', 'Special'): '特殊',
    ('*', 'Line Break'): '断行',
    ('*', 'Text List'): '文本列表',
    ('*', 'Words'): '词',
    ('*', 'Regular Expression'): '正则表达式',
    ('*', 'Keep Delimiters'): '保留分隔符',
    ('*', 'Split By'): '分隔符',
    ('*', 'N Characters'): 'N 个字符',
    ('*', 'Separator'): '分隔符',
    ('*', 'To Upper Case'): '大写',
    ('*', 'To Lower Case'): '小写',
    ('*', 'To Title Case'): '词首大写',
    ('*', 'Capitalize Phrase'): '大写短语',
    ('*', 'Capitalize Words'): '大写词',
    ('*', 'at Start'): '在开始',
    ('*', 'at End'): '在结尾',
    ('*', 'Repeats'): '重复',
    ('*', 'Axiom'): '公理化',
    ('*', 'Rules'): '规则',
    ('*', 'Edge Widths'): '边缘宽度',
    ('*', 'Symbols'): '符号',
    ('*', 'Generations'): '代',
    ('*', 'Scale Width'): '缩放宽度',
    ('*', 'Scale Step Size'): '缩放步尺寸',
    ('*', 'Only Partial Moves'): '仅部分移动',
    ('*', 'Character'): '字符',
    ('*', 'Word'): '单词',
    ('*', 'BFont is not Supported!'): '不支持 BFont!',
    ('Operator', 'Choose Path'): '选择路径',
    ('*', 'Text Block List'): '文本块列表',    
    ('*', 'Starts With'): '开始是',
    ('*', 'Ends With'): '结尾是',   
    ('*', 'All Objects with names starting with'): '所有特定名称开始的对象',
    ('*', 'Ends With'): '结尾是',
    ('*', 'All Objects with names ending with'): '所有特定名称结尾的对象',
    ('*', 'Path does not exist'): '路径不存在',
    ('Operator', 'Character Property'): '字符属性',
    ('Operator', 'Object Separate'): '对象分离',
    ('*', 'Text Objects'): '文本对象',
    ('Operator', 'Update'): '更新',
    ('*', 'Origin to Center of Mass'): '原点 -> 质心点',
    ('*', 'Origin to Cursor'): '原点 -> 3D 浮标',
    ('Operator', 'Object Output'): '对象输出',
    ('*', 'Horizontal Align'): '横向对齐',
    ('*', 'Vertical Align'): '垂直对齐',
    ('*', 'Bold Font'): 'Bold 字体',
    ('*', 'Italic Font'): 'Italic 字体',
    ('*', 'Bold Italic Font'): 'Bold Italic 字体',
    ('Operator', 'Boolean'): '布尔',
    ('Operator', 'Compare'): '比较',
    ('Operator', 'Switch'): '切换',
    ('*', 'Condition'): '条件',
    ('*', 'If True'): '为真',
    ('*', 'If False'): '否则',
    ('Operator', 'Logic'): '逻辑',
    ('*', 'A and B'): 'A 和 B',
    ('*', 'not (A and B)'): '非(A 和 B)',
    ('*', 'A or B'): 'A 或 B',
    ('*', 'not (A or B)'): '非(A 或 B)',
    ('*', 'A xor B'): 'A 异同 B',
    ('Operator', 'List Logic'): '列表逻辑',
    ('*', 'Boolean List'): '布尔列表',
    ('*', 'All True'): '全为真',
    ('*', 'All False'): '全为假',
    ('*', 'Not All True'): '任意假',
    ('*', 'Not All False'): '任意真',
    ('Operator', 'Random Boolean'): '随机布尔',
    ('Operator', 'Choose Color'): '选择颜色',
    ('*', 'Alpha'): '不透明度',
    ('Operator', 'Combine Color'): '组合颜色',
    ('Operator', 'Separate Color'): '分离颜色',
    ('Operator', 'Separate Color'): '分离颜色',
    ('Operator', 'Set Vertex Color'): '设置顶点颜色',
    ('*', 'Vertex Color Index'): '顶点颜色索引',
    ('Operator', 'Vector'): '向量',
    ('Operator', 'Action'): '动作',
    ('Operator', 'Collection'): '集合',
    ('Operator', 'Edge Indices'): '边索引',
    ('Operator', 'Euler'): '欧拉',
    ('Operator', 'FCurve'): '斯特里贝克曲线',
    ('Operator', 'Falloff'): '衰减',
    ('Operator', 'Font'): '字体',
    ('Operator', 'Generic'): '通用',
    ('Operator', 'Interpolation'): '插值',
    ('Operator', 'Material'): '材质',
    ('Operator', 'Matrix'): '矩阵',
    ('Operator', 'Mesh'): '网格',
    ('Operator', 'NlaStrip'): '恩拉斯特里普',
    ('Operator', 'Change Type'): '更改类型',
    ('Operator', 'Particle System'): '粒子系统',
    ('Operator', 'Polygon Indices'): '多边形索引',
    ('Operator', 'Quaternion'): '四元数',
    ('Operator', 'Shape Key'): '形状键',
    ('Operator', 'Spline'): '样条',
    ('Operator', 'Struct'): '结构',
    ('Operator', 'Text Block'): '文本块',
    ('Operator', 'Vector 2D'): '2D 向量',
    ('*', 'Hide Inputs'): '隐藏输入',
    ('*', 'Action List'): '行为列表',
    ('*', 'Float List'): '浮点列表',
    ('*', 'Falloff List'): '衰减列表',
    ('*', 'Struct List'): '结构列表',
    ('*', 'Shape Key List'): '形状键列表',
    ('*', 'Scene List'): '场景列表',
    ('*', 'Integer List'): '整数列表',
    ('*', 'Quaternion List'): '四元数列表',
    ('*', 'Spline List'): '样条列表',
    ('*', 'Polygon Indices List'): '多边形索引列表',
    ('Operator', 'Get Element'): '获取元素',
    ('Operator', 'Get Random Elements'): '随机获取元素',
    ('*', 'Multiple'): '多个',
    ('Operator', 'Search Element'): '搜索元素',
    ('*', 'First Index'): '第一个索引',
    ('*', 'All Indices'): '全部索引',
    ('*', 'Occurrences'): '事件',
    ('Operator', 'Set Element'): '设置元素',
    ('Operator', 'Remove Element'): '移除元素',
    ('*', 'First Occurrence'): '第一次触发',
    ('*', 'All Occurrences'): '全部触发',
    ('Operator', 'Get Length'): '获取长度',
    ('Operator', 'Shuffle'): '洗牌',
    ('*', 'Shuffled List'): '已洗牌列表',
    ('*', 'Reversed List'): '已反向列表',
    ('Operator', 'Slice'): '分割',
    ('Operator', 'Shift'): '位移',
    ('*', 'Shifted List'): '已位移列表',
    ('*', 'Ping Pong'): '乒乓',
    ('*', 'Below Length'): '长度以下',
    ('*', 'Above Length'): '长度以上',
    ('Operator', 'Repeat Elements'): '重复元素',
    ('*', 'Repeated List'): '已重复列表',
    ('Operator', 'List Boolean Operations'): '列表布尔操作',
    ('*', 'Intersection'): '交集',
    ('*', 'Symmetric Difference'): '对称差异',
    ('*', 'List 1'): '列表 1',
    ('*', 'List 2'): '列表 2',
    ('Operator', 'Set Struct Elements'): '设置结构元素',
    ('*', 'Struct'): '结构',
    ('*', 'New Input'): '新建输入',
    ('Operator', 'Get Struct Elements'): '获取结构元素',
    ('*', 'New Output'): '新建输出',
    ('Operator', 'Get Struct List Elements'): '获取结构列表元素',
    ('Operator', 'Filter Object List'): '过滤对象列表',
    ('*', 'Object List'): '对象列表',
    ('Operator', 'Collection Info'): '集合信息',
    ('Operator', 'Transforms Input'): '变换输入',
    ('Operator', 'Mesh Input'): '网络输入',
    ('*', 'Vertex Locations'): '顶点位置',
    ('*', 'Polygon Centers'): '多边形中心',
    ('*', 'Use World Space'): '使用世界空间',
    ('*', 'Use Modifiers'): '使用修改器',
    ('*', 'Load UVs'): '加载 UV',
    ('*', 'Load Vertex Colors'): '加载顶点颜色',
    ('*', 'Vertex Normals'): '顶点法向',
    ('*', 'Polygon Normals'): '多边形法向',
    ('*', 'Edge Indices'): '边索引',
    ('*', 'Polygon Indices'): '多边形索引',
    ('*', 'Local Polygon Areas'): '本地多边形面积',
    ('*', 'Material Indices'): '材质索引',
    ('*', 'Mesh Name'): '网格名称',
    ('Operator', 'Transforms Output'): '变换输出',
    ('Operator', 'Matrix Input'): '矩阵输入',
    ('Operator', 'Matrix Output'): '矩阵输出',
    ('Operator', 'Attribute Input'): '属性输入',
    ('Operator', 'Attribute Output'): '属性输出',
    ('Operator', 'Color Output'): '颜色输出',
    ('Operator', 'Data Path Output'): '数据路径输出',
    ('*', 'Array Index'): '数组索引',
    ('Operator', 'Visibility Input'): '可见性输入',
    ('*', 'Hide Viewport'): '视图隐藏',
    ('*', 'Hide Render'): '渲染隐藏',
    ('*', 'Show Axis'): '轴向',
    ('*', 'Show In Front'): '在前面',
    ('Operator', 'Visibility Output'): '可见性输出',
    ('Operator', 'Shape Keys from Object'): '从对象的形状键',
    ('Operator', 'Shape Key Output'): '形状键输出',
    ('Operator', 'ID Key'): 'ID 键',
    ('Operator', 'Choose ID Key'): '选择 ID 键',
    ('Operator', 'Copy Data'): '复制数据',
    ('*', 'From'): '从',
    ('*', 'Deep Copy'): '深拷贝',
    ('Operator', 'Set Keyframes'): '设置关键帧',
    ('*', 'Set Keyframe'): '设置关键帧',
    ('*', 'Remove Unwanted'): '删除不需要的',
    ('Operator', 'Armature Info'): '骨架信息',
    ('*', 'Directions'): '方向',
    ('*', 'Lengths'): '长度',
    ('*', 'Rest'): '休息',
    ('*', 'Utils'): '其它',
    ('Operator', 'Update Matrices'): '更新矩阵',
    ('Operator', 'Reset Transformations'): '复位变换',
    ('Operator', 'Copy Transformations'): '复制变换',
    ('Operator', 'Get Selected Objects'): '获取选中的对象',
    ('Operator', 'Get Active Camera'): '获取活动相机',
    ('*', 'Disabled During Rendering'): '渲染期间禁用',
    ('*', 'Active Camera'): '活动相机',
    ('Operator', 'Instancer'): '实例化',
    ('*', 'Copy from Source'): '从源复制',
    ('*', 'Copy Full Object'): '复制整个对象',
    ('*', 'Instances'): '实例数',
    ('Operator', 'Collection Operations'): '集合操作',
    ('Operator', 'Collection By Name'): '命名的集合',
    ('Operator', 'Create Collection List'): '创建集合列表',
    ('Operator', 'From Selection'): '从所选',
    ('Operator', 'Combine Collection Lists'): '组合集合列表',
    ('Operator', 'Filter Collection List'): '过滤集合列表',
    ('*', 'Collection List'): '集合列表',
    ('Operator', 'Mesh Info'): '网格信息',
    ('*', 'UV Map Names'): 'UV 映射名称',
    ('*', 'Vertex Color Layers'): '顶点颜色层',
    ('Operator', 'Get Bounding Box'): '获取边界框',
    ('Operator', 'Combine Mesh'): '组合网格',
    ('Operator', 'Mesh From Spline'): '来自样条的网格',
    ('*', 'Use Custom Shape'): '使用自定义形状',
    ('*', 'Spline Resolution'): '样条分辨率',
    ('*', 'Cap Ends'): '闭合结束',
    ('*', 'Mesh Data'): '网格数据',
    ('Operator', 'Vertex Group Input'): '顶点组输入',
    ('Operator', 'Set Vertex Weight'): '设置顶点权重',
    ('Operator', 'Get Vertex Color Layer'): '获取顶点颜色层',
    ('Operator', 'Insert Vertex Color Layer'): '插入顶点颜色层',
    ('Operator', 'Set Bevel Vertex Weight'): '设置顶点倒角权重',
    ('Operator', 'Set Bevel Edge Weight'): '设置边倒角权重',
    ('Operator', 'Set Edge Crease'): '设置边折痕',
    ('Operator', 'Get UV Map'): '获取 UV 贴图',
    ('*', 'Positions'): '位置',
    ('Operator', 'Insert UV Map'): '插入 UV 贴图',
    ('Operator', 'Set UV Map'): '设置 UV 贴图',
    ('*', 'UV Map Index'): 'UV 贴图索引',
    ('Operator', 'Set Polygon Material Index'): '设置多边形材质索引',
    ('Operator', 'Offset Polygons'): '偏移多边形',
    ('Operator', 'Separate Polygons'): '分离多边形',
    ('Operator', 'Extract Polygon Transforms'): '提取多边形变换',
    ('*', 'Inverted Transforms'): '反向变换',
    ('Operator', 'Offset Vertices'): '偏移顶点',
    ('Operator', 'Transform Mesh'): '变换网格',
    ('Operator', 'Triangulate Mesh'): '三角测量网格',
    ('*', 'Use Advanced Method'): '使用高级方法',
    ('*', 'Generators'): '生成器',
    ('*', 'Start-End'): '起始点到结束点',
    ('*', 'Merge Start End'): '闭合',
    ('*', 'Merge Center'): '合并中心',
    ('*', 'Radial Loops'): '径向环',
    ('*', 'Inner Loops'): '内部循环',
    ('*', 'Inner Radius'): '内部半径',
    ('*', 'Outer Radius'): '外部半径',
    ('Operator', 'Unity Triangle'): '等边三角',
    ('*', 'Regular Polygons'): '常规多边形',
    ('Operator', 'Regular Pentagon'): '五边形',
    ('Operator', 'Regular Hexagon'): '六边形',
    ('Operator', 'Regular Heptagon'): '七边形',
    ('Operator', 'Regular Octagon'): '八边形',
    ('Operator', 'Find Close Points'): '查找最近点',
    ('*', 'Distances'): '距离',
    ('Operator', 'Edge to Tube'): '边到管道',
    ('Operator', 'Scatter Points'): '散点',
    ('Operator', 'Create Edges'): '创建边',
    ('*', 'Edge Indices List'): '边索引列表',
    ('*', 'Edge Starts'): '边开始',
    ('*', 'Edge Ends'): '边结束',
    ('Operator', 'Create Edge Indices'): '创建边索引',
    ('*', 'Index 1'): '索引 1',
    ('*', 'Index 2'): '索引 2',
    ('Operator', 'Create Polygon Indices'): '创建多边形索引',
    ('*', 'Vertex Amount'): '顶点数',
    ('Operator', 'Edges of Polygons'): '多边形的边',
    ('Operator', 'Edge Info'): '边信息',
    ('Operator', 'Get Linked Vertices'): '获取连接的顶点',
    ('*', 'Vextex Index'): '顶点索引',
    ('Operator', 'Mesh List'): '网格列表',
    ('*', 'Mesh List'): '网格列表',
    ('Operator', 'Join Mesh List'): '连接网格列表',
    ('Operator', 'BMesh Mesh'): 'BMesh 网格',
    ('Operator', 'BMesh from Mesh'): '网格到 BMesh',
    ('Operator', 'BMesh from Object'): '对象到 BMesh',
    ('*', 'Use Deform Modifiers'): '使用变形修改器',
    ('*', 'Dissolve Boundries'): '溶解边界',
    ('Operator', 'Invert Normals'): '翻转法向',
    ('Operator', 'Shade Object Smooth'): '平滑着色',
    ('*', 'Is Used'): '是否使用',
    ('Operator', 'Get from Object'): '取自对象',
    ('Operator', 'Create from Points'): '创建自点',
    ('*', 'Left Handles'): '左控制柄',
    ('*', 'Right Handles'): '右控制柄',
    ('Operator', 'Create from Edges'): '创建自线段',
    ('*', 'Spline Per Edge'): '每个边的样条',
    ('*', 'Spline Per Branch'): '每个分支的样条',
    ('*', 'Radius per Edge'): '每个边的半径',
    ('*', 'Radius per Vertex'): '每个顶点的半径',
    ('Operator', 'Create from Stroke'): '创建自笔刷',
    ('Operator', 'Append Point'): '增加点',
    ('*', 'Bezier Point'): '贝塞尔点',
    ('Operator', 'Set Radius'): '设置半径',
    ('Operator', 'Make Cyclic'): '使循环',
    ('Operator', 'Smooth Bezier'): '平滑贝塞尔',
    ('Operator', 'Tilt Spline'): '倾斜样条',
    ('Operator', 'Change Direction'): '改变方向',
    ('Operator', 'Offset Spline'): '偏移样条',
    ('Operator', 'Info'): '信息',
    ('*', 'Radii'): '半径',
    ('*', 'Tilts'): '倾斜',
    ('*', 'Point Amount'): '点数量',
    ('Operator', 'Evaluate'): '评估',
    ('Operator', 'Project'): '投影',
    ('*', 'Extended'): '扩展',
    ('Operator', 'Loft'): '放样',
    ('*', 'Spline Samples'): '样条采样',
    ('Operator', 'Revolve'): '围绕', 
    ('*', 'Surface Samples'): '表面采样',
    ('Operator', 'Object Input'): '对象输入', 
    ('Operator', 'Layer Info'): '层信息', 
    ('Operator', 'Frame Info'): '帧信息', 
    ('Operator', 'Stroke Info'): '笔刷信息', 
    ('*', 'Frame Index'): '帧索引', 
    ('*', 'Pressures'): '压力', 
    ('*', 'Vertex Color Fill'): '顶点颜色填充', 
    ('*', 'UV-Rotations'): 'UV 旋转', 
    ('*', 'Start Cap Mode'): '起始端模式', 
    ('*', 'End Cap Mode'): '结束端模式', 
    ('Operator', 'Set Layer Attributes'): '设置图层属性', 
    ('*', 'Invert Mask Layer'): '反转遮罩层', 
    ('Operator', 'Replicate Layer'): '复制层', 
    ('*', 'Offset Frame'): '偏移帧', 
    ('Operator', 'Transform Layer'): '变换图层',
    ('Operator', 'Offset Layer Frames'): '偏移图层帧', 
    ('Operator', 'Set Stroke Attributes'): '设置画笔属性', 
    ('Operator', 'Replicate Stroke'): '复制画笔', 
    ('Operator', 'Transform Stroke'): '变换画笔',
    ('Operator', 'Offset Stroke'): '偏移画笔', 
    ('*', 'UVRotation'): 'UV 旋转', 
    ('*', 'UV-Rotation'): 'UV 旋转', 
    ('Operator', 'Change Stroke Direction'): '更改画笔方向', 
    ('Operator', 'Stroke From Points'): '画笔自点', 
    ('Operator', 'Stroke From Spline'): '画笔自样条线', 
    ('Operator', 'Frame From Strokes'): '画笔到帧', 
    ('Operator', 'Layer From Frames'): '帧到图层', 
    ('Operator', 'GP Material Output'): '蜡笔材质输出', 
    ('Operator', 'Object Material Output'): '对象材质输出', 
    ('Operator', 'From Object'): '来自对象', 
    ('Operator', 'Particles Data'): '粒子数据', 
    ('Operator', 'Hair Data'): '头发数据', 
    ('*', 'Stroke Draw Mode'): '笔画绘制模式', 
    ('*', 'Hair Splines'): '头发样条线', 
    ('*', 'Velocities'): '速度', 
    ('*', 'Sizes'): '尺寸', 
    ('*', 'Birth Times'): '出生时间', 
    ('*', 'Die Times'): '消亡时间', 
    ('*', 'Rate'): '速率', 
    ('Operator', 'Animate Matrix'): '矩阵动画', 
    ('Operator', 'Animate Vector'): '向量动画', 
    ('Operator', 'Animate Float'): '浮点动画', 
    ('Operator', 'Animate Color'): '颜色动画', 
    ('Operator', 'Animate Euler'): '欧拉动画', 
    ('Operator', 'Animate Quaternion'): '四元数动画', 
    ('Operator', 'Mix Matrix List'): '混合矩阵列表', 
    ('Operator', 'Mix Vector List'): '混合向量列表', 
    ('Operator', 'Mix Float List'): '混合浮点列表', 
    ('Operator', 'Mix Color List'): '混合颜色列表', 
    ('Operator', 'Mix Euler List'): '混合欧拉列表', 
    ('Operator', 'Mix Quaternion List'): '混合四元数列表', 
    ('Operator', 'Construct'): '构建', 
    ('Operator', 'From Curve'): '从曲线', 
    ('Operator', 'From FCurve'): '从斯特里贝克曲线', 
    ('*', 'Matrix List'): '矩阵列表', 
    ('*', 'Cache Interpolation'): '缓存插值', 
    ('Operator', 'Reset End Points'): '重置结束点', 
    ('*', 'FCurve'): '斯特里贝克曲线', 
    ('Operator', 'Mirror Interpolation'): '镜像插值', 
    ('*', 'Chain'): '链', 
    ('*', 'Input Min'): '输入最小值', 
    ('*', 'Input Max'): '输入最大值', 
    ('*', 'Output Min'): '输出最小值', 
    ('*', 'Output Max'): '输出最大值', 
    ('*', 'Start / Amount'): '开始 / 数量', 
    ('*', 'Start / End'): '开始 / 结束', 
    ('*', 'End / Amount'): '结束 / 数量', 
    ('*', 'Start Index'): '开始索引', 
    ('*', 'End Index'): '结束索引', 
    ('*', 'Start Value'): '开始值', 
    ('*', 'End Value'): '结束值', 
    ('*', 'Offsets'): '偏移', 
    ('Operator', 'Noise Falloff'): '噪音衰减',
    ('Operator', 'Index Mask'): '索引遮罩',
    ('*', 'Every Nth'): 'N 次平均',
    ('Operator', 'Object Controller'): '对象控制器',
    ('*', 'Falloff Width'): '衰减宽度',
    ('*', 'Fractal Type'): '分形类型',
    ('*', 'Perturb Type'): '扰动类型',
    ('Operator', 'Create Execution Trigger'): '创建执行触发器',
    ('*', 'Axis Scale'): '轴向缩放',
    ('*', 'Empty Sound'): '无声音',
    ('*', 'Attack'): '击打',
    ('*', 'Index Frequency'): '索引频率',
    ('*', 'Falloff Frequency'): '衰减频率',
    ('*', 'Fade to zero:'): '淡出：',
    ('*', 'Low Frequencies'): '低频',
    ('*', 'High Frequencies'): '高频',
    ('*', 'Smoothing Samples'): '平滑采样',
    ('*', 'Kaiser Beta'): '凯撒贝塔',
    ('*', 'Use Radius for Distance'): '使用距离半径',
    ('*', 'Use Radius for Width'): '使用宽度半径',
    ('Operator', 'Mesh Falloff'): '网格衰减',
    ('*', 'Fill Inside'): '填充内部',
    ('Operator', 'Constant'): '常量',
    ('Operator', 'Custom'): '自定义',
    ('Operator', 'Directional'): '定向',
    ('Operator', 'Point Distance'): '点距离',
    ('Operator', 'Radial'): '径向',
    ('Operator', 'Remap'): '重新映射',
    ('*', 'Transformation Matrix'): '变换矩阵',
    ('Operator', 'Action From Object'): '动作自对象',
    ('Operator', 'Chain Actions'): '链动作',
    ('*', 'Chained Action'): '已链接动作',
    ('Operator', 'Delay Action'): '延迟动作',
    ('Operator', 'Overlay Action'): '叠加动作',
    ('Operator', 'Wiggle Action'): '遥摆动作',
    ('*', 'Path Index'): '路径索引',
    ('Operator', 'Follow Spline Action'): '跟随样条动作',
    ('Operator', 'Object Action Output'): '对象动作输出',
    ('*', 'FCurves'): '斯特里贝克曲线',
    ('Operator', 'Keyframes'): '关键帧',
    ('*', 'Keyframes Frames'): '关键帧帧',
    ('*', 'Keyframes Values'): '关键帧值',
    ('Operator', 'Material Input'): '材质输入',
    ('Operator', 'Object Material Input'): '对象材质输入',
    ('Operator', 'Material Output'): '材质输出',
    ('Operator', 'Cycles Material Output'): 'Cycles 材质输出',
    ('Operator', 'Sound From Sequence'): '来自序列的声音',
    ('Operator', 'Sound Spectrum'): '声音频谱',
    ('*', 'Exponential Rate'): '指数率',
    ('Operator', 'Sequences from Channel'): '来自通道的序列',
    ('Operator', 'Get All Sequences'): '获取全部序列',
    ('Operator', 'Text Sequence Output'): '文本序列输出',
    ('Operator', 'Sequence Info'): '序列信息',
    ('*', 'Final Duration'): '最终持续时间',
    ('*', 'Final Start Frame'): '最终开始帧',
    ('*', 'Final End Frame'): '最终结束帧',
    ('*', 'Total Duration'): '合计持续时间',
    ('*', 'Still Frame Start'): '静止帧开始',
    ('*', 'Still Frame End'): '静止帧结束',
    ('Operator', 'Convert Plane Type'): '转换平面类型',
    ('*', 'Point in Plane'): '平面上的点',
    ('*', 'Matrix to Point/Normal'): '矩阵到点/法向',
    ('*', 'Point/Normal to Matrix'): '点/法向到矩阵',
    ('Operator', 'Point List Normal'): '点列表法向',
    ('*', 'Is Valid'): '有效',
    ('*', 'Point List'): '点列表',
    ('Operator', 'Project Point on Line'): '在线上投影点',
    ('Operator', 'Project Point on Plane'): '在平面上投影点',
    ('Operator', 'Point in Camera Frustrum'): '在相机上投影点',
    ('*', 'Image u'): '图像 U',
    ('*', 'Image v'): '图像 V',
    ('*', 'Z depth'): 'Z 深度',
    ('Operator', 'Intersect Line Line'): '线相交',
    ('*', 'First Line Start'): '第一条线开始点',
    ('*', 'First Line End'): '第一条线结束点',
    ('*', 'Second Line Start'): '第二条线开始点',
    ('*', 'Second Line End'): '第二条线结束点',
    ('*', 'First Nearest Point'): '第一条线最近点',
    ('*', 'Second Nearest Point'): '第二条线最近点',
    ('*', 'First Parameter'): '第一点参量',
    ('*', 'Second Parameter'): '第二点参量',
    ('Operator', 'Intersect Line Plane'): '线与平面相交',
    ('Operator', 'Intersect Line Sphere'): '线与球体相交',
    ('*', 'Sphere Center'): '球体中心',
    ('*', 'First Intersection'): '第一相交点',
    ('*', 'Second Intersection'): '第二相交点',
    ('*', 'Number Of Intersections'): '相交数',
    ('Operator', 'Intersect Plane Plane'): '平面相交',
    ('*', 'Line Direction'): '线方向',
    ('*', 'Line Point'): '线点',
    ('*', 'First Plane Point'): '第一平面点',
    ('*', 'First Plane Normal'): '第一平面法向',
    ('*', 'Second Plane Point'): '第二平面点',
    ('*', 'Second Plane Normal'): '第二平面法向',
    ('Operator', 'Intersect Sphere Plane'): '球体与平面相交',
    ('*', 'Circle Center'): '圆中心',
    ('*', 'Circle Radius'): '圆半径',
    ('Operator', 'Intersect Sphere Sphere'): '球体相交',
    ('*', 'First Sphere Center'): '第一个球体中心',
    ('*', 'First Sphere Radius'): '第一个球体半径',
    ('*', 'Second Sphere Center'): '第二个球体中心',
    ('*', 'Second Sphere Radius'): '第二个球体半径',
    ('*', 'Circle Normal'): '圆法向',
    ('Operator', 'Triangulate BMesh'): '三角化 BMesh',
    ('Operator', 'Construct KDTree'): '构造 KDTree',
    ('Operator', 'Find Nearest'): '查找最近点',
    ('Operator', 'Find Amount'): '查找最近几个点',
    ('Operator', 'Find in Radius'): '查找半径中点',
    ('Operator', 'Construct BVHTree'): '构造 BVHTree',
    ('Operator', 'Ray Cast'): '射线',
    ('*', 'Ray Start'): '射线起点',
    ('*', 'Epsilon'): '小量',
    ('*', 'Hit'): '命中',
    ('*', 'Start in Infinity'): '从无限开始',
    ('*', 'Polygon Index'): '多边形索引',
    ('Operator', 'Is Inside Volume'): '在体积内部',
    ('*', 'Is Inside'): '在内部',
    ('Operator', 'Viewer'): '查看器',
    ('*', 'Display Settings:'): '显示设置：',
    ('*', 'Max Rows'): '最大行数',
    ('*', 'List Settings:'): '列表设置：',
    ('*', 'Output Settings:'): '输出设置：',
    ('Operator', '3D Viewer'): '3D 查看器',
    ('Operator', 'Loop Viewer'): '循环查看器',
    ('*', 'Has to be in a loop'): '需要在循环中',
    ('*', 'Width 1'): '宽度 1',
    ('Operator', 'Interpolation Viewer'): '插值查看器',
    ('Operator', 'Action Viewer'): '动作查看器',
    ('Operator', 'Invoke Subprogram'): '调用子程序',
    ('Operator', 'New Subprogram'): '新增子程序',
    ('*', 'Cache Type'): '缓存类型',
    ('*', 'One Time'): '一次',
    ('*', 'Once per Frame'): '每帧一次',
    ('*', 'Once per Input'): '每个输入一次',
    ('Operator', 'Clear Cache'): '清空缓存',
    ('*', 'Show Cache Options'): '显示缓存选项',
    ('*', 'Subprogram Type'): '子程序类型',
    ('*', 'Subprogram Name'): '子程序名称',
    ('*', 'There are not subprograms yet'): '还没有子程序',
    ('Operator', 'Output Node'): '输出节点',
    ('Operator', 'Loop'): '循环',
    ('*', 'New Iterator'): '新迭代器',
    ('*', 'Iterator Sockets:'): '迭代器插口：',
    ('Operator', 'New Iterator'): '新迭代器',
    ('*', 'New Parameter'): '新参数',
    ('*', 'Parameter Sockets:'): '参数插口：',
    ('Operator', 'New Parameter'): '新参数',
    ('*', 'New Generator Output'): '新生成器输出',
    ('*', 'List Generators:'): '生成器：',
    ('*', 'Hide By Default'): '默认隐藏',
    ('*', 'No vectorization for generic type'): '泛型类型无矢量化',
    ('Operator', 'New Generator'): '新生成器',
    ('Operator', 'New Break Condition'): '新中断条件',
    ('Operator', 'Reassign'): '分配',
    ('Operator', 'Script'): '脚本',
    ('Operator', 'New Output'): '添加输出',
    ('Operator', 'Expression'): '表达式',
    ('Operator', 'Viewport Input'): '视口输入',
    ('*', 'Order Weight'): '排序权重',
    ('*', 'Interactive Mode'): '交互模式',
    ('*', 'Debug Mode'): '调试模式',
    ('*', 'Initialize Missing Outputs'): '初始化缺少的输出',
    ('*', 'Correct Output Types'): '正确的输出类型',
    ('*', 'Input Defaults:'): '输入默认值：',
    ('*', 'Output Defaults:'): '输出默认值：',
    ('*', 'Correct Type'): '正确类型',
    ('*', 'Inline Expression'): '内联表达式',
    ('*', 'Fixed Data Type'): '固定数据类型',
    ('*', 'Modules'): '模块',
    ('Operator', 'Data Interface'): '数据接口',
    ('Operator', 'Frame'): '框',
    ('Operator', 'Reroute'): '改道点',
    ('Operator', 'Toogle ID Key Visibility'): '切换 ID 键可见性',
    ('*', 'dataType'): '数据类型',
    ('*', 'propertyName'): '属性名称',
}