# -*- coding: utf-8 -*-

lang_dict = {
   ('*', 'Node: Animation Nodes') : '節點： 動畫節點編輯器(Animation Nodes)',
   ('*', 'Animation Nodes') : '動畫節點編輯器',
   ('*', 'Node based visual scripting system designed for motion graphics in Blender.') : '基於節點的可視化腳本系統，專為 Blender 中的運動圖形而設計。',
   ('*', 'Animation Nodes Editor') : '動畫節點編輯器',
   ('*', 'This version is still in development.') : '此版本任在開發中',
   ('*', 'Node Colors:') : '節點顏色：',
   ('*', 'Main Network') : '主網絡',
   ('*', 'Invalid Network') : '無效網絡',
   ('*', 'Run Tests') : '運行測試',
   ('*', 'Subprogram Value') : '子程序亮度',
   ('*', 'Subprogram Saturation') : '子程序飽和度',
   ('*', 'Color for all networks that are not in a subprogram') : '非子程序中的所有網絡的顏色',
   ('*', 'Color for networks that stop the execution because they have an error') : '因出現錯誤而停止執行的網絡的顏色',
   ('*', 'Lightness of random subnetwork colors') : '隨機子網顏色的亮度',
   ('*', 'Color intensity of random subnetwork colors') : '隨機子網顏色的強度',
   ('*', 'Enable some print statements') : '啟用一些打印語句',
   ('*', 'Run the test suite when Blender starts') : 'Blender 啟動時運行測試套件',
   ('*', 'How to Uninstall?') : '如何卸載？',
   ('*', 'Animation Node Tree') : '動畫節點樹',
   ('*', 'Auto Execution') : '自動執行',
   ('*', 'Tree Changed') : '樹改變時',
   ('*', 'Frame Changed') : '幀改變時',
   ('*', 'Property Changed') : '屬性改變時',
   ('*', 'Min Time Difference') : '最小時差',
   ('Operator', 'New Trigger') : '添加觸發器',
   ('Operator', 'Remove Auto Execution Trigger') : '刪除自動執行觸發器',
   ('Operator', 'Enable') : '啟用',
   ('Operator', 'Execute Node Tree') : '執行節點樹',
   ('*', 'Details') : '明細',
   ('*', 'Measure execution times of the individual nodes') : '測量各個節點的執行時間',
   ('*', 'Edit Node Labels') : '編輯節點標籤',
   ('*', 'Overview') : '概述',
   ('*', 'Execution Code:') : '執行代碼：',
   ('*', 'Different execution codes can be useful in different contexts') : '不同的執行代碼在不同的上下文中很有用',
   ('*', 'Monitor Execution') : '監視執行',
   ('*', 'Measure Execution Times') : '測量執行時間',
   ('Operator', 'Print') : '打印',
   ('*', 'Print the code of the currently active node') : '打印當前活動節點的代碼',
   ('Operator', 'Write') : '編寫',
   ('*', 'Write the code of the currently active node in a text block') : '在文本塊中寫入當前活動節點的代碼',
   ('Operator', 'Select Area') : '選擇區域',
   ('*', 'Profiling Function') : '分析功能',
   ('*', 'Function') : '功能',
   ('*', 'Execution') : '執行',
   ('*', 'Tree Analysis') : '樹分析',
   ('*', 'Update Everything') : '更新全部',
   ('*', 'Script Generation') : '腳本生成',
   ('*', 'Sort Mode') : '排序模式',
   ('*', 'Amount of Calls') : '調用次數',
   ('*', 'Total Time') : '總時間',
   ('*', 'Cumulative Time') : '累計時間',
   ('*', 'Text Block') : '文本塊',
   ('Operator', 'Profile') : '分析',
   ('*', 'Networks') : '網絡',
   ('*', 'Needed Copies') : '所需副本',
   ('*', 'Use Network Color') : '使用網絡顏色',
   ('*', 'Only subprograms have a custom network color') : '只有子程序具有自定義網絡顏色',
   ('*', 'Advanced Node Settings') : '高級節點設置',
   ('*', 'Has no advanced settings') : '沒有高級設置',
   ('*', 'Viewport Input') : '視口輸入',
   ('*', 'No Viewport Input node.') : '沒有視口輸入節點',
   ('*', 'ID Keys') : 'ID 鍵',
   ('*', 'Initial Transforms') : '初始變換',
   ('Operator', 'From Current Transforms') : '從當前變換',
   ('Operator', 'Sort Objects') : '排序對象',
   ('*', 'Selection Order') : '選中的順序',
   ('Operator', 'New ID Key') : '新增 ID 鍵',
   ('*', 'Number') : '數值',
   ('*', '   There are no subprograms yet') : '   沒有子程序',
   ('Operator', 'Remove Animation Node Tree') : '移除動畫節點樹',
   ('*', 'Remove the active animation node tree') : '移除活動的動畫節點樹',
   ('Operator', 'Integer') : '整數',
   ('Operator', 'Float') : '浮點數',
   ('Operator', 'Integer List') : '整數列表',
   ('Operator', 'Float List') : '浮點數列表',
   ('Operator', 'Integer Range') : '整數範圍序列',
   ('Operator', 'Float Range') : '浮點數範圍序列',
   ('Operator', 'Parse Number') : '解析數值',
   ('Operator', 'Constants') : '常量',
   ('Operator', 'Random') : '隨機',
   ('Operator', 'Wiggle') : '搖擺',
   ('Operator', 'Mix') : '混合',
   ('Operator', 'Map Range') : '範圍映射',
   ('Operator', 'Math') : '運算',
   ('Operator', 'List Math') : '列表運算',
   ('Operator', 'Sort Numbers') : '排序數值',
   ('Operator', 'Clamp') : '鉗制',
   ('Operator', 'Round') : '四捨五入',
   ('Operator', 'Convert Angle') : '角度轉換',
   ('Operator', 'Float to Integer') : '浮點到整數',
   ('Operator', 'Float to Text') : '浮點到文本',
   ('Operator', 'Combine') : '組合',
   ('Operator', 'From Value') : '從值',
   ('Operator', 'List') : '列表',
   ('Operator', 'Noise') : '噪聲',
   ('Operator', 'Distance') : '距離',
   ('Operator', 'Distance to Line') : '到線的距離',
   ('Operator', 'Distance to Plane') : '到面的距離',
   ('Operator', 'Dot Product') : '點乘',
   ('Operator', 'Offset') : '偏移',
   ('Operator', 'Direction to Rotation') : '方向到旋轉',
   ('Operator', 'Rotation to Direction') : '旋轉到方向',
   ('Operator', 'Euler to/from Vector') : '歐拉到/從矢量',
   ('Operator', 'Convert Rotation Types') : '轉換旋轉類型',
   ('Operator', 'Separate Euler') : '分離歐拉',
   ('Operator', 'Combine Euler') : '組合歐拉',
   ('Operator', 'Euler Math') : '歐拉運算',
   ('Operator', 'Euler Mix') : '歐拉混合',
   ('Operator', 'Random Euler') : '隨機歐拉',
   ('Operator', 'Euler Wiggle') : '搖擺歐拉',
   ('Operator', 'Separate Quaternion') : '分離四元數',
   ('Operator', 'Combine Quaternion') : '組合四元數',
   ('Operator', 'Quaternion Math') : '四元數運算',
   ('Operator', 'Quaternion Mix') : '四元數混合',
   ('Operator', 'Random Quaternion') : '隨機四元數',
   ('Operator', 'Quaternion Wiggle') : '搖擺四元數',
   ('Operator', 'Combine Quaternion Rotations') : '組合四元旋轉',
   ('Operator', 'Compose') : '組成',
   ('Operator', 'Decompose') : '分解',
   ('Operator', 'Distribute') : '分發',
   ('Operator', 'Replicate') : '複製',
   ('Operator', 'Axis Rotation') : '軸向旋轉',
   ('Operator', 'Extract Matrix Basis') : '提取矩陣基礎',
   ('Operator', 'Input') : '輸入',
   ('Operator', 'Characters') : '字符',
   ('Operator', 'Convert To Text') : '轉換到文本',
   ('Operator', 'Timecode Generator') : '時間碼生成器',
   ('Operator', 'Change Text Case') : '轉換大小寫',
   ('Operator', 'Reverse') : '反向',
   ('Operator', 'LSystem') : 'L系統',
   ('Operator', 'Decompose Text') : '分解文本',
   ('Operator', 'Block Reader') : '塊讀取器',
   ('Operator', 'Block Writer') : '塊寫入器',
   ('Operator', 'Filter Text Block List') : '過濾文本塊列表',
   ('Operator', 'File Reader') : '文件讀取器',
   ('Operator', 'Sequence Output') : '序列輸出',
   ('*', 'Element') : '元素',
   ('*', 'Start / Step') : '起始 / 步長',
   ('*', 'Start / Stop') : '起始 / 停止',
   ('*', 'Include End Point') : '包括停止',
   ('*', 'List') : '列表',
   ('*', 'Create') : '創建',
   ('*', 'More') : '更多',
   ('*', 'Subprograms') : '子程序',
   ('Operator', 'Search') : '搜索',
   ('*', 'Results') : '結果',
   ('Operator', 'Are you sure?') : '是否確定？',
   ('*', 'Remove unlinked inputs') : '刪除未連接的輸入',
   ('Operator', 'Remove Unlinked Inputs') : '刪除未連接的輸入',
   ('*', 'Sorted Numbers') : '已排序數值',
   ('Operator', 'Time Info') : '時間信息',
   ('Operator', 'Delay') : '延時',
   ('Operator', 'Repeat') : '重複',
   ('Operator', 'New Input') : '添加輸入',
   ('*', 'Create a new input socket') : '添加一個新的輸入端口',
   ('*', 'Node Seed') : '隨機種子',
   ('*', 'Degree') : '度',
   ('*', 'Degree to Radian') : '度到弧度',
   ('*', 'Radian') : '弧度',
   ('*', 'Radian to Degree') : '弧度到度',
   ('*', 'Vectors') : '向量',
   ('*', 'Evolution') : '演變',
   ('*', 'Persistance') : '持續',
   ('*', 'Simplex') : '簡單',
   ('*', 'Perlin') : '柏林',
   ('*', 'Cellular') : '蜂窩',
   ('*', 'Cell Value') : '格值',
   ('*', 'Clamp Factor') : '鉗制因子',
   ('*', 'Clamp factor between 0 and 1') : '限制結果為 0 到 1 的範圍內',
   ('*', 'Line Start') : '線起點',
   ('*', 'Parameter') : '參數',
   ('*', 'Signed Distance') : '距離',
   ('*', 'Rotation Difference') : '旋轉差異',
   ('*', 'Vector List') : '向量列表',
   ('*', 'Matrix Rotation') : '矩陣旋轉',
   ('*', 'Euler to Vector') : '歐拉到矢量',
   ('*', 'Vector to Euler') : '矢量到歐拉',
   ('*', 'Use Degree') : '使用度',
   ('*', 'Matrix to Euler') : '矩陣到歐拉',
   ('*', 'Euler to Matrix') : '歐拉到矩陣',
   ('*', 'Quaternion to Euler') : '四元數到歐拉',
   ('*', 'Euler to Quaternion') : '歐拉到四元數',
   ('*', 'Quaternion to Matrix') : '四元數到矩陣',
   ('*', 'Matrix to Quaternion') : '矩陣到四元數',
   ('*', 'Quaternion to Axis Angle') : '四元數到軸角度',
   ('*', 'Axis Angle to Quaternion') : '軸角度到四元數',
   ('*', 'Matrices') : '矩陣',
   ('*', 'X Divisions') : 'X 分段',
   ('*', 'Y Divisions') : 'Y 分段',
   ('*', 'Z Divisions') : 'Z 分段',
   ('*', 'X Distance') : 'X 距離',
   ('*', 'Y Distance') : 'Y 距離',
   ('*', 'Z Distance') : 'Z 距離',
   ('*', 'Start Radius') : '起始半徑',
   ('*', 'End Radius') : '結束半徑',
   ('*', 'Start Size') : '起始尺寸',
   ('*', 'End Size') : '結束尺寸',
   ('*', 'Start Angle') : '起始角度',
   ('*', 'End Angle') : '結束角度',
   ('*', 'Transformations') : '變換',
   ('*', 'Inverted Matrix') : '倒置矩陣',
   ('*', 'Loc/Rot/Scale') : '位置/旋轉/縮放',
   ('*', 'Characters') : '字符',
   ('*', 'Special') : '特殊',
   ('*', 'Line Break') : '斷行',
   ('*', 'Text List') : '文本列表',
   ('*', 'Words') : '詞',
   ('*', 'Regular Expression') : '正則表達式',
   ('*', 'Keep Delimiters') : '保留分隔符',
   ('*', 'Split By') : '分隔符',
   ('*', 'N Characters') : 'N 個字符',
   ('*', 'Separator') : '分隔符',
   ('*', 'To Upper Case') : '大寫',
   ('*', 'To Lower Case') : '小寫',
   ('*', 'To Title Case') : '詞首大寫',
   ('*', 'Capitalize Phrase') : '大寫短語',
   ('*', 'Capitalize Words') : '大寫詞',
   ('*', 'at Start') : '在開始',
   ('*', 'at End') : '在結尾',
   ('*', 'Repeats') : '重複',
   ('*', 'Axiom') : '公理化',
   ('*', 'Rules') : '規則',
   ('*', 'Edge Widths') : '邊緣寬度',
   ('*', 'Symbols') : '符號',
   ('*', 'Generations') : '代',
   ('*', 'Scale Width') : '縮放寬度',
   ('*', 'Scale Step Size') : '縮放步尺寸',
   ('*', 'Only Partial Moves') : '僅部分移動',
   ('*', 'Character') : '字符',
   ('*', 'Word') : '單詞',
   ('*', 'BFont is not Supported!') : '不支持 BFont!',
   ('Operator', 'Choose Path') : '選擇路徑',
   ('*', 'Text Block List') : '文本塊列表',
   ('*', 'Starts With') : '開始是',
   ('*', 'Ends With') : '結尾是',
   ('*', 'All Objects with names starting with') : '所有特定名稱開始的對象',
   ('*', 'All Objects with names ending with') : '所有特定名稱結尾的對象',
   ('*', 'Path does not exist') : '路徑不存在',
   ('Operator', 'Character Property') : '字符屬性',
   ('Operator', 'Object Separate') : '對象分離',
   ('*', 'Text Objects') : '文本對象',
   ('Operator', 'Update') : '更新',
   ('*', 'Origin to Center of Mass') : '原點 -> 質心點',
   ('*', 'Origin to Cursor') : '原點 -> 3D 浮標',
   ('Operator', 'Object Output') : '對象輸出',
   ('*', 'Horizontal Align') : '橫向對齊',
   ('*', 'Vertical Align') : '垂直對齊',
   ('*', 'Bold Font') : 'Bold 字體',
   ('*', 'Italic Font') : 'Italic 字體',
   ('*', 'Bold Italic Font') : 'Bold Italic 字體',
   ('Operator', 'Boolean') : '布爾',
   ('Operator', 'Compare') : '比較',
   ('Operator', 'Switch') : '切換',
   ('*', 'Condition') : '條件',
   ('*', 'If True') : '為真',
   ('*', 'If False') : '否則',
   ('Operator', 'Logic') : '邏輯',
   ('*', 'A and B') : 'A 和 B',
   ('*', 'not (A and B)') : '非(A 和 B)',
   ('*', 'A or B') : 'A 或 B',
   ('*', 'not (A or B)') : '非(A 或 B)',
   ('*', 'A xor B') : 'A 異同 B',
   ('Operator', 'List Logic') : '列表邏輯',
   ('*', 'Boolean List') : '布爾列表',
   ('*', 'All True') : '全為真',
   ('*', 'All False') : '全為假',
   ('*', 'Not All True') : '任意假',
   ('*', 'Not All False') : '任意真',
   ('Operator', 'Random Boolean') : '隨機布爾',
   ('Operator', 'Choose Color') : '選擇顏色',
   ('*', 'Alpha') : '不透明度',
   ('Operator', 'Combine Color') : '組合顏色',
   ('Operator', 'Separate Color') : '分離顏色',
   ('Operator', 'Set Vertex Color') : '設置頂點顏色',
   ('*', 'Vertex Color Index') : '頂點顏色索引',
   ('Operator', 'Vector') : '向量',
   ('Operator', 'Action') : '動作',
   ('Operator', 'Collection') : '集合',
   ('Operator', 'Edge Indices') : '邊索引',
   ('Operator', 'Euler') : '歐拉',
   ('Operator', 'FCurve') : '斯特里貝克曲線',
   ('Operator', 'Falloff') : '衰減',
   ('Operator', 'Font') : '字體',
   ('Operator', 'Generic') : '通用',
   ('Operator', 'Interpolation') : '插值',
   ('Operator', 'Material') : '材質',
   ('Operator', 'Matrix') : '矩陣',
   ('Operator', 'Mesh') : '網格',
   ('Operator', 'NlaStrip') : '恩拉斯特里普',
   ('Operator', 'Change Type') : '更改類型',
   ('Operator', 'Particle System') : '粒子系統',
   ('Operator', 'Polygon Indices') : '多邊形索引',
   ('Operator', 'Quaternion') : '四元數',
   ('Operator', 'Shape Key') : '形狀鍵',
   ('Operator', 'Spline') : '樣條',
   ('Operator', 'Struct') : '結構',
   ('Operator', 'Text Block') : '文本塊',
   ('Operator', 'Vector 2D') : '2D 向量',
   ('*', 'Hide Inputs') : '隱藏輸入',
   ('*', 'Action List') : '行為列表',
   ('*', 'Float List') : '浮點列表',
   ('*', 'Falloff List') : '衰減列表',
   ('*', 'Struct List') : '結構列表',
   ('*', 'Shape Key List') : '形狀鍵列表',
   ('*', 'Scene List') : '場景列表',
   ('*', 'Integer List') : '整數列表',
   ('*', 'Quaternion List') : '四元數列表',
   ('*', 'Spline List') : '樣條列表',
   ('*', 'Polygon Indices List') : '多邊形索引列表',
   ('Operator', 'Get Element') : '獲取元素',
   ('Operator', 'Get Random Elements') : '隨機獲取元素',
   ('*', 'Multiple') : '多個',
   ('Operator', 'Search Element') : '搜索元素',
   ('*', 'First Index') : '第一個索引',
   ('*', 'All Indices') : '全部索引',
   ('*', 'Occurrences') : '事件',
   ('Operator', 'Set Element') : '設置元素',
   ('Operator', 'Remove Element') : '移除元素',
   ('*', 'First Occurrence') : '第一次觸發',
   ('*', 'All Occurrences') : '全部觸發',
   ('Operator', 'Get Length') : '獲取長度',
   ('Operator', 'Shuffle') : '洗牌',
   ('*', 'Shuffled List') : '已洗牌列表',
   ('*', 'Reversed List') : '已反向列表',
   ('Operator', 'Slice') : '分割',
   ('Operator', 'Shift') : '位移',
   ('*', 'Shifted List') : '已位移列表',
   ('*', 'Ping Pong') : '乒乓',
   ('*', 'Below Length') : '長度以下',
   ('*', 'Above Length') : '長度以上',
   ('Operator', 'Repeat Elements') : '重複元素',
   ('*', 'Repeated List') : '已重複列表',
   ('Operator', 'List Boolean Operations') : '列表布爾操作',
   ('*', 'Intersection') : '交集',
   ('*', 'Symmetric Difference') : '對稱差異',
   ('*', 'List 1') : '列表 1',
   ('*', 'List 2') : '列表 2',
   ('Operator', 'Set Struct Elements') : '設置結構元素',
   ('*', 'Struct') : '結構',
   ('*', 'New Input') : '新建輸入',
   ('Operator', 'Get Struct Elements') : '獲取結構元素',
   ('*', 'New Output') : '新建輸出',
   ('Operator', 'Get Struct List Elements') : '獲取結構列表元素',
   ('Operator', 'Filter Object List') : '過濾對象列表',
   ('*', 'Object List') : '對象列表',
   ('Operator', 'Collection Info') : '集合信息',
   ('Operator', 'Transforms Input') : '變換輸入',
   ('Operator', 'Mesh Input') : '網絡輸入',
   ('*', 'Vertex Locations') : '頂點位置',
   ('*', 'Polygon Centers') : '多邊形中心',
   ('*', 'Use World Space') : '使用世界空間',
   ('*', 'Use Modifiers') : '使用修改器',
   ('*', 'Load UVs') : '加載 UV',
   ('*', 'Load Vertex Colors') : '加載頂點顏色',
   ('*', 'Vertex Normals') : '頂點法向',
   ('*', 'Polygon Normals') : '多邊形法向',
   ('*', 'Edge Indices') : '邊索引',
   ('*', 'Polygon Indices') : '多邊形索引',
   ('*', 'Local Polygon Areas') : '本地多邊形面積',
   ('*', 'Material Indices') : '材質索引',
   ('*', 'Mesh Name') : '網格名稱',
   ('Operator', 'Transforms Output') : '變換輸出',
   ('Operator', 'Matrix Input') : '矩陣輸入',
   ('Operator', 'Matrix Output') : '矩陣輸出',
   ('Operator', 'Attribute Input') : '屬性輸入',
   ('Operator', 'Attribute Output') : '屬性輸出',
   ('Operator', 'Color Output') : '顏色輸出',
   ('Operator', 'Data Path Output') : '數據路徑輸出',
   ('*', 'Array Index') : '數組索引',
   ('Operator', 'Visibility Input') : '可見性輸入',
   ('*', 'Hide Viewport') : '視圖隱藏',
   ('*', 'Hide Render') : '渲染隱藏',
   ('*', 'Show Axis') : '軸向',
   ('*', 'Show In Front') : '在前面',
   ('Operator', 'Visibility Output') : '可見性輸出',
   ('Operator', 'Shape Keys from Object') : '從對象的形狀鍵',
   ('Operator', 'Shape Key Output') : '形狀鍵輸出',
   ('Operator', 'ID Key') : 'ID 鍵',
   ('Operator', 'Choose ID Key') : '選擇 ID 鍵',
   ('Operator', 'Copy Data') : '複製數據',
   ('*', 'From') : '從',
   ('*', 'Deep Copy') : '深拷貝',
   ('Operator', 'Set Keyframes') : '設置關鍵幀',
   ('*', 'Set Keyframe') : '設置關鍵幀',
   ('*', 'Remove Unwanted') : '刪除不需要的',
   ('Operator', 'Armature Info') : '骨架信息',
   ('*', 'Directions') : '方向',
   ('*', 'Lengths') : '長度',
   ('*', 'Rest') : '休息',
   ('*', 'Utils') : '其它',
   ('Operator', 'Update Matrices') : '更新矩陣',
   ('Operator', 'Reset Transformations') : '復位變換',
   ('Operator', 'Copy Transformations') : '複製變換',
   ('Operator', 'Get Selected Objects') : '獲取選中的對象',
   ('Operator', 'Get Active Camera') : '獲取活動相機',
   ('*', 'Disabled During Rendering') : '渲染期間禁用',
   ('*', 'Active Camera') : '活動相機',
   ('Operator', 'Instancer') : '實例化',
   ('*', 'Copy from Source') : '從源複製',
   ('*', 'Copy Full Object') : '複製整個對象',
   ('*', 'Instances') : '實例數',
   ('Operator', 'Collection Operations') : '集合操作',
   ('Operator', 'Collection By Name') : '命名的集合',
   ('Operator', 'Create Collection List') : '創建集合列表',
   ('Operator', 'From Selection') : '從所選',
   ('Operator', 'Combine Collection Lists') : '組合集合列表',
   ('Operator', 'Filter Collection List') : '過濾集合列表',
   ('*', 'Collection List') : '集合列表',
   ('Operator', 'Mesh Info') : '網格信息',
   ('*', 'UV Map Names') : 'UV 映射名稱',
   ('*', 'Vertex Color Layers') : '頂點顏色層',
   ('Operator', 'Get Bounding Box') : '獲取邊界框',
   ('Operator', 'Combine Mesh') : '組合網格',
   ('Operator', 'Mesh From Spline') : '來自樣條的網格',
   ('*', 'Use Custom Shape') : '使用自定義形狀',
   ('*', 'Spline Resolution') : '樣條分辨率',
   ('*', 'Cap Ends') : '閉合結束',
   ('*', 'Mesh Data') : '網格數據',
   ('Operator', 'Vertex Group Input') : '頂點組輸入',
   ('Operator', 'Set Vertex Weight') : '設置頂點權重',
   ('Operator', 'Get Vertex Color Layer') : '獲取頂點顏色層',
   ('Operator', 'Insert Vertex Color Layer') : '插入頂點顏色層',
   ('Operator', 'Set Bevel Vertex Weight') : '設置頂點倒角權重',
   ('Operator', 'Set Bevel Edge Weight') : '設置邊倒角權重',
   ('Operator', 'Set Edge Crease') : '設置邊摺痕',
   ('Operator', 'Get UV Map') : '獲取 UV 貼圖',
   ('*', 'Positions') : '位置',
   ('Operator', 'Insert UV Map') : '插入 UV 貼圖',
   ('Operator', 'Set UV Map') : '設置 UV 貼圖',
   ('*', 'UV Map Index') : 'UV 貼圖索引',
   ('Operator', 'Set Polygon Material Index') : '設置多邊形材質索引',
   ('Operator', 'Offset Polygons') : '偏移多邊形',
   ('Operator', 'Separate Polygons') : '分離多邊形',
   ('Operator', 'Extract Polygon Transforms') : '提取多邊形變換',
   ('*', 'Inverted Transforms') : '反向變換',
   ('Operator', 'Offset Vertices') : '偏移頂點',
   ('Operator', 'Transform Mesh') : '變換網格',
   ('Operator', 'Triangulate Mesh') : '三角測量網格',
   ('*', 'Use Advanced Method') : '使用高級方法',
   ('*', 'Generators') : '生成器',
   ('*', 'Start-End') : '起始點到結束點',
   ('*', 'Merge Start End') : '閉合',
   ('*', 'Merge Center') : '合併中心',
   ('*', 'Radial Loops') : '徑向環',
   ('*', 'Inner Loops') : '內部循環',
   ('*', 'Inner Radius') : '內部半徑',
   ('*', 'Outer Radius') : '外部半徑',
   ('Operator', 'Unity Triangle') : '等邊三角',
   ('*', 'Regular Polygons') : '常規多邊形',
   ('Operator', 'Regular Pentagon') : '五邊形',
   ('Operator', 'Regular Hexagon') : '六邊形',
   ('Operator', 'Regular Heptagon') : '七邊形',
   ('Operator', 'Regular Octagon') : '八邊形',
   ('Operator', 'Find Close Points') : '查找最近點',
   ('*', 'Distances') : '距離',
   ('Operator', 'Edge to Tube') : '邊到管道',
   ('Operator', 'Scatter Points') : '散點',
   ('Operator', 'Create Edges') : '創建邊',
   ('*', 'Edge Indices List') : '邊索引列表',
   ('*', 'Edge Starts') : '邊開始',
   ('*', 'Edge Ends') : '邊結束',
   ('Operator', 'Create Edge Indices') : '創建邊索引',
   ('*', 'Index 1') : '索引 1',
   ('*', 'Index 2') : '索引 2',
   ('Operator', 'Create Polygon Indices') : '創建多邊形索引',
   ('*', 'Vertex Amount') : '頂點數',
   ('Operator', 'Edges of Polygons') : '多邊形的邊',
   ('Operator', 'Edge Info') : '邊信息',
   ('Operator', 'Get Linked Vertices') : '獲取連接的頂點',
   ('*', 'Vextex Index') : '頂點索引',
   ('Operator', 'Mesh List') : '網格列表',
   ('*', 'Mesh List') : '網格列表',
   ('Operator', 'Join Mesh List') : '連接網格列表',
   ('Operator', 'BMesh Mesh') : 'BMesh 網格',
   ('Operator', 'BMesh from Mesh') : '網格到 BMesh',
   ('Operator', 'BMesh from Object') : '對象到 BMesh',
   ('*', 'Use Deform Modifiers') : '使用變形修改器',
   ('*', 'Dissolve Boundries') : '溶解邊界',
   ('Operator', 'Invert Normals') : '翻轉法向',
   ('Operator', 'Shade Object Smooth') : '平滑著色',
   ('*', 'Is Used') : '是否使用',
   ('Operator', 'Get from Object') : '取自對象',
   ('Operator', 'Create from Points') : '創建自點',
   ('*', 'Left Handles') : '左控制柄',
   ('*', 'Right Handles') : '右控制柄',
   ('Operator', 'Create from Edges') : '創建自線段',
   ('*', 'Spline Per Edge') : '每個邊的樣條',
   ('*', 'Spline Per Branch') : '每個分支的樣條',
   ('*', 'Radius per Edge') : '每個邊的半徑',
   ('*', 'Radius per Vertex') : '每個頂點的半徑',
   ('Operator', 'Create from Stroke') : '創建自筆刷',
   ('Operator', 'Append Point') : '增加點',
   ('*', 'Bezier Point') : '貝塞爾點',
   ('Operator', 'Set Radius') : '設置半徑',
   ('Operator', 'Make Cyclic') : '使循環',
   ('Operator', 'Smooth Bezier') : '平滑貝塞爾',
   ('Operator', 'Tilt Spline') : '傾斜樣條',
   ('Operator', 'Change Direction') : '改變方向',
   ('Operator', 'Offset Spline') : '偏移樣條',
   ('Operator', 'Info') : '信息',
   ('*', 'Radii') : '半徑',
   ('*', 'Tilts') : '傾斜',
   ('*', 'Point Amount') : '點數量',
   ('Operator', 'Evaluate') : '評估',
   ('Operator', 'Project') : '投影',
   ('*', 'Extended') : '擴展',
   ('Operator', 'Loft') : '放樣',
   ('*', 'Spline Samples') : '樣條採樣',
   ('Operator', 'Revolve') : '圍繞',
   ('*', 'Surface Samples') : '表面採樣',
   ('Operator', 'Object Input') : '對象輸入',
   ('Operator', 'Layer Info') : '層信息',
   ('Operator', 'Frame Info') : '幀信息',
   ('Operator', 'Stroke Info') : '筆刷信息',
   ('*', 'Frame Index') : '幀索引',
   ('*', 'Pressures') : '壓力',
   ('*', 'Vertex Color Fill') : '頂點顏色填充',
   ('*', 'UV-Rotations') : 'UV 旋轉',
   ('*', 'Start Cap Mode') : '起始端模式',
   ('*', 'End Cap Mode') : '結束端模式',
   ('Operator', 'Set Layer Attributes') : '設置圖層屬性',
   ('*', 'Invert Mask Layer') : '反轉遮罩層',
   ('Operator', 'Replicate Layer') : '複製層',
   ('*', 'Offset Frame') : '偏移幀',
   ('Operator', 'Transform Layer') : '變換圖層',
   ('Operator', 'Offset Layer Frames') : '偏移圖層幀',
   ('Operator', 'Set Stroke Attributes') : '設置畫筆屬性',
   ('Operator', 'Replicate Stroke') : '複製畫筆',
   ('Operator', 'Transform Stroke') : '變換畫筆',
   ('Operator', 'Offset Stroke') : '偏移畫筆',
   ('*', 'UVRotation') : 'UV 旋轉',
   ('*', 'UV-Rotation') : 'UV 旋轉',
   ('Operator', 'Change Stroke Direction') : '更改畫筆方向',
   ('Operator', 'Stroke From Points') : '畫筆自點',
   ('Operator', 'Stroke From Spline') : '畫筆自樣條線',
   ('Operator', 'Frame From Strokes') : '畫筆到幀',
   ('Operator', 'Layer From Frames') : '幀到圖層',
   ('Operator', 'GP Material Output') : '蠟筆材質輸出',
   ('Operator', 'Object Material Output') : '對象材質輸出',
   ('Operator', 'From Object') : '來自對象',
   ('Operator', 'Particles Data') : '粒子數據',
   ('Operator', 'Hair Data') : '頭髮數據',
   ('*', 'Stroke Draw Mode') : '筆畫繪製模式',
   ('*', 'Hair Splines') : '頭髮樣條線',
   ('*', 'Velocities') : '速度',
   ('*', 'Sizes') : '尺寸',
   ('*', 'Birth Times') : '出生時間',
   ('*', 'Die Times') : '消亡時間',
   ('*', 'Rate') : '速率',
   ('Operator', 'Animate Matrix') : '矩陣動畫',
   ('Operator', 'Animate Vector') : '向量動畫',
   ('Operator', 'Animate Float') : '浮點動畫',
   ('Operator', 'Animate Color') : '顏色動畫',
   ('Operator', 'Animate Euler') : '歐拉動畫',
   ('Operator', 'Animate Quaternion') : '四元數動畫',
   ('Operator', 'Mix Matrix List') : '混合矩陣列表',
   ('Operator', 'Mix Vector List') : '混合向量列表',
   ('Operator', 'Mix Float List') : '混合浮點列表',
   ('Operator', 'Mix Color List') : '混合顏色列表',
   ('Operator', 'Mix Euler List') : '混合歐拉列表',
   ('Operator', 'Mix Quaternion List') : '混合四元數列表',
   ('Operator', 'Construct') : '構建',
   ('Operator', 'From Curve') : '從曲線',
   ('Operator', 'From FCurve') : '從斯特里貝克曲線',
   ('*', 'Matrix List') : '矩陣列表',
   ('*', 'Cache Interpolation') : '緩存插值',
   ('Operator', 'Reset End Points') : '重置結束點',
   ('*', 'FCurve') : '斯特里貝克曲線',
   ('Operator', 'Mirror Interpolation') : '鏡像插值',
   ('*', 'Chain') : '鏈',
   ('*', 'Input Min') : '輸入最小值',
   ('*', 'Input Max') : '輸入最大值',
   ('*', 'Output Min') : '輸出最小值',
   ('*', 'Output Max') : '輸出最大值',
   ('*', 'Start / Amount') : '開始 / 數量',
   ('*', 'Start / End') : '開始 / 結束',
   ('*', 'End / Amount') : '結束 / 數量',
   ('*', 'Start Index') : '開始索引',
   ('*', 'End Index') : '結束索引',
   ('*', 'Start Value') : '開始值',
   ('*', 'End Value') : '結束值',
   ('*', 'Offsets') : '偏移',
   ('Operator', 'Noise Falloff') : '噪音衰減',
   ('Operator', 'Index Mask') : '索引遮罩',
   ('*', 'Every Nth') : 'N 次平均',
   ('Operator', 'Object Controller') : '對象控制器',
   ('*', 'Falloff Width') : '衰減寬度',
   ('*', 'Fractal Type') : '分形類型',
   ('*', 'Perturb Type') : '擾動類型',
   ('Operator', 'Create Execution Trigger') : '創建執行觸發器',
   ('*', 'Axis Scale') : '軸向縮放',
   ('*', 'Empty Sound') : '無聲音',
   ('*', 'Attack') : '擊打',
   ('*', 'Index Frequency') : '索引頻率',
   ('*', 'Falloff Frequency') : '衰減頻率',
   ('*', 'Fade to zero:') : '淡出：',
   ('*', 'Low Frequencies') : '低頻',
   ('*', 'High Frequencies') : '高頻',
   ('*', 'Smoothing Samples') : '平滑採樣',
   ('*', 'Kaiser Beta') : '凱撒貝塔',
   ('*', 'Use Radius for Distance') : '使用距離半徑',
   ('*', 'Use Radius for Width') : '使用寬度半徑',
   ('Operator', 'Mesh Falloff') : '網格衰減',
   ('*', 'Fill Inside') : '填充內部',
   ('Operator', 'Constant') : '常量',
   ('Operator', 'Custom') : '自定義',
   ('Operator', 'Directional') : '定向',
   ('Operator', 'Point Distance') : '點距離',
   ('Operator', 'Radial') : '徑向',
   ('Operator', 'Remap') : '重新映射',
   ('*', 'Transformation Matrix') : '變換矩陣',
   ('Operator', 'Action From Object') : '動作自對象',
   ('Operator', 'Chain Actions') : '鏈動作',
   ('*', 'Chained Action') : '已鏈接動作',
   ('Operator', 'Delay Action') : '延遲動作',
   ('Operator', 'Overlay Action') : '疊加動作',
   ('Operator', 'Wiggle Action') : '遙擺動作',
   ('*', 'Path Index') : '路徑索引',
   ('Operator', 'Follow Spline Action') : '跟隨樣條動作',
   ('Operator', 'Object Action Output') : '對象動作輸出',
   ('*', 'FCurves') : '斯特里貝克曲線',
   ('Operator', 'Keyframes') : '關鍵幀',
   ('*', 'Keyframes Frames') : '關鍵幀幀',
   ('*', 'Keyframes Values') : '關鍵幀值',
   ('Operator', 'Material Input') : '材質輸入',
   ('Operator', 'Object Material Input') : '對象材質輸入',
   ('Operator', 'Material Output') : '材質輸出',
   ('Operator', 'Cycles Material Output') : 'Cycles 材質輸出',
   ('Operator', 'Sound From Sequence') : '來自序列的聲音',
   ('Operator', 'Sound Spectrum') : '聲音頻譜',
   ('*', 'Exponential Rate') : '指數率',
   ('Operator', 'Sequences from Channel') : '來自通道的序列',
   ('Operator', 'Get All Sequences') : '獲取全部序列',
   ('Operator', 'Text Sequence Output') : '文本序列輸出',
   ('Operator', 'Sequence Info') : '序列信息',
   ('*', 'Final Duration') : '最終持續時間',
   ('*', 'Final Start Frame') : '最終開始幀',
   ('*', 'Final End Frame') : '最終結束幀',
   ('*', 'Total Duration') : '合計持續時間',
   ('*', 'Still Frame Start') : '靜止幀開始',
   ('*', 'Still Frame End') : '靜止幀結束',
   ('Operator', 'Convert Plane Type') : '轉換平面類型',
   ('*', 'Point in Plane') : '平面上的點',
   ('*', 'Matrix to Point/Normal') : '矩陣到點/法向',
   ('*', 'Point/Normal to Matrix') : '點/法向到矩陣',
   ('Operator', 'Point List Normal') : '點列表法向',
   ('*', 'Is Valid') : '有效',
   ('*', 'Point List') : '點列表',
   ('Operator', 'Project Point on Line') : '在線上投影點',
   ('Operator', 'Project Point on Plane') : '在平面上投影點',
   ('Operator', 'Point in Camera Frustrum') : '在相機上投影點',
   ('*', 'Image u') : '圖像 U',
   ('*', 'Image v') : '圖像 V',
   ('*', 'Z depth') : 'Z 深度',
   ('Operator', 'Intersect Line Line') : '線相交',
   ('*', 'First Line Start') : '第一條線開始點',
   ('*', 'First Line End') : '第一條線結束點',
   ('*', 'Second Line Start') : '第二條線開始點',
   ('*', 'Second Line End') : '第二條線結束點',
   ('*', 'First Nearest Point') : '第一條線最近點',
   ('*', 'Second Nearest Point') : '第二條線最近點',
   ('*', 'First Parameter') : '第一點參量',
   ('*', 'Second Parameter') : '第二點參量',
   ('Operator', 'Intersect Line Plane') : '線與平面相交',
   ('Operator', 'Intersect Line Sphere') : '線與球體相交',
   ('*', 'Sphere Center') : '球體中心',
   ('*', 'First Intersection') : '第一相交點',
   ('*', 'Second Intersection') : '第二相交點',
   ('*', 'Number Of Intersections') : '相交數',
   ('Operator', 'Intersect Plane Plane') : '平面相交',
   ('*', 'Line Direction') : '線方向',
   ('*', 'Line Point') : '線點',
   ('*', 'First Plane Point') : '第一平面點',
   ('*', 'First Plane Normal') : '第一平面法向',
   ('*', 'Second Plane Point') : '第二平面點',
   ('*', 'Second Plane Normal') : '第二平面法向',
   ('Operator', 'Intersect Sphere Plane') : '球體與平面相交',
   ('*', 'Circle Center') : '圓中心',
   ('*', 'Circle Radius') : '圓半徑',
   ('Operator', 'Intersect Sphere Sphere') : '球體相交',
   ('*', 'First Sphere Center') : '第一個球體中心',
   ('*', 'First Sphere Radius') : '第一個球體半徑',
   ('*', 'Second Sphere Center') : '第二個球體中心',
   ('*', 'Second Sphere Radius') : '第二個球體半徑',
   ('*', 'Circle Normal') : '圓法向',
   ('Operator', 'Triangulate BMesh') : '三角化 BMesh',
   ('Operator', 'Construct KDTree') : '構造 KDTree',
   ('Operator', 'Find Nearest') : '查找最近點',
   ('Operator', 'Find Amount') : '查找最近幾個點',
   ('Operator', 'Find in Radius') : '查找半徑中點',
   ('Operator', 'Construct BVHTree') : '構造 BVHTree',
   ('Operator', 'Ray Cast') : '射線',
   ('*', 'Ray Start') : '射線起點',
   ('*', 'Epsilon') : '小量',
   ('*', 'Hit') : '命中',
   ('*', 'Start in Infinity') : '從無限開始',
   ('*', 'Polygon Index') : '多邊形索引',
   ('Operator', 'Is Inside Volume') : '在體積內部',
   ('*', 'Is Inside') : '在內部',
   ('Operator', 'Viewer') : '查看器',
   ('*', 'Display Settings:') : '顯示設置：',
   ('*', 'Max Rows') : '最大行數',
   ('*', 'List Settings:') : '列表設置：',
   ('*', 'Output Settings:') : '輸出設置：',
   ('Operator', '3D Viewer') : '3D 查看器',
   ('Operator', 'Loop Viewer') : '循環查看器',
   ('*', 'Has to be in a loop') : '需要在循環中',
   ('*', 'Width 1') : '寬度 1',
   ('Operator', 'Interpolation Viewer') : '插值查看器',
   ('Operator', 'Action Viewer') : '動作查看器',
   ('Operator', 'Invoke Subprogram') : '調用子程序',
   ('Operator', 'New Subprogram') : '新增子程序',
   ('*', 'Cache Type') : '緩存類型',
   ('*', 'One Time') : '一次',
   ('*', 'Once per Frame') : '每幀一次',
   ('*', 'Once per Input') : '每個輸入一次',
   ('Operator', 'Clear Cache') : '清空緩存',
   ('*', 'Show Cache Options') : '顯示緩存選項',
   ('*', 'Subprogram Type') : '子程序類型',
   ('*', 'Subprogram Name') : '子程序名稱',
   ('*', 'There are not subprograms yet') : '還沒有子程序',
   ('Operator', 'Output Node') : '輸出節點',
   ('Operator', 'Loop') : '循環',
   ('*', 'New Iterator') : '新迭代器',
   ('*', 'Iterator Sockets:') : '迭代器插口：',
   ('Operator', 'New Iterator') : '新迭代器',
   ('*', 'New Parameter') : '新參數',
   ('*', 'Parameter Sockets:') : '參數插口：',
   ('Operator', 'New Parameter') : '新參數',
   ('*', 'New Generator Output') : '新生成器輸出',
   ('*', 'List Generators:') : '生成器：',
   ('*', 'Hide By Default') : '默認隱藏',
   ('*', 'No vectorization for generic type') : '泛型類型無矢量化',
   ('Operator', 'New Generator') : '新生成器',
   ('Operator', 'New Break Condition') : '新中斷條件',
   ('Operator', 'Reassign') : '分配',
   ('Operator', 'Script') : '腳本',
   ('Operator', 'New Output') : '添加輸出',
   ('Operator', 'Expression') : '表達式',
   ('Operator', 'Viewport Input') : '視口輸入',
   ('*', 'Order Weight') : '排序權重',
   ('*', 'Interactive Mode') : '交互模式',
   ('*', 'Debug Mode') : '調試模式',
   ('*', 'Initialize Missing Outputs') : '初始化缺少的輸出',
   ('*', 'Correct Output Types') : '正確的輸出類型',
   ('*', 'Input Defaults:') : '輸入默認值：',
   ('*', 'Output Defaults:') : '輸出默認值：',
   ('*', 'Correct Type') : '正確類型',
   ('*', 'Inline Expression') : '內聯表達式',
   ('*', 'Fixed Data Type') : '固定數據類型',
   ('*', 'Modules') : '模塊',
   ('Operator', 'Data Interface') : '數據接口',
   ('Operator', 'Frame') : '框',
   ('Operator', 'Reroute') : '改道點',
   ('Operator', 'Toogle ID Key Visibility') : '切換 ID 鍵可見性',
   ('*', 'dataType') : '數據類型',
   ('*', 'propertyName') : '屬性名稱',
}