lang_dict = {
    ('*', 'Extra Objects'): '额外对象',
    ('*', 'Add Mesh: Extra Objects'): '添加网格：额外对象',
    ('*', 'Add extra mesh object types'): '添加额外网格对象类型',

    ('Operator', 'Rock Generator'): '岩石生成器',
    ('Operator', 'Add Rocks'): '添加岩石',
    ('*', 'Number of rocks'): '岩石数量',
    ('*', 'X scale'): 'X 轴缩放',
    ('*', 'X skew'): 'X 轴斜度',
    ('*', 'Y scale'): 'Y 轴缩放',
    ('*', 'Y skew'): 'Y 轴斜度',
    ('*', 'Z scale'): 'Z 轴缩放',
    ('*', 'Z skew'): 'Z 轴斜度',
    ('*', 'Scale displace textures'): '缩放置换纹理',
    ('*', 'Detail level'): '细节级别',
    ('*', 'Display Detail'): '显示细节',
    ('*', 'Smooth Factor'): '平滑因子',
    ('*', 'Generate Rocks'): '生成岩石',
    ('*', 'Use a random seed'): '使用随机种子',
    ('*', 'User seed'): '用户随机种子',
    ('*', 'Scaling Factor'): '缩放因子',

    ('*', 'Single Vert'): '单个点',
    ('Operator', 'Add Single Vert'): '添加单个点',
    ('*', 'Add a Single Vertice to Edit Mode'): '添加单个点并进入编辑模式',
    ('Operator', 'Object Origin Only'): '仅对象原点',
    ('*', 'Add an Object Origin to Edit Mode'): '添加对象原点进入编辑模式',
    ('Operator', 'Origin & Vert Mirrored'): '原点垂直镜像',
    ('Operator', 'Object Origin Mirrored'): '对象原点镜像',

    ('Operator', 'Round Cube'): '圆角立方体',
    ('Operator', 'Add Round Cube'): '添加圆角立方体',
    ('*', 'Odd Axis Align'): '奇数轴对齐',
    ('*', 'Arc:'): '弧：',
    ('*', 'Linear:'): '线：',

    ('*', 'Torus Objects'): '圆环对象',
    ('Operator', 'Twisted Torus'): '扭曲圆环',
    ('Operator', 'Add Twisted Torus'): '添加扭曲圆环',
    ('*', 'Twists'): '扭曲',
    ('*', 'Use Int/Ext Controls'): '使用 Int/Ext 控件',
    ('*', 'Inside Radius'): '内径',

    ('Operator', 'Supertoroid') : '超环',
    ('Operator', 'Add SuperToroid') : '添加超环',
    ('*', 'Big radius') : '大半径',
    ('*', 'Small radius') : '小半径',
    ('*', 'U-segments') : 'U 分段',
    ('*', 'V-segments') : 'V 分段',
    ('*', 'Ring manipulator') : '环修改',
    ('*', 'Cross manipulator') : '截面修改',
    ('*', 'Use Int. and Ext. radii') : '使用 Int. 和 Ext. 半径',

    ('Operator', 'Torus Knot') : '圆环结',
    ('Operator', 'Add Torus Knot') : '添加圆环结',
    ('*', 'Knot Type') : '结类型',
    ('Operator', 'Change TorusKnot') : '修改圆环结',
    
    ('*', 'Math Function') : '数学函数',
    ('Operator', 'Z Math Surface') : 'Z 函数曲面',
    ('Operator', 'Add Z Function Surface') : '添加 Z 函数曲面',
    ('*', 'Z Equation') : 'Z 方程',
    
    ('Operator', 'XYZ Math Surface') : 'XYZ 函数曲面',
    ('Operator', 'Add X, Y, Z Function Surface') : '添加 X, Y, Z 函数曲面',
    ('*', 'X equation') : 'X 方程',
    ('*', 'Y equation') : 'Y 方程',
    ('*', 'Z equation') : 'Z 方程',
    ('*', 'U min') : 'U 最小值',
    ('*', 'U max') : 'U 最大值',
    ('*', 'U step') : 'U 单步值',
    ('*', 'U wrap') : 'U 包裹',
    ('*', 'V min') : 'V 最小值',
    ('*', 'V max') : 'V 最大值',
    ('*', 'V step') : 'V 单步值',
    ('*', 'V wrap') : 'V 包裹',
    ('*', 'Close V') : 'V 闭合',
    ('*', 'Number of objects (n=0..N-1)') : '对象数量（n=0..N-1）',
    ('*', 'A helper function') : 'A 辅助函数',
    ('*', 'B helper function') : 'B 辅助函数',
    ('*', 'C helper function') : 'C 辅助函数',
    ('*', 'D helper function') : 'D 辅助函数',
    ('*', 'E helper function') : 'E 辅助函数',
    ('*', 'F helper function') : 'F 辅助函数',
    ('*', 'G helper function') : 'G 辅助函数',
    ('*', 'H helper function') : 'H 辅助函数',
    ('*', 'Show wireframe') : '显示线框',
    ('*', 'Show in edit mode') : '显示编辑模式',
    
    ('Operator', 'Regular Solid') : '常规实体',
    ('Operator', '(Regular) solids') : '常规实体',
    ('*', 'Tetrahedron') : '四面体',
    ('*', 'Hexahedron') : '六面体',
    ('*', 'Octahedron') : '八面体',
    ('*', 'Dodecahedron') : '十二面体',
    ('*', 'Icosahedron') : '二十面体',
    ('*', 'Vertex Truncation') : '顶点截断',
    ('*', 'Edge Truncation') : '边截断',
    ('*', 'Dual') : '双重',
    ('*', 'Keep Size') : '保持尺寸',
    
    ('Operator', 'Triangle') : '三角',

    ('*', 'Gears') : '齿轮',
    ('Operator', 'Gear') : '齿轮',
    ('Operator', 'Add Gear') : '添加齿轮',
    ('*', 'Keep Size') : '保持尺寸',
    ('*', 'Number of Teeth') : '齿数',
    ('*', 'Dedendum') : '齿根高',
    ('*', 'Addendum') : '齿顶高',
    ('*', 'Pressure Angle') : '压力角度',
    ('*', 'Skewness') : '倾斜度',
    ('*', 'Conical angle') : '锥形角度',
    ('*', 'Crown') : '冠',

    ('Operator', 'Worm') : '蜗轮',
    ('Operator', 'Add Worm Gear') : '添加蜗轮',
    ('*', 'Number of Rows') : '行数',
    ('*', 'Skewness per Row') : '每行倾斜度',
    ('Operator', 'Change WormGear') : '修改蜗轮',

    ('*', 'Pipe Joints') : '管道接头',
    ('Operator', 'Pipe Elbow') : '弯头',
    ('Operator', 'Add Pipe Elbow') : '添加管道弯头',
    ('*', 'Length Start') : '起始长度',
    ('*', 'End Length') : '结束长度',
    ('Operator', 'Change ElbowJoint') : '修改管道弯头',
    
    ('Operator', 'Pipe T-Joint') : 'T 形接头',
    ('Operator', 'Add Pipe Tee-Joint') : '添加 T 形管道接头',
    ('*', 'End Length') : '结束长度',
    ('*', 'Arm Length') : '臂长',
    ('Operator', 'Change TeeJoint') : '修改 T 形接头',
    
    ('Operator', 'Pipe Y-Joint') : 'Y 形接头',
    ('Operator', 'Add Pipe Wye-Joint') : '添加 Y 形管道接头',
    ('*', 'Angle 1') : '角度 1',
    ('*', 'Angle 2') : '角度 2',
    ('*', 'Length Arm 1') : '臂长 1',
    ('*', 'Length Arm 2') : '臂长 2',
    ('Operator', 'Change WyeJoint') : '修改 Y 形接头',
    
    ('Operator', 'Pipe Cross-Joint') : '十字接头',
    ('Operator', 'Add Pipe Cross-Joint') : '添加十字管道接头',
    ('*', 'Angle 3 (center)') : '角度 3 (中间)',
    ('*', 'Length Arm 3 (center)') : '臂长 3 (中间)',
    ('Operator', 'Change CrossJoint') : '修改十字接头',
    
    ('Operator', 'Pipe N-Joint') : '多头接头',
    ('Operator', 'Add Pipe N-Joint') : '添加管道多头接头',
    ('*', 'Arms / Joints') : '臂 / 接头数',
    ('Operator', 'Change NJoint') : '修改多头接头',
    
    ('*', 'Diamonds') : '钻石',
    ('Operator', 'Brilliant Diamond') : '亮钻',
    ('Operator', 'Custom Brilliant') : '自定义亮钻',
    ('*', 'Table width') : '平面宽度',
    ('*', 'Crown height') : '顶高',
    ('*', 'Girdle height') : '腰高',
    ('*', 'Real girdle') : '真实腰',
    ('*', 'Smooth girdle') : '平滑腰',
    ('*', 'Pavilion depth') : '底部深度',
    ('*', 'Upper facet factor') : '上面因子',
    ('*', 'Lower facet factor') : '下面因子',
    ('*', 'Culet size') : '下切尺寸',
    ('*', 'Retain lower angle') : '保持顶部角度',
    ('Operator', 'Change Brilliant') : '修改亮钻',
    
    ('Operator', 'Diamond') : '钻石',
    ('Operator', 'Add Diamond') : '添加钻石',
    ('*', 'Girdle Radius') : '腰半径',
    ('*', 'Table Radius') : '顶半径',
    ('*', 'Crown Height') : '顶高',
    ('*', 'Pavilion Height') : '底高',
    ('Operator', 'Change Diamond') : '修改钻石',
    
    ('Operator', 'Gem') : '宝石',
    ('Operator', 'Add Gem') : '添加宝石',
    ('Operator', 'Change Gem') : '修改宝石',
    ('*', 'Table height') : '顶高',
    ('*', 'Pavilion height') : '底高',
    
    ('Operator', 'Beam Builder') : '梁构造器',

    ('Operator', 'Wall Factory') : '墙工厂',
    ('Operator', 'Add a Masonry Wall') : '添加砌体墙',
    ('*', 'Construct') : '构建',
    ('*', 'Wall Size (area)') : '墙尺寸（面积）',
    ('*', 'Edging') : '边',
    ('*', 'Block Sizing') : '块大小',
    ('*', 'Merge Blocks') : '合并块',
    ('*', 'Variance') : '变化',
    ('*', 'Grout') : '灌浆',
    ('*', 'Wall Shape') : '墙形',
    ('*', 'Opening(s)') : '开口',
    ('*', 'Indent') : '缩进',
    ('*', 'Top Arch') : '顶拱',
    ('*', 'Bottom Arch') : '底拱',
    ('*', 'Slots') : '槽',
    ('*', 'Opening') : '开口',
    ('*', 'Crenels') : '垛口',
    ('*', 'Shelf') : '搁板',
    ('*', 'Backside') : '背面',
    ('*', 'Riser') : '平台',
    ('*', 'Tread') : '踏面',
    ('*', 'Steps Only') : '仅台阶',
    ('Operator', 'Change Wall') : '修改墙',

    ('Operator', 'Simple Star') : '简单星形',

    ('Operator', 'Step Pyramid') : '金字塔',
    ('Operator', 'Pyramid') : '金字塔',
    ('*', 'Number Sides') : '边数',
    ('*', 'Number of Steps') : '层数',
    ('*', 'Initial Width') : '初始宽度',
    ('*', 'Reduce Step By') : '每层减少',
    ('Operator', 'Change Pyramid') : '修改金字塔',

    ('Operator', 'Honeycomb') : '蜂窝',
    ('Operator', 'Add HoneyComb') : '添加蜂窝',
    ('Operator', 'Change HoneyComb') : '修改蜂窝',
    ('*', 'Num of rows') : '行数',
    ('*', 'Num of cols') : '列数',
    ('*', 'Cell Diameter') : '格直径',
    ('*', 'Edge Width') : '边宽',

    ('Operator', 'Teapot+') : '茶壶+',
    ('Operator', 'Add Teapot') : '添加茶壶',
    ('*', 'Object Type') : '对象类型',
    ('*', 'Teapot') : '茶壶',
    ('*', 'Tea Spoon') : '茶勺',
    
    ('Operator', 'Menger Sponge') : '门格海绵',
    
    ('Operator', 'Parent To Empty') : '添加父空对象',
    ('Operator', 'Parent to Empty') : '添加父空对象',
    ('*', 'Create Group') : '创建组',
    ('*', 'Add Prefix') : '添加前缀',
}