# -*- coding: utf-8 -*-

lang_dict = {
   ('*', 'Extra Objects') : '額外對象',
   ('*', 'Add Mesh: Extra Objects') : '添加網格：額外對象',
   ('*', 'Add extra mesh object types') : '添加額外網格對象類型',
   ('Operator', 'Rock Generator') : '岩石生成器',
   ('Operator', 'Add Rocks') : '添加岩石',
   ('*', 'Number of rocks') : '岩石數量',
   ('*', 'X scale') : 'X 軸縮放',
   ('*', 'X skew') : 'X 軸斜度',
   ('*', 'Y scale') : 'Y 軸縮放',
   ('*', 'Y skew') : 'Y 軸斜度',
   ('*', 'Z scale') : 'Z 軸縮放',
   ('*', 'Z skew') : 'Z 軸斜度',
   ('*', 'Scale displace textures') : '縮放置換紋理',
   ('*', 'Detail level') : '細節級別',
   ('*', 'Display Detail') : '顯示細節',
   ('*', 'Smooth Factor') : '平滑因子',
   ('*', 'Generate Rocks') : '生成岩石',
   ('*', 'Use a random seed') : '使用隨機種子',
   ('*', 'User seed') : '用戶隨機種子',
   ('*', 'Scaling Factor') : '縮放因子',
   ('*', 'Single Vert') : '單個點',
   ('Operator', 'Add Single Vert') : '添加單個點',
   ('*', 'Add a Single Vertice to Edit Mode') : '添加單個點並進入編輯模式',
   ('Operator', 'Object Origin Only') : '僅對象原點',
   ('*', 'Add an Object Origin to Edit Mode') : '添加對象原點進入編輯模式',
   ('Operator', 'Origin & Vert Mirrored') : '原點垂直鏡像',
   ('Operator', 'Object Origin Mirrored') : '對象原點鏡像',
   ('Operator', 'Round Cube') : '圓角立方體',
   ('Operator', 'Add Round Cube') : '添加圓角立方體',
   ('*', 'Odd Axis Align') : '奇數軸對齊',
   ('*', 'Arc:') : '弧：',
   ('*', 'Linear:') : '線：',
   ('*', 'Torus Objects') : '圓環對象',
   ('Operator', 'Twisted Torus') : '扭曲圓環',
   ('Operator', 'Add Twisted Torus') : '添加扭曲圓環',
   ('*', 'Twists') : '扭曲',
   ('*', 'Use Int/Ext Controls') : '使用 Int/Ext 控件',
   ('*', 'Inside Radius') : '內徑',
   ('Operator', 'Supertoroid') : '超環',
   ('Operator', 'Add SuperToroid') : '添加超環',
   ('*', 'Big radius') : '大半徑',
   ('*', 'Small radius') : '小半徑',
   ('*', 'U-segments') : 'U 分段',
   ('*', 'V-segments') : 'V 分段',
   ('*', 'Ring manipulator') : '環修改',
   ('*', 'Cross manipulator') : '截面修改',
   ('*', 'Use Int. and Ext. radii') : '使用 Int. 和 Ext. 半徑',
   ('Operator', 'Torus Knot') : '圓環結',
   ('Operator', 'Add Torus Knot') : '添加圓環結',
   ('*', 'Knot Type') : '結類型',
   ('Operator', 'Change TorusKnot') : '修改圓環結',
   ('*', 'Math Function') : '數學函數',
   ('Operator', 'Z Math Surface') : 'Z 函數曲面',
   ('Operator', 'Add Z Function Surface') : '添加 Z 函數曲面',
   ('*', 'Z Equation') : 'Z 方程',
   ('Operator', 'XYZ Math Surface') : 'XYZ 函數曲面',
   ('Operator', 'Add X, Y, Z Function Surface') : '添加 X, Y, Z 函數曲面',
   ('*', 'X equation') : 'X 方程',
   ('*', 'Y equation') : 'Y 方程',
   ('*', 'Z equation') : 'Z 方程',
   ('*', 'U min') : 'U 最小值',
   ('*', 'U max') : 'U 最大值',
   ('*', 'U step') : 'U 單步值',
   ('*', 'U wrap') : 'U 包裹',
   ('*', 'V min') : 'V 最小值',
   ('*', 'V max') : 'V 最大值',
   ('*', 'V step') : 'V 單步值',
   ('*', 'V wrap') : 'V 包裹',
   ('*', 'Close V') : 'V 閉合',
   ('*', 'Number of objects (n=0..N-1)') : '對象數量（n=0..N-1）',
   ('*', 'A helper function') : 'A 輔助函數',
   ('*', 'B helper function') : 'B 輔助函數',
   ('*', 'C helper function') : 'C 輔助函數',
   ('*', 'D helper function') : 'D 輔助函數',
   ('*', 'E helper function') : 'E 輔助函數',
   ('*', 'F helper function') : 'F 輔助函數',
   ('*', 'G helper function') : 'G 輔助函數',
   ('*', 'H helper function') : 'H 輔助函數',
   ('*', 'Show wireframe') : '顯示線框',
   ('*', 'Show in edit mode') : '顯示編輯模式',
   ('Operator', 'Regular Solid') : '常規實體',
   ('Operator', '(Regular) solids') : '常規實體',
   ('*', 'Tetrahedron') : '四面體',
   ('*', 'Hexahedron') : '六面體',
   ('*', 'Octahedron') : '八面體',
   ('*', 'Dodecahedron') : '十二面體',
   ('*', 'Icosahedron') : '二十面體',
   ('*', 'Vertex Truncation') : '頂點截斷',
   ('*', 'Edge Truncation') : '邊截斷',
   ('*', 'Dual') : '雙重',
   ('*', 'Keep Size') : '保持尺寸',
   ('Operator', 'Triangle') : '三角',
   ('*', 'Gears') : '齒輪',
   ('Operator', 'Gear') : '齒輪',
   ('Operator', 'Add Gear') : '添加齒輪',
   ('*', 'Number of Teeth') : '齒數',
   ('*', 'Dedendum') : '齒根高',
   ('*', 'Addendum') : '齒頂高',
   ('*', 'Pressure Angle') : '壓力角度',
   ('*', 'Skewness') : '傾斜度',
   ('*', 'Conical angle') : '錐形角度',
   ('*', 'Crown') : '冠',
   ('Operator', 'Worm') : '蝸輪',
   ('Operator', 'Add Worm Gear') : '添加蝸輪',
   ('*', 'Number of Rows') : '行數',
   ('*', 'Skewness per Row') : '每行傾斜度',
   ('Operator', 'Change WormGear') : '修改蝸輪',
   ('*', 'Pipe Joints') : '管道接頭',
   ('Operator', 'Pipe Elbow') : '彎頭',
   ('Operator', 'Add Pipe Elbow') : '添加管道彎頭',
   ('*', 'Length Start') : '起始長度',
   ('*', 'End Length') : '結束長度',
   ('Operator', 'Change ElbowJoint') : '修改管道彎頭',
   ('Operator', 'Pipe T-Joint') : 'T 形接頭',
   ('Operator', 'Add Pipe Tee-Joint') : '添加 T 形管道接頭',
   ('*', 'Arm Length') : '臂長',
   ('Operator', 'Change TeeJoint') : '修改 T 形接頭',
   ('Operator', 'Pipe Y-Joint') : 'Y 形接頭',
   ('Operator', 'Add Pipe Wye-Joint') : '添加 Y 形管道接頭',
   ('*', 'Angle 1') : '角度 1',
   ('*', 'Angle 2') : '角度 2',
   ('*', 'Length Arm 1') : '臂長 1',
   ('*', 'Length Arm 2') : '臂長 2',
   ('Operator', 'Change WyeJoint') : '修改 Y 形接頭',
   ('Operator', 'Pipe Cross-Joint') : '十字接頭',
   ('Operator', 'Add Pipe Cross-Joint') : '添加十字管道接頭',
   ('*', 'Angle 3 (center)') : '角度 3 (中間)',
   ('*', 'Length Arm 3 (center)') : '臂長 3 (中間)',
   ('Operator', 'Change CrossJoint') : '修改十字接頭',
   ('Operator', 'Pipe N-Joint') : '多頭接頭',
   ('Operator', 'Add Pipe N-Joint') : '添加管道多頭接頭',
   ('*', 'Arms / Joints') : '臂 / 接頭數',
   ('Operator', 'Change NJoint') : '修改多頭接頭',
   ('*', 'Diamonds') : '鑽石',
   ('Operator', 'Brilliant Diamond') : '亮鑽',
   ('Operator', 'Custom Brilliant') : '自定義亮鑽',
   ('*', 'Table width') : '平面寬度',
   ('*', 'Crown height') : '頂高',
   ('*', 'Girdle height') : '腰高',
   ('*', 'Real girdle') : '真實腰',
   ('*', 'Smooth girdle') : '平滑腰',
   ('*', 'Pavilion depth') : '底部深度',
   ('*', 'Upper facet factor') : '上面因子',
   ('*', 'Lower facet factor') : '下面因子',
   ('*', 'Culet size') : '下切尺寸',
   ('*', 'Retain lower angle') : '保持頂部角度',
   ('Operator', 'Change Brilliant') : '修改亮鑽',
   ('Operator', 'Diamond') : '鑽石',
   ('Operator', 'Add Diamond') : '添加鑽石',
   ('*', 'Girdle Radius') : '腰半徑',
   ('*', 'Table Radius') : '頂半徑',
   ('*', 'Crown Height') : '頂高',
   ('*', 'Pavilion Height') : '底高',
   ('Operator', 'Change Diamond') : '修改鑽石',
   ('Operator', 'Gem') : '寶石',
   ('Operator', 'Add Gem') : '添加寶石',
   ('Operator', 'Change Gem') : '修改寶石',
   ('*', 'Table height') : '頂高',
   ('*', 'Pavilion height') : '底高',
   ('Operator', 'Beam Builder') : '樑構造器',
   ('Operator', 'Wall Factory') : '牆工廠',
   ('Operator', 'Add a Masonry Wall') : '添加砌體牆',
   ('*', 'Construct') : '構建',
   ('*', 'Wall Size (area)') : '牆尺寸（面積）',
   ('*', 'Edging') : '邊',
   ('*', 'Block Sizing') : '塊大小',
   ('*', 'Merge Blocks') : '合併塊',
   ('*', 'Variance') : '變化',
   ('*', 'Grout') : '灌漿',
   ('*', 'Wall Shape') : '牆形',
   ('*', 'Opening(s)') : '開口',
   ('*', 'Indent') : '縮進',
   ('*', 'Top Arch') : '頂拱',
   ('*', 'Bottom Arch') : '底拱',
   ('*', 'Slots') : '槽',
   ('*', 'Opening') : '開口',
   ('*', 'Crenels') : '垛口',
   ('*', 'Shelf') : '擱板',
   ('*', 'Backside') : '背面',
   ('*', 'Riser') : '平臺',
   ('*', 'Tread') : '踏面',
   ('*', 'Steps Only') : '僅臺階',
   ('Operator', 'Change Wall') : '修改牆',
   ('Operator', 'Simple Star') : '簡單星形',
   ('Operator', 'Step Pyramid') : '金字塔',
   ('Operator', 'Pyramid') : '金字塔',
   ('*', 'Number Sides') : '邊數',
   ('*', 'Number of Steps') : '層數',
   ('*', 'Initial Width') : '初始寬度',
   ('*', 'Reduce Step By') : '每層減少',
   ('Operator', 'Change Pyramid') : '修改金字塔',
   ('Operator', 'Honeycomb') : '蜂窩',
   ('Operator', 'Add HoneyComb') : '添加蜂窩',
   ('Operator', 'Change HoneyComb') : '修改蜂窩',
   ('*', 'Num of rows') : '行數',
   ('*', 'Num of cols') : '列數',
   ('*', 'Cell Diameter') : '格直徑',
   ('*', 'Edge Width') : '邊寬',
   ('Operator', 'Teapot+') : '茶壺+',
   ('Operator', 'Add Teapot') : '添加茶壺',
   ('*', 'Object Type') : '對象類型',
   ('*', 'Teapot') : '茶壺',
   ('*', 'Tea Spoon') : '茶勺',
   ('Operator', 'Menger Sponge') : '門格海綿',
   ('Operator', 'Parent To Empty') : '添加父空對象',
   ('Operator', 'Parent to Empty') : '添加父空對象',
   ('*', 'Create Group') : '創建組',
   ('*', 'Add Prefix') : '添加前綴',
}