lang_dict = {
    ('*', '3D View: Hard Ops 9'): '3D 视图：Hard Ops 9',
    ('*', 'Ui'): '界面',
    ('*', 'Links/Help'): '链接/帮助',
    ('*', 'Addons'): '插件',
    ('*', 'HardOps panel category'): 'HardOps 面板类别',
    ('*', 'Hardops UI'): 'HardOps 界面',
    ('*', 'Modal Scale'): '模态界面缩放',
    ('*', 'Modal UI Size'): '模态界面尺寸',
    ('*', 'Modal UI Display Method'): '模态界面显示方式',
    ('*', 'Display options'): '显示选项',
    ('*', 'Modal Background'): '模态背景',
    ('*', 'Modal Drop Shadow'): '模态投影',
    ('*', 'Modal Cell Border'): '模态格边框',
    ('*', 'Modal Drop Shadow Offset'): '模态投影偏移',
    ('*', 'Modal Cell Background'): '模态格背景',
    ('*', 'Kit Ops Display Count'): 'Kit Ops 显示数量',
    ('*', 'Fade options'): '淡入淡出选项',
    ('*', 'Modal fade in time'): '模态淡入时间',
    ('*', 'Modal fade out time'): '模态淡出时间',
    ('*', 'Fast UI options'): '快速界面选项',
    ('*', 'Fast UI panel offset'): '偏移',
    ('*', 'Fast UI Mod count'): '模块数量',
    ('*', 'Fast UI auto show Help'): '自动显示帮助',
    ('*', 'Fast UI auto show Mods'): '自动显示模块',
    ('*', 'Fast UI show Help label in fast UI'): '在快速界面显示帮助标签',
    ('*', 'Fast UI Mods Offset'): '模块偏移',
    ('*', 'Fast UI show Mods label'): '显示模块标签',
    ('*', 'Fast UI Mods Size'): '模块尺寸',
    ('*', 'Fast UI Help Offset'): '帮助偏移',
    ('*', 'Fast UI Help Size'): '帮助尺寸',
    ('*', 'Fast UI Main Y Offset'): '主 Y 轴偏移',
    ('*', 'Turn Cursor Warp on or off'): '开启或关闭游标扭曲',
    ('*', 'Cursor Warp Padding'): '游标扭曲填充',
    ('*', 'Display Warp Border'): '显示扭曲边框',
    ('*', 'Display Style'): '显示样式',
    ('*', 'Display lenght'): '显示长度',
    ('*', 'Display width'): '显示宽度',
    ('*', 'Auto Hide N-Panel'): '自动隐藏边栏',
    ('*', 'Auto Hide T-Panel'): '自动隐藏工具栏',
    ('*', 'Operator UI options'): '操作界面选项',
    ('*', 'Operator UI offset'): '界面偏移',
    ('*', 'Operator Display Time'): '界面显示时间',
    ('*', 'Operator Fade Time'): '界面淡出时间',
    ('*', 'Operator Display'): '操作显示',
    ('*', 'Extra Info Display'): '额外信息显示',
    ('*', 'Operator Background'): '操作背景',
    ('*', 'Operator Border'): '操作边框',
    ('*', 'Operator Border Size'): '操作边框尺寸',
    ('*', 'Material List Count'): '材质列表数量',
    ('*', 'Sequential Q Menus'): '排序 Q 菜单',
    ('*', 'Popup Dpi Factoring'): '使用 Dpi 缩放',
    ('*', 'Helper popup'): '助手弹出',
    ('*', 'Bevel Helper popup'): '斜角助手弹出窗口',
    ('*', 'Use KITOPS popup'): '使用 KITOPS 弹出窗口',
    ('*', 'Hardops Properties:'): 'Hardops 属性：',
    ('*', 'Modal Handedness'): '左右手',
    ('*', 'KitOps Popup Type'): 'KitOps 弹出类型',
    ('*', 'Expansive'): '展开',
    ('*', 'Array Q Menu Option'): 'Q 菜单阵列选项',
    ('*', 'Classic'): '经典',
    ('*', 'Array V1'): '阵列 V1',
    ('*', 'Array V2'): '阵列 V2',
    ('*', 'ST3 Array Gizmo'): '阵列 V1 Gizmo',
    ('*', 'MeshClean Mode'): '网格清理模式',
    ('*', 'Bevel Profile'): '倒角轮廓',
    ('*', 'Bool Scroll System'): '布尔滚动系统',
    ('*', 'Profile Folder'): '设置文件夹',
    ('*', 'Lights Folder'): '灯光文件夹',
    ('*', 'Blank Mat Scroll to Viewport Mat'): '空白材质滚动到视口材质',
    ('*', 'Radial / Twist (Render Toggle)'): '径向/扭曲（渲染切换）',
    ('*', 'To_Cam Behavior'): '转到相机行为',
    ('*', 'Frontal'): '前',
    ('*', 'Viewport+ Set Render'): '视口+ 设置渲染',
    ('*', 'Blank Light Constraint'): '空白光约束',
    ('*', 'Sharpen Options:'): '锐化选项：',
    ('*', 'Sharpness Angle'): '锐化角度',
    ('*', 'Sharp : Mark:'): '锐化 - 标记：',
    ('*', 'Remove Cutters:'): '移除刀具：',
    ('*', 'Sharpen '): '锐化',
    ('*', 'Smart Apply '): '智能应用',
    ('*', 'Debug Options'): '调试选项',
    ('*', 'Hardops Drawing:'): 'Hardops 绘图：',
    ('*', 'Enable Overlays'): '启用叠加层',
    ('*', 'UI System:'): '界面系统：',
    ('*', 'Cell Background Color'): '格背景色',
    ('*', 'Main Text Color'): '主文字色',
    ('*', 'Secoundary Text Color'): '第二文字色',
    ('*', 'Highlight Color'): '高亮色',
    ('*', 'Drop Shadow Color'): '投影色',
    ('*', 'Border Color'): '边框色',
    ('*', 'Hover Color'): '悬停色',
    ('*', 'Drag Color'): '拖动色',
    ('*', 'Logo:'): '徽标：',
    ('*', 'Display Logo'): '显示徽标',
    ('*', 'Logo Color'): '徽标颜色',
    ('*', 'Boolshape Color'): '布尔形颜色',
    ('*', 'Logo Size'): '徽标尺寸',
    ('*', 'Logo X Position'): '徽标 X 位置',
    ('*', 'Logo Y Position'): '徽标 Y 位置',
    ('*', 'modal mirror scale'): '模态镜像缩放',
    ('*', 'modal mirror sides scale'): '模态镜像边缩放',
    ('*', 'Active tool:'): '活动工具：',
    ('*', 'Dots colors'): '点颜色',
    ('*', 'Display Dots Text'): '显示点文字',
    ('*', '     Basic Dots'): '     基本点',
    ('*', '     Displace'): '     置换',
    ('*', 'Displace X'): '置换 X',
    ('*', 'Displace Y'): '置换 Y',
    ('*', 'Displace Z'): '置换 Z',
    ('*', '     Screw'): '     螺旋',
    ('*', 'Screw X'): '螺旋 X',
    ('*', 'Screw Y'): '螺旋 Y',
    ('*', 'Screw Z'): '螺旋 Z',
    ('*', '     Solidify'): '     实体',
    ('*', 'Solidify X'): '实体 X',
    ('*', 'Solidify Y'): '实体 Y',
    ('*', 'Solidify Z'): '实体 Z',
    ('*', 'Solidify C'): '实体 C',
    ('*', '     Array'): '     阵列',
    ('*', 'Array X'): '阵列 X',
    ('*', 'Array Y'): '阵列 Y',
    ('*', 'Array Z'): '阵列 Z',
    ('*', '     Simple Deform'): '     简单变形',
    ('*', 'Deform X'): '变形 X',
    ('*', 'Deform Y'): '变形 Y',
    ('*', 'Deform Z'): '变形 Z',
    ('*', '     Wireframe'): '     线框',
    ('*', '     Bevel'): '     倒角',
    ('*', '     Booleandots'): '     布尔点',
    ('*', 'Slash'): '削减',
    ('*', 'Sharpen keymap'): '锐化键位映射',
    ('*', 'Sharpen Activation Hotkeys'): '锐化激活热键',
    ('*', 'Resharp'): '重建形',
    ('*', 'CsharpBevel'): 'C 形倒角',
    ('*', 'Weighted Mod'): '加权模组',
    ('*', 'Do not remove hotkeys, disable them instead.'): '不要删除热键，而是禁用它们。',
    ('*', 'Hotkeys'): '热键',
    ('*', 'Main Pie'): '主饼形菜单',
    ('*', 'Main Menu'): '主菜单',
    ('*', 'menus / systems:'): '菜单 / 系统：',
    ('*', 'No hotkey entry found'): '找不到热键记录',
    ('*', 'Material list'): '材质列表',
    ('*', 'operators:'): '操作：',
    ('*', 'Mirror Gizmo'): '镜像 Gizmo',
    ('*', 'Bevel Boolean Multi_Assist'): '倒角布尔辅助',
    ('*', 'booleans:'): '布尔：',
    ('*', 'Hops Union Boolean'): 'Hops 并集布尔',
    ('*', 'Hops Difference Boolean'): 'Hops 差值布尔',
    ('*', 'Hops Slash Boolean'): 'Hops 切痕布尔',
    ('*', 'Hops Inset Boolean'): 'Hops 内插布尔',
    ('*', 'restore hotkeys from interface tab'): '从界面标签恢复热键',
    ('*', 'edit mode:'): '编辑模式：',
    ('*', 'Hops Union Boolean Edit Mode'): 'Hops 编辑模式并集布尔',
    ('*', 'Hops Difference Boolean Edit Mode'): 'Hops 编辑模式差值布尔',
    ('*', '3rd Party:'): '第三方：',
    ('*', 'External Support:'): '外部支持：',
    ('*', 'nothing to see here'): '无',
    ('*', 'Extended:'): '扩展：',
    ('*', 'Hops Tilde Remap'): 'Hops 波浪重映射',
    ('*', 'Helper Width'): '助手宽度',
    ('Operator', 'Hops sharpen'): 'Hops 锐化',
    ('Operator', 'Sharpen'): '锐化',
    ('*', 'Sharpen'): '锐化',
    ('*', 'Ssharp'): 'S 形',
    ('*', 'Csharp'): 'C 形',
    ('*', 'Cleansharp'): '干净利落',
    ('*', 'MeshTools'): '网格工具',
    ('Operator', 'Array V1'): '阵列 V1',
    ('Operator', 'Array V2'): '阵列 V2',
    ('Operator', 'Mirror / Array'): '镜像与阵列',
    ('*', 'Sharpening Parameters'): '锐化参数',
    ('*', 'Additive Mode'): '添加模式',
    ('*', 'Add bevel modifier'): '添加倒角修改器',
    ('*', 'Modifiers Applied By Csharp'): 'C 形锐化应用修改器',
    ('*', 'Bool'): '布尔',
    ('*', 'Sol'): '实体',
    ('*', 'Bev'): '倒角',
    ('*', 'Mir'): '镜像',
    ('*', 'Arr'): '阵列',
    ('*', 'Remove Cutters'): '移除刀具',
    ('*', 'Vertex Group bevels applied only'): '仅应用倒角到顶点组',
    ('*', 'RemoveModifiers?'): '移除修改器',
    ('*', 'Clear Sharps'): '清除锐化',
    ('*', 'Clear Bevels'): '清除倒角',
    ('*', 'Clear Crease'): '清除折痕',
    ('*', 'Clear Seam'): '清除接缝',
    ('*', 'Clear Custom Data'): '清除自定义数据',
    ('Operator', 'HOps Helper'): 'HOps 助手',
    ('*', 'Adjust tool settings'): '调整工具设置',
    ('*', 'Adjust object settings'): '调整对象设置',
    ('*', 'Adjust constraint settings'): '调整约束设置',
    ('*', 'Adjust constraint settings'): '调整约束设置',
    ('*', 'Adjust modifier settings'): '调整修改器设置',
    ('*', 'Adjust mesh settings'): '调整网格设置',
    ('*', 'Adjust material settings'): '调整材质设置',
    ('*', 'Cutting Material'): '切割材料',
    ('Operator', 'Add Blank Material'): '添加空白材质',
    ('Operator', 'Material Scroll'): '材质滚动',
    ('Operator', 'Blank Light'): '空白灯光',
    ('*', 'Auto T Panel'): '自动工具栏',
    ('*', 'Auto N Panel'): '自动边栏',
    ('*', 'Modal BG Color'): '模态背景色',
    ('*', 'Modal Help Scale:'): '模态帮助缩放：',
    ('*', 'Modal Warp'): '模态换行',
    ('*', 'Operator Text'): '操作文字',
    ('*', 'Array Type'): '阵列类型',
    ('*', 'Array V1 Gizmo'): '阵列 V1 Gizmo',
    ('*', 'Bool Scroll'): '布尔滚动',
    ('*', 'To_Cam :'): '转到相机：',

}