# -*- coding: utf-8 -*-

lang_dict = {
   ('*', '3D View: Hard Ops 9') : '3D 視圖：Hard Ops 9',
   ('*', 'Ui') : '界面',
   ('*', 'Links/Help') : '鏈接/幫助',
   ('*', 'Addons') : '插件',
   ('*', 'HardOps panel category') : 'HardOps 面板類別',
   ('*', 'Hardops UI') : 'HardOps 界面',
   ('*', 'Modal Scale') : '模態界面縮放',
   ('*', 'Modal UI Size') : '模態界面尺寸',
   ('*', 'Modal UI Display Method') : '模態界面顯示方式',
   ('*', 'Display options') : '顯示選項',
   ('*', 'Modal Background') : '模態背景',
   ('*', 'Modal Drop Shadow') : '模態投影',
   ('*', 'Modal Cell Border') : '模態格邊框',
   ('*', 'Modal Drop Shadow Offset') : '模態投影偏移',
   ('*', 'Modal Cell Background') : '模態格背景',
   ('*', 'Kit Ops Display Count') : 'Kit Ops 顯示數量',
   ('*', 'Fade options') : '淡入淡出選項',
   ('*', 'Modal fade in time') : '模態淡入時間',
   ('*', 'Modal fade out time') : '模態淡出時間',
   ('*', 'Fast UI options') : '快速界面選項',
   ('*', 'Fast UI panel offset') : '偏移',
   ('*', 'Fast UI Mod count') : '模塊數量',
   ('*', 'Fast UI auto show Help') : '自動顯示幫助',
   ('*', 'Fast UI auto show Mods') : '自動顯示模塊',
   ('*', 'Fast UI show Help label in fast UI') : '在快速界面顯示幫助標籤',
   ('*', 'Fast UI Mods Offset') : '模塊偏移',
   ('*', 'Fast UI show Mods label') : '顯示模塊標籤',
   ('*', 'Fast UI Mods Size') : '模塊尺寸',
   ('*', 'Fast UI Help Offset') : '幫助偏移',
   ('*', 'Fast UI Help Size') : '幫助尺寸',
   ('*', 'Fast UI Main Y Offset') : '主 Y 軸偏移',
   ('*', 'Turn Cursor Warp on or off') : '開啟或關閉遊標扭曲',
   ('*', 'Cursor Warp Padding') : '遊標扭曲填充',
   ('*', 'Display Warp Border') : '顯示扭曲邊框',
   ('*', 'Display Style') : '顯示樣式',
   ('*', 'Display lenght') : '顯示長度',
   ('*', 'Display width') : '顯示寬度',
   ('*', 'Auto Hide N-Panel') : '自動隱藏邊欄',
   ('*', 'Auto Hide T-Panel') : '自動隱藏工具欄',
   ('*', 'Operator UI options') : '操作界面選項',
   ('*', 'Operator UI offset') : '界面偏移',
   ('*', 'Operator Display Time') : '界面顯示時間',
   ('*', 'Operator Fade Time') : '界面淡出時間',
   ('*', 'Operator Display') : '操作顯示',
   ('*', 'Extra Info Display') : '額外信息顯示',
   ('*', 'Operator Background') : '操作背景',
   ('*', 'Operator Border') : '操作邊框',
   ('*', 'Operator Border Size') : '操作邊框尺寸',
   ('*', 'Material List Count') : '材質列表數量',
   ('*', 'Sequential Q Menus') : '排序 Q 菜單',
   ('*', 'Popup Dpi Factoring') : '使用 Dpi 縮放',
   ('*', 'Helper popup') : '助手彈出',
   ('*', 'Bevel Helper popup') : '斜角助手彈出窗口',
   ('*', 'Use KITOPS popup') : '使用 KITOPS 彈出窗口',
   ('*', 'Hardops Properties:') : 'Hardops 屬性：',
   ('*', 'Modal Handedness') : '左右手',
   ('*', 'KitOps Popup Type') : 'KitOps 彈出類型',
   ('*', 'Expansive') : '展開',
   ('*', 'Array Q Menu Option') : 'Q 菜單陣列選項',
   ('*', 'Classic') : '經典',
   ('*', 'Array V1') : '陣列 V1',
   ('*', 'Array V2') : '陣列 V2',
   ('*', 'ST3 Array Gizmo') : '陣列 V1 Gizmo',
   ('*', 'MeshClean Mode') : '網格清理模式',
   ('*', 'Bevel Profile') : '倒角輪廓',
   ('*', 'Bool Scroll System') : '布爾滾動系統',
   ('*', 'Profile Folder') : '設置文件夾',
   ('*', 'Lights Folder') : '燈光文件夾',
   ('*', 'Blank Mat Scroll to Viewport Mat') : '空白材質滾動到視口材質',
   ('*', 'Radial / Twist (Render Toggle)') : '徑向/扭曲（渲染切換）',
   ('*', 'To_Cam Behavior') : '轉到相機行為',
   ('*', 'Frontal') : '前',
   ('*', 'Viewport+ Set Render') : '視口+ 設置渲染',
   ('*', 'Blank Light Constraint') : '空白光約束',
   ('*', 'Sharpen Options:') : '銳化選項：',
   ('*', 'Sharpness Angle') : '銳化角度',
   ('*', 'Sharp : Mark:') : '銳化 - 標記：',
   ('*', 'Remove Cutters:') : '移除刀具：',
   ('*', 'Sharpen ') : '銳化',
   ('*', 'Smart Apply ') : '智能應用',
   ('*', 'Debug Options') : '調試選項',
   ('*', 'Hardops Drawing:') : 'Hardops 繪圖：',
   ('*', 'Enable Overlays') : '啟用疊加層',
   ('*', 'UI System:') : '界面系統：',
   ('*', 'Cell Background Color') : '格背景色',
   ('*', 'Main Text Color') : '主文字色',
   ('*', 'Secoundary Text Color') : '第二文字色',
   ('*', 'Highlight Color') : '高亮色',
   ('*', 'Drop Shadow Color') : '投影色',
   ('*', 'Border Color') : '邊框色',
   ('*', 'Hover Color') : '懸停色',
   ('*', 'Drag Color') : '拖動色',
   ('*', 'Logo:') : '徽標：',
   ('*', 'Display Logo') : '顯示徽標',
   ('*', 'Logo Color') : '徽標顏色',
   ('*', 'Boolshape Color') : '布爾形顏色',
   ('*', 'Logo Size') : '徽標尺寸',
   ('*', 'Logo X Position') : '徽標 X 位置',
   ('*', 'Logo Y Position') : '徽標 Y 位置',
   ('*', 'modal mirror scale') : '模態鏡像縮放',
   ('*', 'modal mirror sides scale') : '模態鏡像邊縮放',
   ('*', 'Active tool:') : '活動工具：',
   ('*', 'Dots colors') : '點顏色',
   ('*', 'Display Dots Text') : '顯示點文字',
   ('*', '     Basic Dots') : '     基本點',
   ('*', '     Displace') : '     置換',
   ('*', 'Displace X') : '置換 X',
   ('*', 'Displace Y') : '置換 Y',
   ('*', 'Displace Z') : '置換 Z',
   ('*', '     Screw') : '     螺旋',
   ('*', 'Screw X') : '螺旋 X',
   ('*', 'Screw Y') : '螺旋 Y',
   ('*', 'Screw Z') : '螺旋 Z',
   ('*', '     Solidify') : '     實體',
   ('*', 'Solidify X') : '實體 X',
   ('*', 'Solidify Y') : '實體 Y',
   ('*', 'Solidify Z') : '實體 Z',
   ('*', 'Solidify C') : '實體 C',
   ('*', '     Array') : '     陣列',
   ('*', 'Array X') : '陣列 X',
   ('*', 'Array Y') : '陣列 Y',
   ('*', 'Array Z') : '陣列 Z',
   ('*', '     Simple Deform') : '     簡單變形',
   ('*', 'Deform X') : '變形 X',
   ('*', 'Deform Y') : '變形 Y',
   ('*', 'Deform Z') : '變形 Z',
   ('*', '     Wireframe') : '     線框',
   ('*', '     Bevel') : '     倒角',
   ('*', '     Booleandots') : '     布爾點',
   ('*', 'Slash') : '削減',
   ('*', 'Sharpen keymap') : '銳化鍵位映射',
   ('*', 'Sharpen Activation Hotkeys') : '銳化激活熱鍵',
   ('*', 'Resharp') : '重建形',
   ('*', 'CsharpBevel') : 'C 形倒角',
   ('*', 'Weighted Mod') : '加權模組',
   ('*', 'Do not remove hotkeys, disable them instead.') : '不要刪除熱鍵，而是禁用它們。',
   ('*', 'Hotkeys') : '熱鍵',
   ('*', 'Main Pie') : '主餅形菜單',
   ('*', 'Main Menu') : '主菜單',
   ('*', 'menus / systems:') : '菜單 / 系統：',
   ('*', 'No hotkey entry found') : '找不到熱鍵記錄',
   ('*', 'Material list') : '材質列表',
   ('*', 'operators:') : '操作：',
   ('*', 'Mirror Gizmo') : '鏡像 Gizmo',
   ('*', 'Bevel Boolean Multi_Assist') : '倒角布爾輔助',
   ('*', 'booleans:') : '布爾：',
   ('*', 'Hops Union Boolean') : 'Hops 並集布爾',
   ('*', 'Hops Difference Boolean') : 'Hops 差值布爾',
   ('*', 'Hops Slash Boolean') : 'Hops 切痕布爾',
   ('*', 'Hops Inset Boolean') : 'Hops 內插布爾',
   ('*', 'restore hotkeys from interface tab') : '從界面標籤恢復熱鍵',
   ('*', 'edit mode:') : '編輯模式：',
   ('*', 'Hops Union Boolean Edit Mode') : 'Hops 編輯模式並集布爾',
   ('*', 'Hops Difference Boolean Edit Mode') : 'Hops 編輯模式差值布爾',
   ('*', '3rd Party:') : '第三方：',
   ('*', 'External Support:') : '外部支持：',
   ('*', 'nothing to see here') : '無',
   ('*', 'Extended:') : '擴展：',
   ('*', 'Hops Tilde Remap') : 'Hops 波浪重映射',
   ('*', 'Helper Width') : '助手寬度',
   ('Operator', 'Hops sharpen') : 'Hops 銳化',
   ('Operator', 'Sharpen') : '銳化',
   ('*', 'Sharpen') : '銳化',
   ('*', 'Ssharp') : 'S 形',
   ('*', 'Csharp') : 'C 形',
   ('*', 'Cleansharp') : '乾淨利落',
   ('*', 'MeshTools') : '網格工具',
   ('Operator', 'Array V1') : '陣列 V1',
   ('Operator', 'Array V2') : '陣列 V2',
   ('Operator', 'Mirror / Array') : '鏡像與陣列',
   ('*', 'Sharpening Parameters') : '銳化參數',
   ('*', 'Additive Mode') : '添加模式',
   ('*', 'Add bevel modifier') : '添加倒角修改器',
   ('*', 'Modifiers Applied By Csharp') : 'C 形銳化應用修改器',
   ('*', 'Bool') : '布爾',
   ('*', 'Sol') : '實體',
   ('*', 'Bev') : '倒角',
   ('*', 'Mir') : '鏡像',
   ('*', 'Arr') : '陣列',
   ('*', 'Remove Cutters') : '移除刀具',
   ('*', 'Vertex Group bevels applied only') : '僅應用倒角到頂點組',
   ('*', 'RemoveModifiers?') : '移除修改器',
   ('*', 'Clear Sharps') : '清除銳化',
   ('*', 'Clear Bevels') : '清除倒角',
   ('*', 'Clear Crease') : '清除摺痕',
   ('*', 'Clear Seam') : '清除接縫',
   ('*', 'Clear Custom Data') : '清除自定義數據',
   ('Operator', 'HOps Helper') : 'HOps 助手',
   ('*', 'Adjust tool settings') : '調整工具設置',
   ('*', 'Adjust object settings') : '調整對象設置',
   ('*', 'Adjust constraint settings') : '調整約束設置',
   ('*', 'Adjust modifier settings') : '調整修改器設置',
   ('*', 'Adjust mesh settings') : '調整網格設置',
   ('*', 'Adjust material settings') : '調整材質設置',
   ('*', 'Cutting Material') : '切割材料',
   ('Operator', 'Add Blank Material') : '添加空白材質',
   ('Operator', 'Material Scroll') : '材質滾動',
   ('Operator', 'Blank Light') : '空白燈光',
   ('*', 'Auto T Panel') : '自動工具欄',
   ('*', 'Auto N Panel') : '自動邊欄',
   ('*', 'Modal BG Color') : '模態背景色',
   ('*', 'Modal Help Scale:') : '模態幫助縮放：',
   ('*', 'Modal Warp') : '模態換行',
   ('*', 'Operator Text') : '操作文字',
   ('*', 'Array Type') : '陣列類型',
   ('*', 'Array V1 Gizmo') : '陣列 V1 Gizmo',
   ('*', 'Bool Scroll') : '布爾滾動',
   ('*', 'To_Cam :') : '轉到相機：',
}